// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: accounts.sql

package sharesqlc

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createShareAccount = `-- name: CreateShareAccount :one
INSERT INTO share_accounts (member_id, branch_id, status, opened_at)
VALUES ($1, $2, 'active', NOW())
RETURNING id, member_id, branch_id, status, opened_at, is_deleted, created_at, updated_at
`

type CreateShareAccountParams struct {
	MemberID pgtype.UUID `json:"memberId"`
	BranchID int64       `json:"branchId"`
}

func (q *Queries) CreateShareAccount(ctx context.Context, arg CreateShareAccountParams) (ShareAccount, error) {
	row := q.db.QueryRow(ctx, createShareAccount, arg.MemberID, arg.BranchID)
	var i ShareAccount
	err := row.Scan(
		&i.ID,
		&i.MemberID,
		&i.BranchID,
		&i.Status,
		&i.OpenedAt,
		&i.IsDeleted,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getAccountByID = `-- name: GetAccountByID :one
SELECT sa.id, sa.member_id, sa.branch_id, sa.status, sa.opened_at, sa.is_deleted, sa.created_at, sa.updated_at, m.member_number, mp.full_name AS member_name
FROM share_accounts AS sa
JOIN members AS m ON m.id = sa.member_id
LEFT JOIN member_profiles AS mp ON mp.member_id = m.id
WHERE sa.id = $1 AND sa.is_deleted = FALSE
`

type GetAccountByIDRow struct {
	ShareAccount ShareAccount `json:"shareAccount"`
	MemberNumber int64        `json:"memberNumber"`
	MemberName   pgtype.Text  `json:"memberName"`
}

func (q *Queries) GetAccountByID(ctx context.Context, id pgtype.UUID) (GetAccountByIDRow, error) {
	row := q.db.QueryRow(ctx, getAccountByID, id)
	var i GetAccountByIDRow
	err := row.Scan(
		&i.ShareAccount.ID,
		&i.ShareAccount.MemberID,
		&i.ShareAccount.BranchID,
		&i.ShareAccount.Status,
		&i.ShareAccount.OpenedAt,
		&i.ShareAccount.IsDeleted,
		&i.ShareAccount.CreatedAt,
		&i.ShareAccount.UpdatedAt,
		&i.MemberNumber,
		&i.MemberName,
	)
	return i, err
}

const getAccountByMemberID = `-- name: GetAccountByMemberID :one
SELECT id, member_id, branch_id, status, opened_at, is_deleted, created_at, updated_at FROM share_accounts
WHERE member_id = $1 AND is_deleted = FALSE
`

func (q *Queries) GetAccountByMemberID(ctx context.Context, memberID pgtype.UUID) (ShareAccount, error) {
	row := q.db.QueryRow(ctx, getAccountByMemberID, memberID)
	var i ShareAccount
	err := row.Scan(
		&i.ID,
		&i.MemberID,
		&i.BranchID,
		&i.Status,
		&i.OpenedAt,
		&i.IsDeleted,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getAccountByMemberIdentifier = `-- name: GetAccountByMemberIdentifier :one
SELECT sa.id, sa.member_id, sa.branch_id, sa.status, sa.opened_at, sa.is_deleted, sa.created_at, sa.updated_at, m.member_number, mp.full_name AS member_name
FROM share_accounts AS sa
JOIN members AS m ON m.id = sa.member_id
LEFT JOIN member_profiles AS mp ON mp.member_id = m.id
WHERE sa.is_deleted = FALSE
  AND m.is_deleted = FALSE
  AND sa.branch_id = $1
  AND m.branch_id = $1
  AND (m.member_number = $2::bigint
       OR m.national_id = $3::text)
`

type GetAccountByMemberIdentifierParams struct {
	BranchID     int64       `json:"branchId"`
	MemberNumber pgtype.Int8 `json:"memberNumber"`
	NationalID   pgtype.Text `json:"nationalId"`
}

type GetAccountByMemberIdentifierRow struct {
	ShareAccount ShareAccount `json:"shareAccount"`
	MemberNumber int64        `json:"memberNumber"`
	MemberName   pgtype.Text  `json:"memberName"`
}

func (q *Queries) GetAccountByMemberIdentifier(ctx context.Context, arg GetAccountByMemberIdentifierParams) (GetAccountByMemberIdentifierRow, error) {
	row := q.db.QueryRow(ctx, getAccountByMemberIdentifier, arg.BranchID, arg.MemberNumber, arg.NationalID)
	var i GetAccountByMemberIdentifierRow
	err := row.Scan(
		&i.ShareAccount.ID,
		&i.ShareAccount.MemberID,
		&i.ShareAccount.BranchID,
		&i.ShareAccount.Status,
		&i.ShareAccount.OpenedAt,
		&i.ShareAccount.IsDeleted,
		&i.ShareAccount.CreatedAt,
		&i.ShareAccount.UpdatedAt,
		&i.MemberNumber,
		&i.MemberName,
	)
	return i, err
}

const listShareAccounts = `-- name: ListShareAccounts :many
SELECT
    sa.id,
    sa.member_id,
    sa.branch_id,
    sa.status,
    sa.opened_at,
    sa.created_at,
    sa.updated_at,
    m.member_number,
    mp.full_name AS member_name
FROM share_accounts AS sa
JOIN members AS m ON m.id = sa.member_id
LEFT JOIN member_profiles AS mp ON mp.member_id = m.id
WHERE sa.is_deleted = FALSE
  AND m.is_deleted = FALSE
  AND sa.branch_id = $1
  AND ($2::share_account_status IS NULL OR sa.status = $2)
  AND (
      $3::bigint IS NULL
      OR (m.member_number, sa.id) > (
          $3::bigint,
          $4::uuid
      )
  )
ORDER BY m.member_number ASC, sa.id ASC
LIMIT $5
`

type ListShareAccountsParams struct {
	BranchID           int64                  `json:"branchId"`
	StatusFilter       NullShareAccountStatus `json:"statusFilter"`
	CursorMemberNumber pgtype.Int8            `json:"cursorMemberNumber"`
	CursorID           pgtype.UUID            `json:"cursorId"`
	FetchLimit         int32                  `json:"fetchLimit"`
}

type ListShareAccountsRow struct {
	ID           pgtype.UUID        `json:"id"`
	MemberID     pgtype.UUID        `json:"memberId"`
	BranchID     int64              `json:"branchId"`
	Status       ShareAccountStatus `json:"status"`
	OpenedAt     pgtype.Timestamptz `json:"openedAt"`
	CreatedAt    pgtype.Timestamptz `json:"createdAt"`
	UpdatedAt    pgtype.Timestamptz `json:"updatedAt"`
	MemberNumber int64              `json:"memberNumber"`
	MemberName   pgtype.Text        `json:"memberName"`
}

func (q *Queries) ListShareAccounts(ctx context.Context, arg ListShareAccountsParams) ([]ListShareAccountsRow, error) {
	rows, err := q.db.Query(ctx, listShareAccounts,
		arg.BranchID,
		arg.StatusFilter,
		arg.CursorMemberNumber,
		arg.CursorID,
		arg.FetchLimit,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListShareAccountsRow
	for rows.Next() {
		var i ListShareAccountsRow
		if err := rows.Scan(
			&i.ID,
			&i.MemberID,
			&i.BranchID,
			&i.Status,
			&i.OpenedAt,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.MemberNumber,
			&i.MemberName,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const lockAccountByMemberID = `-- name: LockAccountByMemberID :one
SELECT id, member_id, branch_id, status, opened_at, is_deleted, created_at, updated_at FROM share_accounts
WHERE member_id = $1 AND is_deleted = FALSE
FOR UPDATE
`

func (q *Queries) LockAccountByMemberID(ctx context.Context, memberID pgtype.UUID) (ShareAccount, error) {
	row := q.db.QueryRow(ctx, lockAccountByMemberID, memberID)
	var i ShareAccount
	err := row.Scan(
		&i.ID,
		&i.MemberID,
		&i.BranchID,
		&i.Status,
		&i.OpenedAt,
		&i.IsDeleted,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const lockAndReadAccount = `-- name: LockAndReadAccount :one
SELECT id, member_id, branch_id, status, opened_at, is_deleted, created_at, updated_at FROM share_accounts
WHERE id = $1 AND is_deleted = FALSE
FOR UPDATE
`

func (q *Queries) LockAndReadAccount(ctx context.Context, id pgtype.UUID) (ShareAccount, error) {
	row := q.db.QueryRow(ctx, lockAndReadAccount, id)
	var i ShareAccount
	err := row.Scan(
		&i.ID,
		&i.MemberID,
		&i.BranchID,
		&i.Status,
		&i.OpenedAt,
		&i.IsDeleted,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const updateAccountStatus = `-- name: UpdateAccountStatus :one
UPDATE share_accounts
    SET status = $2, updated_at = NOW()
WHERE id = $1 AND is_deleted = FALSE
RETURNING id, member_id, branch_id, status, opened_at, is_deleted, created_at, updated_at
`

type UpdateAccountStatusParams struct {
	ID     pgtype.UUID        `json:"id"`
	Status ShareAccountStatus `json:"status"`
}

func (q *Queries) UpdateAccountStatus(ctx context.Context, arg UpdateAccountStatusParams) (ShareAccount, error) {
	row := q.db.QueryRow(ctx, updateAccountStatus, arg.ID, arg.Status)
	var i ShareAccount
	err := row.Scan(
		&i.ID,
		&i.MemberID,
		&i.BranchID,
		&i.Status,
		&i.OpenedAt,
		&i.IsDeleted,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
