// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: accounts.sql

package sharesqlc

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const getAccountByID = `-- name: GetAccountByID :one
SELECT id, member_id, branch_id, status, opened_at, is_deleted, created_at, updated_at FROM share_accounts
WHERE id = $1 AND is_deleted = FALSE
`

func (q *Queries) GetAccountByID(ctx context.Context, id pgtype.UUID) (ShareAccount, error) {
	row := q.db.QueryRow(ctx, getAccountByID, id)
	var i ShareAccount
	err := row.Scan(
		&i.ID,
		&i.MemberID,
		&i.BranchID,
		&i.Status,
		&i.OpenedAt,
		&i.IsDeleted,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getAccountByMemberID = `-- name: GetAccountByMemberID :one
SELECT id, member_id, branch_id, status, opened_at, is_deleted, created_at, updated_at FROM share_accounts
WHERE member_id = $1 AND is_deleted = FALSE
`

func (q *Queries) GetAccountByMemberID(ctx context.Context, memberID pgtype.UUID) (ShareAccount, error) {
	row := q.db.QueryRow(ctx, getAccountByMemberID, memberID)
	var i ShareAccount
	err := row.Scan(
		&i.ID,
		&i.MemberID,
		&i.BranchID,
		&i.Status,
		&i.OpenedAt,
		&i.IsDeleted,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listAccounts = `-- name: ListAccounts :many
SELECT id, member_id, branch_id, status, opened_at, is_deleted, created_at, updated_at FROM share_accounts
WHERE is_deleted = FALSE
  AND (created_at < $1 OR (created_at = $1 AND id < $2))
ORDER BY created_at DESC, id DESC
LIMIT $3
`

type ListAccountsParams struct {
	CreatedAt interface{} `json:"createdAt"`
	ID        pgtype.UUID `json:"id"`
	Limit     int32       `json:"limit"`
}

func (q *Queries) ListAccounts(ctx context.Context, arg ListAccountsParams) ([]ShareAccount, error) {
	rows, err := q.db.Query(ctx, listAccounts, arg.CreatedAt, arg.ID, arg.Limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ShareAccount
	for rows.Next() {
		var i ShareAccount
		if err := rows.Scan(
			&i.ID,
			&i.MemberID,
			&i.BranchID,
			&i.Status,
			&i.OpenedAt,
			&i.IsDeleted,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const lockAndReadAccount = `-- name: LockAndReadAccount :one
SELECT id, member_id, branch_id, status, opened_at, is_deleted, created_at, updated_at FROM share_accounts
WHERE id = $1 AND is_deleted = FALSE
FOR UPDATE
`

func (q *Queries) LockAndReadAccount(ctx context.Context, id pgtype.UUID) (ShareAccount, error) {
	row := q.db.QueryRow(ctx, lockAndReadAccount, id)
	var i ShareAccount
	err := row.Scan(
		&i.ID,
		&i.MemberID,
		&i.BranchID,
		&i.Status,
		&i.OpenedAt,
		&i.IsDeleted,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const updateAccountStatus = `-- name: UpdateAccountStatus :one
UPDATE share_accounts
    SET status = $2, updated_at = NOW()
WHERE id = $1 AND is_deleted = FALSE
RETURNING id, member_id, branch_id, status, opened_at, is_deleted, created_at, updated_at
`

type UpdateAccountStatusParams struct {
	ID     pgtype.UUID        `json:"id"`
	Status ShareAccountStatus `json:"status"`
}

func (q *Queries) UpdateAccountStatus(ctx context.Context, arg UpdateAccountStatusParams) (ShareAccount, error) {
	row := q.db.QueryRow(ctx, updateAccountStatus, arg.ID, arg.Status)
	var i ShareAccount
	err := row.Scan(
		&i.ID,
		&i.MemberID,
		&i.BranchID,
		&i.Status,
		&i.OpenedAt,
		&i.IsDeleted,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
