// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: accounts.sql

package sharesqlc

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createShareAccount = `-- name: CreateShareAccount :one
INSERT INTO share_accounts (member_id, branch_id, status, opened_at)
VALUES ($1, $2, 'active', NOW())
RETURNING id, member_id, branch_id, status, opened_at, is_deleted, created_at, updated_at
`

type CreateShareAccountParams struct {
	MemberID pgtype.UUID `json:"memberId"`
	BranchID int64       `json:"branchId"`
}

func (q *Queries) CreateShareAccount(ctx context.Context, arg CreateShareAccountParams) (ShareAccount, error) {
	row := q.db.QueryRow(ctx, createShareAccount, arg.MemberID, arg.BranchID)
	var i ShareAccount
	err := row.Scan(
		&i.ID,
		&i.MemberID,
		&i.BranchID,
		&i.Status,
		&i.OpenedAt,
		&i.IsDeleted,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getAccountByID = `-- name: GetAccountByID :one
SELECT id, member_id, branch_id, status, opened_at, is_deleted, created_at, updated_at FROM share_accounts
WHERE id = $1 AND is_deleted = FALSE
`

func (q *Queries) GetAccountByID(ctx context.Context, id pgtype.UUID) (ShareAccount, error) {
	row := q.db.QueryRow(ctx, getAccountByID, id)
	var i ShareAccount
	err := row.Scan(
		&i.ID,
		&i.MemberID,
		&i.BranchID,
		&i.Status,
		&i.OpenedAt,
		&i.IsDeleted,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getAccountByMemberID = `-- name: GetAccountByMemberID :one
SELECT id, member_id, branch_id, status, opened_at, is_deleted, created_at, updated_at FROM share_accounts
WHERE member_id = $1 AND is_deleted = FALSE
`

func (q *Queries) GetAccountByMemberID(ctx context.Context, memberID pgtype.UUID) (ShareAccount, error) {
	row := q.db.QueryRow(ctx, getAccountByMemberID, memberID)
	var i ShareAccount
	err := row.Scan(
		&i.ID,
		&i.MemberID,
		&i.BranchID,
		&i.Status,
		&i.OpenedAt,
		&i.IsDeleted,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listAccounts = `-- name: ListAccounts :many
SELECT id, member_id, branch_id, status, opened_at, is_deleted, created_at, updated_at FROM share_accounts
WHERE is_deleted = FALSE
  AND branch_id = $1
  AND ($2::timestamptz IS NULL OR created_at < $2 OR (created_at = $2 AND id < $3))
ORDER BY created_at DESC, id DESC
LIMIT $4
`

type ListAccountsParams struct {
	BranchID int64              `json:"branchId"`
	Column2  pgtype.Timestamptz `json:"column2"`
	ID       pgtype.UUID        `json:"id"`
	Limit    int32              `json:"limit"`
}

func (q *Queries) ListAccounts(ctx context.Context, arg ListAccountsParams) ([]ShareAccount, error) {
	rows, err := q.db.Query(ctx, listAccounts,
		arg.BranchID,
		arg.Column2,
		arg.ID,
		arg.Limit,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ShareAccount
	for rows.Next() {
		var i ShareAccount
		if err := rows.Scan(
			&i.ID,
			&i.MemberID,
			&i.BranchID,
			&i.Status,
			&i.OpenedAt,
			&i.IsDeleted,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const lockAndReadAccount = `-- name: LockAndReadAccount :one
SELECT id, member_id, branch_id, status, opened_at, is_deleted, created_at, updated_at FROM share_accounts
WHERE id = $1 AND is_deleted = FALSE
FOR UPDATE
`

func (q *Queries) LockAndReadAccount(ctx context.Context, id pgtype.UUID) (ShareAccount, error) {
	row := q.db.QueryRow(ctx, lockAndReadAccount, id)
	var i ShareAccount
	err := row.Scan(
		&i.ID,
		&i.MemberID,
		&i.BranchID,
		&i.Status,
		&i.OpenedAt,
		&i.IsDeleted,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const updateAccountStatus = `-- name: UpdateAccountStatus :one
UPDATE share_accounts
    SET status = $2, updated_at = NOW()
WHERE id = $1 AND is_deleted = FALSE
RETURNING id, member_id, branch_id, status, opened_at, is_deleted, created_at, updated_at
`

type UpdateAccountStatusParams struct {
	ID     pgtype.UUID        `json:"id"`
	Status ShareAccountStatus `json:"status"`
}

func (q *Queries) UpdateAccountStatus(ctx context.Context, arg UpdateAccountStatusParams) (ShareAccount, error) {
	row := q.db.QueryRow(ctx, updateAccountStatus, arg.ID, arg.Status)
	var i ShareAccount
	err := row.Scan(
		&i.ID,
		&i.MemberID,
		&i.BranchID,
		&i.Status,
		&i.OpenedAt,
		&i.IsDeleted,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
