// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: adjustments.sql

package sharesqlc

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const getAdjustmentByTransactionID = `-- name: GetAdjustmentByTransactionID :one
SELECT id, share_transaction_id, approver_id, reason, audit_report_id, created_at FROM share_adjustments
WHERE share_transaction_id = $1
`

func (q *Queries) GetAdjustmentByTransactionID(ctx context.Context, shareTransactionID pgtype.UUID) (ShareAdjustment, error) {
	row := q.db.QueryRow(ctx, getAdjustmentByTransactionID, shareTransactionID)
	var i ShareAdjustment
	err := row.Scan(
		&i.ID,
		&i.ShareTransactionID,
		&i.ApproverID,
		&i.Reason,
		&i.AuditReportID,
		&i.CreatedAt,
	)
	return i, err
}

const insertAdjustment = `-- name: InsertAdjustment :one
INSERT INTO share_adjustments (share_transaction_id, approver_id, reason, audit_report_id)
VALUES ($1, $2, $3, $4)
RETURNING id, share_transaction_id, approver_id, reason, audit_report_id, created_at
`

type InsertAdjustmentParams struct {
	ShareTransactionID pgtype.UUID `json:"shareTransactionId"`
	ApproverID         pgtype.UUID `json:"approverId"`
	Reason             string      `json:"reason"`
	AuditReportID      pgtype.UUID `json:"auditReportId"`
}

func (q *Queries) InsertAdjustment(ctx context.Context, arg InsertAdjustmentParams) (ShareAdjustment, error) {
	row := q.db.QueryRow(ctx, insertAdjustment,
		arg.ShareTransactionID,
		arg.ApproverID,
		arg.Reason,
		arg.AuditReportID,
	)
	var i ShareAdjustment
	err := row.Scan(
		&i.ID,
		&i.ShareTransactionID,
		&i.ApproverID,
		&i.Reason,
		&i.AuditReportID,
		&i.CreatedAt,
	)
	return i, err
}
