// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package sharesqlc

import (
	"database/sql/driver"
	"fmt"

	"github.com/jackc/pgx/v5/pgtype"
)

type ShareAccountStatus string

const (
	ShareAccountStatusActive  ShareAccountStatus = "active"
	ShareAccountStatusDormant ShareAccountStatus = "dormant"
	ShareAccountStatusClosed  ShareAccountStatus = "closed"
)

func (e *ShareAccountStatus) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = ShareAccountStatus(s)
	case string:
		*e = ShareAccountStatus(s)
	default:
		return fmt.Errorf("unsupported scan type for ShareAccountStatus: %T", src)
	}
	return nil
}

type NullShareAccountStatus struct {
	ShareAccountStatus ShareAccountStatus `json:"shareAccountStatus"`
	Valid              bool               `json:"valid"` // Valid is true if ShareAccountStatus is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullShareAccountStatus) Scan(value interface{}) error {
	if value == nil {
		ns.ShareAccountStatus, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.ShareAccountStatus.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullShareAccountStatus) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.ShareAccountStatus), nil
}

type ShareTransactionType string

const (
	ShareTransactionTypePurchase   ShareTransactionType = "purchase"
	ShareTransactionTypeWithdrawal ShareTransactionType = "withdrawal"
	ShareTransactionTypeDividend   ShareTransactionType = "dividend"
	ShareTransactionTypeReversal   ShareTransactionType = "reversal"
	ShareTransactionTypeAdjustment ShareTransactionType = "adjustment"
)

func (e *ShareTransactionType) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = ShareTransactionType(s)
	case string:
		*e = ShareTransactionType(s)
	default:
		return fmt.Errorf("unsupported scan type for ShareTransactionType: %T", src)
	}
	return nil
}

type NullShareTransactionType struct {
	ShareTransactionType ShareTransactionType `json:"shareTransactionType"`
	Valid                bool                 `json:"valid"` // Valid is true if ShareTransactionType is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullShareTransactionType) Scan(value interface{}) error {
	if value == nil {
		ns.ShareTransactionType, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.ShareTransactionType.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullShareTransactionType) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.ShareTransactionType), nil
}

type ShareAccount struct {
	ID        pgtype.UUID        `json:"id"`
	MemberID  pgtype.UUID        `json:"memberId"`
	BranchID  int64              `json:"branchId"`
	Status    ShareAccountStatus `json:"status"`
	OpenedAt  interface{}        `json:"openedAt"`
	IsDeleted bool               `json:"isDeleted"`
	CreatedAt interface{}        `json:"createdAt"`
	UpdatedAt interface{}        `json:"updatedAt"`
}

type ShareAdjustment struct {
	ID                 pgtype.UUID `json:"id"`
	ShareTransactionID pgtype.UUID `json:"shareTransactionId"`
	ApproverID         pgtype.UUID `json:"approverId"`
	Reason             string      `json:"reason"`
	AuditReportID      pgtype.UUID `json:"auditReportId"`
	CreatedAt          interface{} `json:"createdAt"`
}

type ShareTransaction struct {
	ID             pgtype.UUID          `json:"id"`
	ShareAccountID pgtype.UUID          `json:"shareAccountId"`
	Type           ShareTransactionType `json:"type"`
	Amount         pgtype.Numeric       `json:"amount"`
	BalanceAfter   pgtype.Numeric       `json:"balanceAfter"`
	ReferenceID    pgtype.UUID          `json:"referenceId"`
	ReversalOf     pgtype.UUID          `json:"reversalOf"`
	Reason         pgtype.Text          `json:"reason"`
	OriginatorID   pgtype.UUID          `json:"originatorId"`
	CreatedAt      interface{}          `json:"createdAt"`
}
