// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: pledges.sql

package sharesqlc

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const activateSharePledge = `-- name: ActivateSharePledge :one
UPDATE share_pledges
SET status = 'active', approved_by = $2, approved_at = NOW(), updated_at = NOW()
WHERE id = $1 AND status = 'pending'
RETURNING id, share_account_id, loan_id, pledged_amount, type, status, approved_by, approved_at, released_at, created_at, updated_at
`

type ActivateSharePledgeParams struct {
	ID         pgtype.UUID `json:"id"`
	ApprovedBy pgtype.UUID `json:"approvedBy"`
}

func (q *Queries) ActivateSharePledge(ctx context.Context, arg ActivateSharePledgeParams) (SharePledge, error) {
	row := q.db.QueryRow(ctx, activateSharePledge, arg.ID, arg.ApprovedBy)
	var i SharePledge
	err := row.Scan(
		&i.ID,
		&i.ShareAccountID,
		&i.LoanID,
		&i.PledgedAmount,
		&i.Type,
		&i.Status,
		&i.ApprovedBy,
		&i.ApprovedAt,
		&i.ReleasedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const createSharePledge = `-- name: CreateSharePledge :one
INSERT INTO share_pledges (share_account_id, loan_id, pledged_amount, type)
VALUES ($1, $2, $3, $4)
ON CONFLICT (share_account_id, loan_id) DO NOTHING
RETURNING id, share_account_id, loan_id, pledged_amount, type, status, approved_by, approved_at, released_at, created_at, updated_at
`

type CreateSharePledgeParams struct {
	ShareAccountID pgtype.UUID     `json:"shareAccountId"`
	LoanID         pgtype.UUID     `json:"loanId"`
	PledgedAmount  pgtype.Numeric  `json:"pledgedAmount"`
	Type           SharePledgeType `json:"type"`
}

func (q *Queries) CreateSharePledge(ctx context.Context, arg CreateSharePledgeParams) (SharePledge, error) {
	row := q.db.QueryRow(ctx, createSharePledge,
		arg.ShareAccountID,
		arg.LoanID,
		arg.PledgedAmount,
		arg.Type,
	)
	var i SharePledge
	err := row.Scan(
		&i.ID,
		&i.ShareAccountID,
		&i.LoanID,
		&i.PledgedAmount,
		&i.Type,
		&i.Status,
		&i.ApprovedBy,
		&i.ApprovedAt,
		&i.ReleasedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getActiveApplicantPledgeAmount = `-- name: GetActiveApplicantPledgeAmount :one
SELECT COALESCE(SUM(pledged_amount), 0)::NUMERIC AS pledged_amount
FROM share_pledges
WHERE loan_id = $1 AND type = 'applicant_security' AND status = 'active'
`

func (q *Queries) GetActiveApplicantPledgeAmount(ctx context.Context, loanID pgtype.UUID) (pgtype.Numeric, error) {
	row := q.db.QueryRow(ctx, getActiveApplicantPledgeAmount, loanID)
	var pledged_amount pgtype.Numeric
	err := row.Scan(&pledged_amount)
	return pledged_amount, err
}

const getActivePledgedAmount = `-- name: GetActivePledgedAmount :one
SELECT COALESCE(SUM(pledged_amount), 0)::NUMERIC AS pledged_amount
FROM share_pledges
WHERE share_account_id = $1 AND status = 'active'
`

func (q *Queries) GetActivePledgedAmount(ctx context.Context, shareAccountID pgtype.UUID) (pgtype.Numeric, error) {
	row := q.db.QueryRow(ctx, getActivePledgedAmount, shareAccountID)
	var pledged_amount pgtype.Numeric
	err := row.Scan(&pledged_amount)
	return pledged_amount, err
}

const getApplicantSharePledge = `-- name: GetApplicantSharePledge :one
SELECT id, share_account_id, loan_id, pledged_amount, type, status, approved_by, approved_at, released_at, created_at, updated_at
FROM share_pledges
WHERE loan_id = $1 AND type = 'applicant_security'
`

func (q *Queries) GetApplicantSharePledge(ctx context.Context, loanID pgtype.UUID) (SharePledge, error) {
	row := q.db.QueryRow(ctx, getApplicantSharePledge, loanID)
	var i SharePledge
	err := row.Scan(
		&i.ID,
		&i.ShareAccountID,
		&i.LoanID,
		&i.PledgedAmount,
		&i.Type,
		&i.Status,
		&i.ApprovedBy,
		&i.ApprovedAt,
		&i.ReleasedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const releaseApplicantSharePledge = `-- name: ReleaseApplicantSharePledge :exec
UPDATE share_pledges
SET status = CASE WHEN status = 'pending' THEN 'cancelled'::share_pledge_status ELSE 'released'::share_pledge_status END,
    released_at = CASE WHEN status = 'active' THEN NOW() ELSE released_at END,
    updated_at = NOW()
WHERE loan_id = $1
  AND type = 'applicant_security'
  AND status IN ('pending', 'active')
`

func (q *Queries) ReleaseApplicantSharePledge(ctx context.Context, loanID pgtype.UUID) error {
	_, err := q.db.Exec(ctx, releaseApplicantSharePledge, loanID)
	return err
}
