// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: transactions.sql

package sharesqlc

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const getLatestBalance = `-- name: GetLatestBalance :one
SELECT balance_after FROM share_transactions
WHERE share_account_id = $1
ORDER BY created_at DESC
LIMIT 1
`

func (q *Queries) GetLatestBalance(ctx context.Context, shareAccountID pgtype.UUID) (pgtype.Numeric, error) {
	row := q.db.QueryRow(ctx, getLatestBalance, shareAccountID)
	var balance_after pgtype.Numeric
	err := row.Scan(&balance_after)
	return balance_after, err
}

const getReversalTransactions = `-- name: GetReversalTransactions :many
SELECT id, share_account_id, type, amount, balance_after, reference_id, reversal_of, reason, originator_id, created_at FROM share_transactions
WHERE reversal_of = $1
`

func (q *Queries) GetReversalTransactions(ctx context.Context, reversalOf pgtype.UUID) ([]ShareTransaction, error) {
	rows, err := q.db.Query(ctx, getReversalTransactions, reversalOf)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ShareTransaction
	for rows.Next() {
		var i ShareTransaction
		if err := rows.Scan(
			&i.ID,
			&i.ShareAccountID,
			&i.Type,
			&i.Amount,
			&i.BalanceAfter,
			&i.ReferenceID,
			&i.ReversalOf,
			&i.Reason,
			&i.OriginatorID,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getTransactionByID = `-- name: GetTransactionByID :one
SELECT id, share_account_id, type, amount, balance_after, reference_id, reversal_of, reason, originator_id, created_at FROM share_transactions
WHERE id = $1
`

func (q *Queries) GetTransactionByID(ctx context.Context, id pgtype.UUID) (ShareTransaction, error) {
	row := q.db.QueryRow(ctx, getTransactionByID, id)
	var i ShareTransaction
	err := row.Scan(
		&i.ID,
		&i.ShareAccountID,
		&i.Type,
		&i.Amount,
		&i.BalanceAfter,
		&i.ReferenceID,
		&i.ReversalOf,
		&i.Reason,
		&i.OriginatorID,
		&i.CreatedAt,
	)
	return i, err
}

const getTransactionByReference = `-- name: GetTransactionByReference :one
SELECT id, share_account_id, type, amount, balance_after, reference_id, reversal_of, reason, originator_id, created_at FROM share_transactions
WHERE share_account_id = $1 AND reference_id = $2 AND type = $3
`

type GetTransactionByReferenceParams struct {
	ShareAccountID pgtype.UUID          `json:"shareAccountId"`
	ReferenceID    pgtype.UUID          `json:"referenceId"`
	Type           ShareTransactionType `json:"type"`
}

func (q *Queries) GetTransactionByReference(ctx context.Context, arg GetTransactionByReferenceParams) (ShareTransaction, error) {
	row := q.db.QueryRow(ctx, getTransactionByReference, arg.ShareAccountID, arg.ReferenceID, arg.Type)
	var i ShareTransaction
	err := row.Scan(
		&i.ID,
		&i.ShareAccountID,
		&i.Type,
		&i.Amount,
		&i.BalanceAfter,
		&i.ReferenceID,
		&i.ReversalOf,
		&i.Reason,
		&i.OriginatorID,
		&i.CreatedAt,
	)
	return i, err
}

const insertShareTransaction = `-- name: InsertShareTransaction :one
INSERT INTO share_transactions (share_account_id, type, amount, balance_after, reference_id, reversal_of, reason, originator_id)
VALUES ($1, $2, $3, $4, $5, $6, $7, $8)
ON CONFLICT (share_account_id, reference_id, type) DO NOTHING
RETURNING id, share_account_id, type, amount, balance_after, reference_id, reversal_of, reason, originator_id, created_at
`

type InsertShareTransactionParams struct {
	ShareAccountID pgtype.UUID          `json:"shareAccountId"`
	Type           ShareTransactionType `json:"type"`
	Amount         pgtype.Numeric       `json:"amount"`
	BalanceAfter   pgtype.Numeric       `json:"balanceAfter"`
	ReferenceID    pgtype.UUID          `json:"referenceId"`
	ReversalOf     pgtype.UUID          `json:"reversalOf"`
	Reason         pgtype.Text          `json:"reason"`
	OriginatorID   pgtype.UUID          `json:"originatorId"`
}

func (q *Queries) InsertShareTransaction(ctx context.Context, arg InsertShareTransactionParams) (ShareTransaction, error) {
	row := q.db.QueryRow(ctx, insertShareTransaction,
		arg.ShareAccountID,
		arg.Type,
		arg.Amount,
		arg.BalanceAfter,
		arg.ReferenceID,
		arg.ReversalOf,
		arg.Reason,
		arg.OriginatorID,
	)
	var i ShareTransaction
	err := row.Scan(
		&i.ID,
		&i.ShareAccountID,
		&i.Type,
		&i.Amount,
		&i.BalanceAfter,
		&i.ReferenceID,
		&i.ReversalOf,
		&i.Reason,
		&i.OriginatorID,
		&i.CreatedAt,
	)
	return i, err
}

const listTransactions = `-- name: ListTransactions :many
SELECT id, share_account_id, type, amount, balance_after, reference_id, reversal_of, reason, originator_id, created_at FROM share_transactions
WHERE share_account_id = $1
  AND ($2::timestamptz IS NULL OR created_at < $2 OR (created_at = $2 AND id < $3))
ORDER BY created_at DESC, id DESC
LIMIT $4
`

type ListTransactionsParams struct {
	ShareAccountID pgtype.UUID        `json:"shareAccountId"`
	Column2        pgtype.Timestamptz `json:"column2"`
	ID             pgtype.UUID        `json:"id"`
	Limit          int32              `json:"limit"`
}

func (q *Queries) ListTransactions(ctx context.Context, arg ListTransactionsParams) ([]ShareTransaction, error) {
	rows, err := q.db.Query(ctx, listTransactions,
		arg.ShareAccountID,
		arg.Column2,
		arg.ID,
		arg.Limit,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ShareTransaction
	for rows.Next() {
		var i ShareTransaction
		if err := rows.Scan(
			&i.ID,
			&i.ShareAccountID,
			&i.Type,
			&i.Amount,
			&i.BalanceAfter,
			&i.ReferenceID,
			&i.ReversalOf,
			&i.Reason,
			&i.OriginatorID,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const lockAndGetLatestBalance = `-- name: LockAndGetLatestBalance :one
SELECT balance_after FROM share_transactions
WHERE share_account_id = $1
ORDER BY created_at DESC
LIMIT 1
FOR UPDATE
`

func (q *Queries) LockAndGetLatestBalance(ctx context.Context, shareAccountID pgtype.UUID) (pgtype.Numeric, error) {
	row := q.db.QueryRow(ctx, lockAndGetLatestBalance, shareAccountID)
	var balance_after pgtype.Numeric
	err := row.Scan(&balance_after)
	return balance_after, err
}
