// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package sqlc

import (
	"github.com/jackc/pgx/v5/pgtype"
)

type MemberStatusHistory struct {
	ID         pgtype.UUID        `json:"id"`
	MemberID   pgtype.UUID        `json:"memberId"`
	FromStatus pgtype.Text        `json:"fromStatus"`
	ToStatus   string             `json:"toStatus"`
	Reason     pgtype.Text        `json:"reason"`
	CreatedAt  pgtype.Timestamptz `json:"createdAt"`
}
