// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: queries.sql

package sqlc

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createMember = `-- name: CreateMember :one
INSERT INTO members (branch_id, member_number, national_id, status)
VALUES ($1, $2, $3, $4)
ON CONFLICT (branch_id, national_id) DO NOTHING
RETURNING id
`

type CreateMemberParams struct {
	BranchID     int64  `json:"branchId"`
	MemberNumber int64  `json:"memberNumber"`
	NationalID   string `json:"nationalId"`
	Status       string `json:"status"`
}

func (q *Queries) CreateMember(ctx context.Context, arg CreateMemberParams) (pgtype.UUID, error) {
	row := q.db.QueryRow(ctx, createMember,
		arg.BranchID,
		arg.MemberNumber,
		arg.NationalID,
		arg.Status,
	)
	var id pgtype.UUID
	err := row.Scan(&id)
	return id, err
}

const createMemberProfile = `-- name: CreateMemberProfile :one
INSERT INTO member_profiles (member_id, full_name, phone, email, address, date_of_birth, occupation, employer,
                            monthly_income, id_document_type, id_document_number,
                            next_of_kin_name, next_of_kin_phone, next_of_kin_relationship)
VALUES ($1, $2, $3, $4, $5, $6, $7, $8, $9, $10, $11, $12, $13, $14)
RETURNING member_id
`

type CreateMemberProfileParams struct {
	MemberID              pgtype.UUID    `json:"memberId"`
	FullName              string         `json:"fullName"`
	Phone                 string         `json:"phone"`
	Email                 string         `json:"email"`
	Address               pgtype.Text    `json:"address"`
	DateOfBirth           pgtype.Date    `json:"dateOfBirth"`
	Occupation            pgtype.Text    `json:"occupation"`
	Employer              pgtype.Text    `json:"employer"`
	MonthlyIncome         pgtype.Numeric `json:"monthlyIncome"`
	IDDocumentType        pgtype.Text    `json:"idDocumentType"`
	IDDocumentNumber      pgtype.Text    `json:"idDocumentNumber"`
	NextOfKinName         pgtype.Text    `json:"nextOfKinName"`
	NextOfKinPhone        pgtype.Text    `json:"nextOfKinPhone"`
	NextOfKinRelationship pgtype.Text    `json:"nextOfKinRelationship"`
}

func (q *Queries) CreateMemberProfile(ctx context.Context, arg CreateMemberProfileParams) (pgtype.UUID, error) {
	row := q.db.QueryRow(ctx, createMemberProfile,
		arg.MemberID,
		arg.FullName,
		arg.Phone,
		arg.Email,
		arg.Address,
		arg.DateOfBirth,
		arg.Occupation,
		arg.Employer,
		arg.MonthlyIncome,
		arg.IDDocumentType,
		arg.IDDocumentNumber,
		arg.NextOfKinName,
		arg.NextOfKinPhone,
		arg.NextOfKinRelationship,
	)
	var member_id pgtype.UUID
	err := row.Scan(&member_id)
	return member_id, err
}

const deactivateMember = `-- name: DeactivateMember :one
UPDATE members
SET is_deleted = TRUE, status = 'closed', updated_at = CURRENT_TIMESTAMP
WHERE id = $1 AND is_deleted = FALSE
RETURNING id, branch_id, status
`

type DeactivateMemberRow struct {
	ID       pgtype.UUID `json:"id"`
	BranchID int64       `json:"branchId"`
	Status   string      `json:"status"`
}

func (q *Queries) DeactivateMember(ctx context.Context, id pgtype.UUID) (DeactivateMemberRow, error) {
	row := q.db.QueryRow(ctx, deactivateMember, id)
	var i DeactivateMemberRow
	err := row.Scan(&i.ID, &i.BranchID, &i.Status)
	return i, err
}

const getMemberByBranchAndNumber = `-- name: GetMemberByBranchAndNumber :one
SELECT m.id, m.branch_id, m.member_number, m.national_id, m.status, m.is_deleted, m.created_at, m.updated_at,
       p.full_name, p.phone, p.email, p.address, p.date_of_birth, p.occupation, p.employer,
       p.monthly_income, p.id_document_type, p.id_document_number,
       p.next_of_kin_name, p.next_of_kin_phone, p.next_of_kin_relationship
FROM members m
LEFT JOIN member_profiles p ON p.member_id = m.id
WHERE m.branch_id = $1 AND m.member_number = $2 AND m.is_deleted = FALSE
`

type GetMemberByBranchAndNumberParams struct {
	BranchID     int64 `json:"branchId"`
	MemberNumber int64 `json:"memberNumber"`
}

type GetMemberByBranchAndNumberRow struct {
	ID                    pgtype.UUID        `json:"id"`
	BranchID              int64              `json:"branchId"`
	MemberNumber          int64              `json:"memberNumber"`
	NationalID            string             `json:"nationalId"`
	Status                string             `json:"status"`
	IsDeleted             bool               `json:"isDeleted"`
	CreatedAt             pgtype.Timestamptz `json:"createdAt"`
	UpdatedAt             pgtype.Timestamptz `json:"updatedAt"`
	FullName              pgtype.Text        `json:"fullName"`
	Phone                 pgtype.Text        `json:"phone"`
	Email                 pgtype.Text        `json:"email"`
	Address               pgtype.Text        `json:"address"`
	DateOfBirth           pgtype.Date        `json:"dateOfBirth"`
	Occupation            pgtype.Text        `json:"occupation"`
	Employer              pgtype.Text        `json:"employer"`
	MonthlyIncome         pgtype.Numeric     `json:"monthlyIncome"`
	IDDocumentType        pgtype.Text        `json:"idDocumentType"`
	IDDocumentNumber      pgtype.Text        `json:"idDocumentNumber"`
	NextOfKinName         pgtype.Text        `json:"nextOfKinName"`
	NextOfKinPhone        pgtype.Text        `json:"nextOfKinPhone"`
	NextOfKinRelationship pgtype.Text        `json:"nextOfKinRelationship"`
}

func (q *Queries) GetMemberByBranchAndNumber(ctx context.Context, arg GetMemberByBranchAndNumberParams) (GetMemberByBranchAndNumberRow, error) {
	row := q.db.QueryRow(ctx, getMemberByBranchAndNumber, arg.BranchID, arg.MemberNumber)
	var i GetMemberByBranchAndNumberRow
	err := row.Scan(
		&i.ID,
		&i.BranchID,
		&i.MemberNumber,
		&i.NationalID,
		&i.Status,
		&i.IsDeleted,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.FullName,
		&i.Phone,
		&i.Email,
		&i.Address,
		&i.DateOfBirth,
		&i.Occupation,
		&i.Employer,
		&i.MonthlyIncome,
		&i.IDDocumentType,
		&i.IDDocumentNumber,
		&i.NextOfKinName,
		&i.NextOfKinPhone,
		&i.NextOfKinRelationship,
	)
	return i, err
}

const getMemberByID = `-- name: GetMemberByID :one
SELECT m.id, m.branch_id, m.member_number, m.national_id, m.status, m.is_deleted, m.created_at, m.updated_at,
       p.full_name, p.phone, p.email, p.address, p.date_of_birth, p.occupation, p.employer,
       p.monthly_income, p.id_document_type, p.id_document_number,
       p.next_of_kin_name, p.next_of_kin_phone, p.next_of_kin_relationship
FROM members m
LEFT JOIN member_profiles p ON p.member_id = m.id
WHERE m.id = $1 AND m.is_deleted = FALSE
`

type GetMemberByIDRow struct {
	ID                    pgtype.UUID        `json:"id"`
	BranchID              int64              `json:"branchId"`
	MemberNumber          int64              `json:"memberNumber"`
	NationalID            string             `json:"nationalId"`
	Status                string             `json:"status"`
	IsDeleted             bool               `json:"isDeleted"`
	CreatedAt             pgtype.Timestamptz `json:"createdAt"`
	UpdatedAt             pgtype.Timestamptz `json:"updatedAt"`
	FullName              pgtype.Text        `json:"fullName"`
	Phone                 pgtype.Text        `json:"phone"`
	Email                 pgtype.Text        `json:"email"`
	Address               pgtype.Text        `json:"address"`
	DateOfBirth           pgtype.Date        `json:"dateOfBirth"`
	Occupation            pgtype.Text        `json:"occupation"`
	Employer              pgtype.Text        `json:"employer"`
	MonthlyIncome         pgtype.Numeric     `json:"monthlyIncome"`
	IDDocumentType        pgtype.Text        `json:"idDocumentType"`
	IDDocumentNumber      pgtype.Text        `json:"idDocumentNumber"`
	NextOfKinName         pgtype.Text        `json:"nextOfKinName"`
	NextOfKinPhone        pgtype.Text        `json:"nextOfKinPhone"`
	NextOfKinRelationship pgtype.Text        `json:"nextOfKinRelationship"`
}

func (q *Queries) GetMemberByID(ctx context.Context, id pgtype.UUID) (GetMemberByIDRow, error) {
	row := q.db.QueryRow(ctx, getMemberByID, id)
	var i GetMemberByIDRow
	err := row.Scan(
		&i.ID,
		&i.BranchID,
		&i.MemberNumber,
		&i.NationalID,
		&i.Status,
		&i.IsDeleted,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.FullName,
		&i.Phone,
		&i.Email,
		&i.Address,
		&i.DateOfBirth,
		&i.Occupation,
		&i.Employer,
		&i.MonthlyIncome,
		&i.IDDocumentType,
		&i.IDDocumentNumber,
		&i.NextOfKinName,
		&i.NextOfKinPhone,
		&i.NextOfKinRelationship,
	)
	return i, err
}

const getMemberStatusHistory = `-- name: GetMemberStatusHistory :many
SELECT id, member_id, from_status, to_status, reason, created_at
FROM member_status_history
WHERE member_id = $1
ORDER BY created_at DESC
`

func (q *Queries) GetMemberStatusHistory(ctx context.Context, memberID pgtype.UUID) ([]MemberStatusHistory, error) {
	rows, err := q.db.Query(ctx, getMemberStatusHistory, memberID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []MemberStatusHistory
	for rows.Next() {
		var i MemberStatusHistory
		if err := rows.Scan(
			&i.ID,
			&i.MemberID,
			&i.FromStatus,
			&i.ToStatus,
			&i.Reason,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getNextMemberNumber = `-- name: GetNextMemberNumber :one
SELECT next_member_number
FROM member_branch_counters
WHERE branch_id = $1
FOR UPDATE
`

func (q *Queries) GetNextMemberNumber(ctx context.Context, branchID int64) (int64, error) {
	row := q.db.QueryRow(ctx, getNextMemberNumber, branchID)
	var next_member_number int64
	err := row.Scan(&next_member_number)
	return next_member_number, err
}

const incrementMemberNumber = `-- name: IncrementMemberNumber :one
UPDATE member_branch_counters
SET next_member_number = next_member_number + 1, updated_at = CURRENT_TIMESTAMP
WHERE branch_id = $1
RETURNING next_member_number - 1
`

func (q *Queries) IncrementMemberNumber(ctx context.Context, branchID int64) (int32, error) {
	row := q.db.QueryRow(ctx, incrementMemberNumber, branchID)
	var column_1 int32
	err := row.Scan(&column_1)
	return column_1, err
}

const listMembersByBranchCursor = `-- name: ListMembersByBranchCursor :many
SELECT m.id, m.branch_id, m.member_number, m.national_id, m.status, m.is_deleted, m.created_at, m.updated_at,
       p.full_name, p.phone, p.email, p.address, p.date_of_birth, p.occupation, p.employer,
       p.monthly_income, p.id_document_type, p.id_document_number,
       p.next_of_kin_name, p.next_of_kin_phone, p.next_of_kin_relationship
FROM members m
LEFT JOIN member_profiles p ON p.member_id = m.id
WHERE m.branch_id = $1
  AND NOT m.is_deleted
  AND ($2::uuid IS NULL OR m.id < COALESCE($2::uuid, 'FFFFFFFF-FFFF-FFFF-FFFF-FFFFFFFFFFFF'::uuid))
ORDER BY m.id DESC
LIMIT $3
`

type ListMembersByBranchCursorParams struct {
	BranchID int64       `json:"branchId"`
	Column2  pgtype.UUID `json:"column2"`
	Limit    int32       `json:"limit"`
}

type ListMembersByBranchCursorRow struct {
	ID                    pgtype.UUID        `json:"id"`
	BranchID              int64              `json:"branchId"`
	MemberNumber          int64              `json:"memberNumber"`
	NationalID            string             `json:"nationalId"`
	Status                string             `json:"status"`
	IsDeleted             bool               `json:"isDeleted"`
	CreatedAt             pgtype.Timestamptz `json:"createdAt"`
	UpdatedAt             pgtype.Timestamptz `json:"updatedAt"`
	FullName              pgtype.Text        `json:"fullName"`
	Phone                 pgtype.Text        `json:"phone"`
	Email                 pgtype.Text        `json:"email"`
	Address               pgtype.Text        `json:"address"`
	DateOfBirth           pgtype.Date        `json:"dateOfBirth"`
	Occupation            pgtype.Text        `json:"occupation"`
	Employer              pgtype.Text        `json:"employer"`
	MonthlyIncome         pgtype.Numeric     `json:"monthlyIncome"`
	IDDocumentType        pgtype.Text        `json:"idDocumentType"`
	IDDocumentNumber      pgtype.Text        `json:"idDocumentNumber"`
	NextOfKinName         pgtype.Text        `json:"nextOfKinName"`
	NextOfKinPhone        pgtype.Text        `json:"nextOfKinPhone"`
	NextOfKinRelationship pgtype.Text        `json:"nextOfKinRelationship"`
}

func (q *Queries) ListMembersByBranchCursor(ctx context.Context, arg ListMembersByBranchCursorParams) ([]ListMembersByBranchCursorRow, error) {
	rows, err := q.db.Query(ctx, listMembersByBranchCursor, arg.BranchID, arg.Column2, arg.Limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListMembersByBranchCursorRow
	for rows.Next() {
		var i ListMembersByBranchCursorRow
		if err := rows.Scan(
			&i.ID,
			&i.BranchID,
			&i.MemberNumber,
			&i.NationalID,
			&i.Status,
			&i.IsDeleted,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.FullName,
			&i.Phone,
			&i.Email,
			&i.Address,
			&i.DateOfBirth,
			&i.Occupation,
			&i.Employer,
			&i.MonthlyIncome,
			&i.IDDocumentType,
			&i.IDDocumentNumber,
			&i.NextOfKinName,
			&i.NextOfKinPhone,
			&i.NextOfKinRelationship,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const memberExistsByBranchAndNationalID = `-- name: MemberExistsByBranchAndNationalID :one
SELECT id, status
FROM members
WHERE branch_id = $1 AND national_id = $2 AND is_deleted = FALSE
`

type MemberExistsByBranchAndNationalIDParams struct {
	BranchID   int64  `json:"branchId"`
	NationalID string `json:"nationalId"`
}

type MemberExistsByBranchAndNationalIDRow struct {
	ID     pgtype.UUID `json:"id"`
	Status string      `json:"status"`
}

func (q *Queries) MemberExistsByBranchAndNationalID(ctx context.Context, arg MemberExistsByBranchAndNationalIDParams) (MemberExistsByBranchAndNationalIDRow, error) {
	row := q.db.QueryRow(ctx, memberExistsByBranchAndNationalID, arg.BranchID, arg.NationalID)
	var i MemberExistsByBranchAndNationalIDRow
	err := row.Scan(&i.ID, &i.Status)
	return i, err
}

const recordMemberStatusTransition = `-- name: RecordMemberStatusTransition :exec
INSERT INTO member_status_history (member_id, from_status, to_status, reason)
VALUES ($1, $2, $3, $4)
`

type RecordMemberStatusTransitionParams struct {
	MemberID   pgtype.UUID `json:"memberId"`
	FromStatus pgtype.Text `json:"fromStatus"`
	ToStatus   string      `json:"toStatus"`
	Reason     pgtype.Text `json:"reason"`
}

func (q *Queries) RecordMemberStatusTransition(ctx context.Context, arg RecordMemberStatusTransitionParams) error {
	_, err := q.db.Exec(ctx, recordMemberStatusTransition,
		arg.MemberID,
		arg.FromStatus,
		arg.ToStatus,
		arg.Reason,
	)
	return err
}

const recoverMemberNumberCounter = `-- name: RecoverMemberNumberCounter :exec
UPDATE member_branch_counters c
SET next_member_number = GREATEST(next_member_number, (SELECT COALESCE(MAX(member_number), 0) + 1 FROM members m WHERE m.branch_id = $1)),
    updated_at = CURRENT_TIMESTAMP
WHERE c.branch_id = $1
`

func (q *Queries) RecoverMemberNumberCounter(ctx context.Context, branchID int64) error {
	_, err := q.db.Exec(ctx, recoverMemberNumberCounter, branchID)
	return err
}

const updateMemberProfile = `-- name: UpdateMemberProfile :exec
UPDATE member_profiles
SET full_name = COALESCE($2, full_name),
    phone = COALESCE($3, phone),
    email = COALESCE($4, email),
    address = COALESCE($5, address),
    date_of_birth = COALESCE($6, date_of_birth),
    occupation = COALESCE($7, occupation),
    employer = COALESCE($8, employer),
    monthly_income = COALESCE($9, monthly_income),
    id_document_type = COALESCE($10, id_document_type),
    id_document_number = COALESCE($11, id_document_number),
    next_of_kin_name = COALESCE($12, next_of_kin_name),
    next_of_kin_phone = COALESCE($13, next_of_kin_phone),
    next_of_kin_relationship = COALESCE($14, next_of_kin_relationship),
    updated_at = CURRENT_TIMESTAMP
WHERE member_id = $1
`

type UpdateMemberProfileParams struct {
	MemberID              pgtype.UUID    `json:"memberId"`
	FullName              string         `json:"fullName"`
	Phone                 string         `json:"phone"`
	Email                 string         `json:"email"`
	Address               pgtype.Text    `json:"address"`
	DateOfBirth           pgtype.Date    `json:"dateOfBirth"`
	Occupation            pgtype.Text    `json:"occupation"`
	Employer              pgtype.Text    `json:"employer"`
	MonthlyIncome         pgtype.Numeric `json:"monthlyIncome"`
	IDDocumentType        pgtype.Text    `json:"idDocumentType"`
	IDDocumentNumber      pgtype.Text    `json:"idDocumentNumber"`
	NextOfKinName         pgtype.Text    `json:"nextOfKinName"`
	NextOfKinPhone        pgtype.Text    `json:"nextOfKinPhone"`
	NextOfKinRelationship pgtype.Text    `json:"nextOfKinRelationship"`
}

func (q *Queries) UpdateMemberProfile(ctx context.Context, arg UpdateMemberProfileParams) error {
	_, err := q.db.Exec(ctx, updateMemberProfile,
		arg.MemberID,
		arg.FullName,
		arg.Phone,
		arg.Email,
		arg.Address,
		arg.DateOfBirth,
		arg.Occupation,
		arg.Employer,
		arg.MonthlyIncome,
		arg.IDDocumentType,
		arg.IDDocumentNumber,
		arg.NextOfKinName,
		arg.NextOfKinPhone,
		arg.NextOfKinRelationship,
	)
	return err
}

const updateMemberStatus = `-- name: UpdateMemberStatus :one
UPDATE members
SET status = $2, updated_at = CURRENT_TIMESTAMP
WHERE id = $1 AND is_deleted = FALSE
RETURNING id, branch_id, status, updated_at
`

type UpdateMemberStatusParams struct {
	ID     pgtype.UUID `json:"id"`
	Status string      `json:"status"`
}

type UpdateMemberStatusRow struct {
	ID        pgtype.UUID        `json:"id"`
	BranchID  int64              `json:"branchId"`
	Status    string             `json:"status"`
	UpdatedAt pgtype.Timestamptz `json:"updatedAt"`
}

func (q *Queries) UpdateMemberStatus(ctx context.Context, arg UpdateMemberStatusParams) (UpdateMemberStatusRow, error) {
	row := q.db.QueryRow(ctx, updateMemberStatus, arg.ID, arg.Status)
	var i UpdateMemberStatusRow
	err := row.Scan(
		&i.ID,
		&i.BranchID,
		&i.Status,
		&i.UpdatedAt,
	)
	return i, err
}

const validateMemberActiveInBranch = `-- name: ValidateMemberActiveInBranch :one
SELECT id, branch_id, status
FROM members
WHERE id = $1 AND branch_id = $2 AND status = 'active' AND is_deleted = FALSE
`

type ValidateMemberActiveInBranchParams struct {
	ID       pgtype.UUID `json:"id"`
	BranchID int64       `json:"branchId"`
}

type ValidateMemberActiveInBranchRow struct {
	ID       pgtype.UUID `json:"id"`
	BranchID int64       `json:"branchId"`
	Status   string      `json:"status"`
}

func (q *Queries) ValidateMemberActiveInBranch(ctx context.Context, arg ValidateMemberActiveInBranchParams) (ValidateMemberActiveInBranchRow, error) {
	row := q.db.QueryRow(ctx, validateMemberActiveInBranch, arg.ID, arg.BranchID)
	var i ValidateMemberActiveInBranchRow
	err := row.Scan(&i.ID, &i.BranchID, &i.Status)
	return i, err
}
