// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package sqlc

import (
	"context"
)

type Querier interface {
	CreateMember(ctx context.Context, arg CreateMemberParams) (int64, error)
	CreateMemberProfile(ctx context.Context, arg CreateMemberProfileParams) (int64, error)
	DeactivateMember(ctx context.Context, id int64) (DeactivateMemberRow, error)
	GetMemberByBranchAndNumber(ctx context.Context, arg GetMemberByBranchAndNumberParams) (GetMemberByBranchAndNumberRow, error)
	GetMemberByID(ctx context.Context, id int64) (GetMemberByIDRow, error)
	GetMemberStatusHistory(ctx context.Context, memberID int64) ([]MemberStatusHistory, error)
	GetNextMemberNumber(ctx context.Context, branchID int64) (int64, error)
	IncrementMemberNumber(ctx context.Context, branchID int64) (int32, error)
	ListMembersByBranchCursor(ctx context.Context, arg ListMembersByBranchCursorParams) ([]ListMembersByBranchCursorRow, error)
	MemberExistsByBranchAndNationalID(ctx context.Context, arg MemberExistsByBranchAndNationalIDParams) (MemberExistsByBranchAndNationalIDRow, error)
	RecordMemberStatusTransition(ctx context.Context, arg RecordMemberStatusTransitionParams) error
	RecoverMemberNumberCounter(ctx context.Context, branchID int64) error
	UpdateMemberProfile(ctx context.Context, arg UpdateMemberProfileParams) error
	UpdateMemberStatus(ctx context.Context, arg UpdateMemberStatusParams) (UpdateMemberStatusRow, error)
	ValidateMemberActiveInBranch(ctx context.Context, arg ValidateMemberActiveInBranchParams) (ValidateMemberActiveInBranchRow, error)
}

var _ Querier = (*Queries)(nil)
