// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: audit_trails.sql

package loansqlc

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const insertLoanAuditTrail = `-- name: InsertLoanAuditTrail :one
INSERT INTO loan_audit_trails (loan_id, field_changed, previous_value, new_value, changed_by, change_reason, approval_reference)
VALUES ($1, $2, $3, $4, $5, $6, $7)
RETURNING id, loan_id, field_changed, previous_value, new_value, changed_by, change_reason, approval_reference, created_at
`

type InsertLoanAuditTrailParams struct {
	LoanID            pgtype.UUID `json:"loanId"`
	FieldChanged      string      `json:"fieldChanged"`
	PreviousValue     pgtype.Text `json:"previousValue"`
	NewValue          string      `json:"newValue"`
	ChangedBy         pgtype.UUID `json:"changedBy"`
	ChangeReason      string      `json:"changeReason"`
	ApprovalReference pgtype.Text `json:"approvalReference"`
}

func (q *Queries) InsertLoanAuditTrail(ctx context.Context, arg InsertLoanAuditTrailParams) (LoanAuditTrail, error) {
	row := q.db.QueryRow(ctx, insertLoanAuditTrail,
		arg.LoanID,
		arg.FieldChanged,
		arg.PreviousValue,
		arg.NewValue,
		arg.ChangedBy,
		arg.ChangeReason,
		arg.ApprovalReference,
	)
	var i LoanAuditTrail
	err := row.Scan(
		&i.ID,
		&i.LoanID,
		&i.FieldChanged,
		&i.PreviousValue,
		&i.NewValue,
		&i.ChangedBy,
		&i.ChangeReason,
		&i.ApprovalReference,
		&i.CreatedAt,
	)
	return i, err
}

const listLoanAuditTrail = `-- name: ListLoanAuditTrail :many
SELECT id, loan_id, field_changed, previous_value, new_value, changed_by, change_reason, approval_reference, created_at
FROM loan_audit_trails
WHERE loan_id = $1
  AND ($2::timestamptz IS NULL OR created_at < $2 OR (created_at = $2 AND id < $3))
ORDER BY created_at DESC, id DESC
LIMIT $4
`

type ListLoanAuditTrailParams struct {
	LoanID  pgtype.UUID        `json:"loanId"`
	Column2 pgtype.Timestamptz `json:"column2"`
	ID      pgtype.UUID        `json:"id"`
	Limit   int32              `json:"limit"`
}

func (q *Queries) ListLoanAuditTrail(ctx context.Context, arg ListLoanAuditTrailParams) ([]LoanAuditTrail, error) {
	rows, err := q.db.Query(ctx, listLoanAuditTrail,
		arg.LoanID,
		arg.Column2,
		arg.ID,
		arg.Limit,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []LoanAuditTrail
	for rows.Next() {
		var i LoanAuditTrail
		if err := rows.Scan(
			&i.ID,
			&i.LoanID,
			&i.FieldChanged,
			&i.PreviousValue,
			&i.NewValue,
			&i.ChangedBy,
			&i.ChangeReason,
			&i.ApprovalReference,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
