// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: credit_balances.sql

package loansqlc

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createCreditBalance = `-- name: CreateCreditBalance :one
INSERT INTO credit_balances (member_id, loan_id, amount, source, status)
VALUES ($1, $2, $3, $4, 'available')
RETURNING id, member_id, loan_id, amount, source, status, created_at, last_activity_at
`

type CreateCreditBalanceParams struct {
	MemberID pgtype.UUID         `json:"memberId"`
	LoanID   pgtype.UUID         `json:"loanId"`
	Amount   pgtype.Numeric      `json:"amount"`
	Source   CreditBalanceSource `json:"source"`
}

func (q *Queries) CreateCreditBalance(ctx context.Context, arg CreateCreditBalanceParams) (CreditBalance, error) {
	row := q.db.QueryRow(ctx, createCreditBalance,
		arg.MemberID,
		arg.LoanID,
		arg.Amount,
		arg.Source,
	)
	var i CreditBalance
	err := row.Scan(
		&i.ID,
		&i.MemberID,
		&i.LoanID,
		&i.Amount,
		&i.Source,
		&i.Status,
		&i.CreatedAt,
		&i.LastActivityAt,
	)
	return i, err
}

const getCreditBalanceByID = `-- name: GetCreditBalanceByID :one
SELECT id, member_id, loan_id, amount, source, status, created_at, last_activity_at
FROM credit_balances
WHERE id = $1
`

func (q *Queries) GetCreditBalanceByID(ctx context.Context, id pgtype.UUID) (CreditBalance, error) {
	row := q.db.QueryRow(ctx, getCreditBalanceByID, id)
	var i CreditBalance
	err := row.Scan(
		&i.ID,
		&i.MemberID,
		&i.LoanID,
		&i.Amount,
		&i.Source,
		&i.Status,
		&i.CreatedAt,
		&i.LastActivityAt,
	)
	return i, err
}

const listCreditBalancesByMember = `-- name: ListCreditBalancesByMember :many
SELECT id, member_id, loan_id, amount, source, status, created_at, last_activity_at
FROM credit_balances
WHERE member_id = $1
  AND ($2::credit_balance_status IS NULL OR status = $2)
ORDER BY created_at DESC, id DESC
LIMIT $3
`

type ListCreditBalancesByMemberParams struct {
	MemberID pgtype.UUID         `json:"memberId"`
	Column2  CreditBalanceStatus `json:"column2"`
	Limit    int32               `json:"limit"`
}

func (q *Queries) ListCreditBalancesByMember(ctx context.Context, arg ListCreditBalancesByMemberParams) ([]CreditBalance, error) {
	rows, err := q.db.Query(ctx, listCreditBalancesByMember, arg.MemberID, arg.Column2, arg.Limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []CreditBalance
	for rows.Next() {
		var i CreditBalance
		if err := rows.Scan(
			&i.ID,
			&i.MemberID,
			&i.LoanID,
			&i.Amount,
			&i.Source,
			&i.Status,
			&i.CreatedAt,
			&i.LastActivityAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const lockCreditBalanceByID = `-- name: LockCreditBalanceByID :one
SELECT id, member_id, loan_id, amount, source, status, created_at, last_activity_at
FROM credit_balances
WHERE id = $1
FOR UPDATE
`

func (q *Queries) LockCreditBalanceByID(ctx context.Context, id pgtype.UUID) (CreditBalance, error) {
	row := q.db.QueryRow(ctx, lockCreditBalanceByID, id)
	var i CreditBalance
	err := row.Scan(
		&i.ID,
		&i.MemberID,
		&i.LoanID,
		&i.Amount,
		&i.Source,
		&i.Status,
		&i.CreatedAt,
		&i.LastActivityAt,
	)
	return i, err
}

const updateCreditBalanceStatus = `-- name: UpdateCreditBalanceStatus :one
UPDATE credit_balances
SET status = $2,
    last_activity_at = NOW()
WHERE id = $1
RETURNING id, member_id, loan_id, amount, source, status, created_at, last_activity_at
`

type UpdateCreditBalanceStatusParams struct {
	ID     pgtype.UUID         `json:"id"`
	Status CreditBalanceStatus `json:"status"`
}

func (q *Queries) UpdateCreditBalanceStatus(ctx context.Context, arg UpdateCreditBalanceStatusParams) (CreditBalance, error) {
	row := q.db.QueryRow(ctx, updateCreditBalanceStatus, arg.ID, arg.Status)
	var i CreditBalance
	err := row.Scan(
		&i.ID,
		&i.MemberID,
		&i.LoanID,
		&i.Amount,
		&i.Source,
		&i.Status,
		&i.CreatedAt,
		&i.LastActivityAt,
	)
	return i, err
}
