// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: guarantors.sql

package loansqlc

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const countApprovedGuarantors = `-- name: CountApprovedGuarantors :one
SELECT COUNT(*) as count
FROM loan_guarantors
WHERE loan_id = $1 AND status = 'approved'
`

func (q *Queries) CountApprovedGuarantors(ctx context.Context, loanID pgtype.UUID) (int64, error) {
	row := q.db.QueryRow(ctx, countApprovedGuarantors, loanID)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const createLoanGuarantor = `-- name: CreateLoanGuarantor :one
INSERT INTO loan_guarantors (loan_id, guarantor_id, guaranteed_amount, status, approved_by)
VALUES ($1, $2, $3, $4, $5)
RETURNING loan_id, guarantor_id, guaranteed_amount, status, approved_at, approved_by, created_at
`

type CreateLoanGuarantorParams struct {
	LoanID           pgtype.UUID     `json:"loanId"`
	GuarantorID      pgtype.UUID     `json:"guarantorId"`
	GuaranteedAmount pgtype.Numeric  `json:"guaranteedAmount"`
	Status           GuarantorStatus `json:"status"`
	ApprovedBy       pgtype.UUID     `json:"approvedBy"`
}

func (q *Queries) CreateLoanGuarantor(ctx context.Context, arg CreateLoanGuarantorParams) (LoanGuarantor, error) {
	row := q.db.QueryRow(ctx, createLoanGuarantor,
		arg.LoanID,
		arg.GuarantorID,
		arg.GuaranteedAmount,
		arg.Status,
		arg.ApprovedBy,
	)
	var i LoanGuarantor
	err := row.Scan(
		&i.LoanID,
		&i.GuarantorID,
		&i.GuaranteedAmount,
		&i.Status,
		&i.ApprovedAt,
		&i.ApprovedBy,
		&i.CreatedAt,
	)
	return i, err
}

const getLoanGuarantor = `-- name: GetLoanGuarantor :one
SELECT loan_id, guarantor_id, guaranteed_amount, status, approved_at, approved_by, created_at
FROM loan_guarantors
WHERE loan_id = $1 AND guarantor_id = $2
`

type GetLoanGuarantorParams struct {
	LoanID      pgtype.UUID `json:"loanId"`
	GuarantorID pgtype.UUID `json:"guarantorId"`
}

func (q *Queries) GetLoanGuarantor(ctx context.Context, arg GetLoanGuarantorParams) (LoanGuarantor, error) {
	row := q.db.QueryRow(ctx, getLoanGuarantor, arg.LoanID, arg.GuarantorID)
	var i LoanGuarantor
	err := row.Scan(
		&i.LoanID,
		&i.GuarantorID,
		&i.GuaranteedAmount,
		&i.Status,
		&i.ApprovedAt,
		&i.ApprovedBy,
		&i.CreatedAt,
	)
	return i, err
}

const getTotalGuaranteedAmount = `-- name: GetTotalGuaranteedAmount :one
SELECT COALESCE(SUM(guaranteed_amount), 0) as total_guaranteed
FROM loan_guarantors
WHERE loan_id = $1 AND status = 'approved'
`

func (q *Queries) GetTotalGuaranteedAmount(ctx context.Context, loanID pgtype.UUID) (interface{}, error) {
	row := q.db.QueryRow(ctx, getTotalGuaranteedAmount, loanID)
	var total_guaranteed interface{}
	err := row.Scan(&total_guaranteed)
	return total_guaranteed, err
}

const listGuarantorLoans = `-- name: ListGuarantorLoans :many
SELECT lg.loan_id, lg.guarantor_id, lg.guaranteed_amount, lg.status, lg.approved_at, lg.approved_by, lg.created_at,
       l.member_id, l.principal, l.status as loan_status
FROM loan_guarantors lg
JOIN loans l ON lg.loan_id = l.id
WHERE lg.guarantor_id = $1 AND l.is_deleted = FALSE
ORDER BY lg.created_at DESC
`

type ListGuarantorLoansRow struct {
	LoanID           pgtype.UUID        `json:"loanId"`
	GuarantorID      pgtype.UUID        `json:"guarantorId"`
	GuaranteedAmount pgtype.Numeric     `json:"guaranteedAmount"`
	Status           GuarantorStatus    `json:"status"`
	ApprovedAt       pgtype.Timestamptz `json:"approvedAt"`
	ApprovedBy       pgtype.UUID        `json:"approvedBy"`
	CreatedAt        pgtype.Timestamptz `json:"createdAt"`
	MemberID         pgtype.UUID        `json:"memberId"`
	Principal        pgtype.Numeric     `json:"principal"`
	LoanStatus       LoanStatus         `json:"loanStatus"`
}

func (q *Queries) ListGuarantorLoans(ctx context.Context, guarantorID pgtype.UUID) ([]ListGuarantorLoansRow, error) {
	rows, err := q.db.Query(ctx, listGuarantorLoans, guarantorID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListGuarantorLoansRow
	for rows.Next() {
		var i ListGuarantorLoansRow
		if err := rows.Scan(
			&i.LoanID,
			&i.GuarantorID,
			&i.GuaranteedAmount,
			&i.Status,
			&i.ApprovedAt,
			&i.ApprovedBy,
			&i.CreatedAt,
			&i.MemberID,
			&i.Principal,
			&i.LoanStatus,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listLoanGuarantors = `-- name: ListLoanGuarantors :many
SELECT loan_id, guarantor_id, guaranteed_amount, status, approved_at, approved_by, created_at
FROM loan_guarantors
WHERE loan_id = $1
ORDER BY created_at DESC
`

func (q *Queries) ListLoanGuarantors(ctx context.Context, loanID pgtype.UUID) ([]LoanGuarantor, error) {
	rows, err := q.db.Query(ctx, listLoanGuarantors, loanID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []LoanGuarantor
	for rows.Next() {
		var i LoanGuarantor
		if err := rows.Scan(
			&i.LoanID,
			&i.GuarantorID,
			&i.GuaranteedAmount,
			&i.Status,
			&i.ApprovedAt,
			&i.ApprovedBy,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const lockGuarantor = `-- name: LockGuarantor :one
SELECT loan_id, guarantor_id, guaranteed_amount, status, approved_at, approved_by, created_at
FROM loan_guarantors
WHERE loan_id = $1 AND guarantor_id = $2
FOR UPDATE
`

type LockGuarantorParams struct {
	LoanID      pgtype.UUID `json:"loanId"`
	GuarantorID pgtype.UUID `json:"guarantorId"`
}

func (q *Queries) LockGuarantor(ctx context.Context, arg LockGuarantorParams) (LoanGuarantor, error) {
	row := q.db.QueryRow(ctx, lockGuarantor, arg.LoanID, arg.GuarantorID)
	var i LoanGuarantor
	err := row.Scan(
		&i.LoanID,
		&i.GuarantorID,
		&i.GuaranteedAmount,
		&i.Status,
		&i.ApprovedAt,
		&i.ApprovedBy,
		&i.CreatedAt,
	)
	return i, err
}

const updateGuarantorStatus = `-- name: UpdateGuarantorStatus :one
UPDATE loan_guarantors
SET status = $2,
    approved_at = CASE WHEN $2 = 'approved' THEN NOW() ELSE approved_at END,
    approved_by = $3
WHERE loan_id = $1 AND guarantor_id = $4
RETURNING loan_id, guarantor_id, guaranteed_amount, status, approved_at, approved_by, created_at
`

type UpdateGuarantorStatusParams struct {
	LoanID      pgtype.UUID     `json:"loanId"`
	Status      GuarantorStatus `json:"status"`
	ApprovedBy  pgtype.UUID     `json:"approvedBy"`
	GuarantorID pgtype.UUID     `json:"guarantorId"`
}

func (q *Queries) UpdateGuarantorStatus(ctx context.Context, arg UpdateGuarantorStatusParams) (LoanGuarantor, error) {
	row := q.db.QueryRow(ctx, updateGuarantorStatus,
		arg.LoanID,
		arg.Status,
		arg.ApprovedBy,
		arg.GuarantorID,
	)
	var i LoanGuarantor
	err := row.Scan(
		&i.LoanID,
		&i.GuarantorID,
		&i.GuaranteedAmount,
		&i.Status,
		&i.ApprovedAt,
		&i.ApprovedBy,
		&i.CreatedAt,
	)
	return i, err
}
