// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: interest.sql

package loansqlc

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const assessLoanInterest = `-- name: AssessLoanInterest :exec
INSERT INTO loan_monthly_interest (loan_id, period, previous_balance, rate, amount)
SELECT l.id, $1::date,
       GREATEST(l.principal - paid.principal, 0), l.interest_rate,
       ROUND(GREATEST(l.principal - paid.principal, 0) * l.interest_rate, 4)
FROM loans l
CROSS JOIN LATERAL (
    SELECT COALESCE(SUM(COALESCE((t.allocation_breakdown->>'principal')::numeric,
        t.amount - COALESCE((t.allocation_breakdown->>'credit')::numeric, 0))), 0)::numeric AS principal
    FROM loan_transactions t WHERE t.loan_id = l.id AND t.type = 'repayment'
      AND COALESCE((t.allocation_breakdown->>'period')::date,
          date_trunc('month', t.created_at AT TIME ZONE 'Africa/Nairobi')::date) < $1::date
) paid
WHERE l.id = $2
ON CONFLICT DO NOTHING
`

type AssessLoanInterestParams struct {
	Period pgtype.Date `json:"period"`
	LoanID pgtype.UUID `json:"loanId"`
}

func (q *Queries) AssessLoanInterest(ctx context.Context, arg AssessLoanInterestParams) error {
	_, err := q.db.Exec(ctx, assessLoanInterest, arg.Period, arg.LoanID)
	return err
}

const getLoanInterestPeriod = `-- name: GetLoanInterestPeriod :one
SELECT MAX(period)::date AS latest_period
FROM loan_monthly_interest WHERE loan_id = $1
`

func (q *Queries) GetLoanInterestPeriod(ctx context.Context, loanID pgtype.UUID) (pgtype.Date, error) {
	row := q.db.QueryRow(ctx, getLoanInterestPeriod, loanID)
	var latest_period pgtype.Date
	err := row.Scan(&latest_period)
	return latest_period, err
}

const getLoanRepaymentTotals = `-- name: GetLoanRepaymentTotals :one
SELECT
    COALESCE(SUM(COALESCE((allocation_breakdown->>'principal')::numeric,
        amount - COALESCE((allocation_breakdown->>'credit')::numeric, 0))), 0)::numeric AS principal,
    COALESCE(SUM((allocation_breakdown->>'interest')::numeric), 0)::numeric AS interest,
    MAX(COALESCE((allocation_breakdown->>'period')::date,
        date_trunc('month', created_at AT TIME ZONE 'Africa/Nairobi')::date))::date AS latest_period
FROM loan_transactions WHERE loan_id = $1 AND type = 'repayment'
`

type GetLoanRepaymentTotalsRow struct {
	Principal    pgtype.Numeric `json:"principal"`
	Interest     pgtype.Numeric `json:"interest"`
	LatestPeriod pgtype.Date    `json:"latestPeriod"`
}

func (q *Queries) GetLoanRepaymentTotals(ctx context.Context, loanID pgtype.UUID) (GetLoanRepaymentTotalsRow, error) {
	row := q.db.QueryRow(ctx, getLoanRepaymentTotals, loanID)
	var i GetLoanRepaymentTotalsRow
	err := row.Scan(&i.Principal, &i.Interest, &i.LatestPeriod)
	return i, err
}

const sumLoanInterestDue = `-- name: SumLoanInterestDue :one
SELECT COALESCE(SUM(amount), 0)::numeric AS total
FROM loan_monthly_interest WHERE loan_id = $1
`

func (q *Queries) SumLoanInterestDue(ctx context.Context, loanID pgtype.UUID) (pgtype.Numeric, error) {
	row := q.db.QueryRow(ctx, sumLoanInterestDue, loanID)
	var total pgtype.Numeric
	err := row.Scan(&total)
	return total, err
}
