// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: loans.sql

package loansqlc

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createLoan = `-- name: CreateLoan :one
INSERT INTO loans (member_id, branch_id, principal, interest_rate, repayment_period_months, updated_by)
VALUES ($1, $2, $3, $4, $5, $6)
RETURNING id, member_id, branch_id, principal, interest_rate, repayment_period_months, status, disbursed_at, updated_by, previous_status, is_deleted, created_at, updated_at
`

type CreateLoanParams struct {
	MemberID              pgtype.UUID    `json:"memberId"`
	BranchID              int64          `json:"branchId"`
	Principal             pgtype.Numeric `json:"principal"`
	InterestRate          pgtype.Numeric `json:"interestRate"`
	RepaymentPeriodMonths int32          `json:"repaymentPeriodMonths"`
	UpdatedBy             pgtype.UUID    `json:"updatedBy"`
}

type CreateLoanRow struct {
	ID                    pgtype.UUID        `json:"id"`
	MemberID              pgtype.UUID        `json:"memberId"`
	BranchID              int64              `json:"branchId"`
	Principal             pgtype.Numeric     `json:"principal"`
	InterestRate          pgtype.Numeric     `json:"interestRate"`
	RepaymentPeriodMonths int32              `json:"repaymentPeriodMonths"`
	Status                LoanStatus         `json:"status"`
	DisbursedAt           pgtype.Timestamptz `json:"disbursedAt"`
	UpdatedBy             pgtype.UUID        `json:"updatedBy"`
	PreviousStatus        NullLoanStatus     `json:"previousStatus"`
	IsDeleted             bool               `json:"isDeleted"`
	CreatedAt             pgtype.Timestamptz `json:"createdAt"`
	UpdatedAt             pgtype.Timestamptz `json:"updatedAt"`
}

func (q *Queries) CreateLoan(ctx context.Context, arg CreateLoanParams) (CreateLoanRow, error) {
	row := q.db.QueryRow(ctx, createLoan,
		arg.MemberID,
		arg.BranchID,
		arg.Principal,
		arg.InterestRate,
		arg.RepaymentPeriodMonths,
		arg.UpdatedBy,
	)
	var i CreateLoanRow
	err := row.Scan(
		&i.ID,
		&i.MemberID,
		&i.BranchID,
		&i.Principal,
		&i.InterestRate,
		&i.RepaymentPeriodMonths,
		&i.Status,
		&i.DisbursedAt,
		&i.UpdatedBy,
		&i.PreviousStatus,
		&i.IsDeleted,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getLoanByID = `-- name: GetLoanByID :one
SELECT id, member_id, branch_id, principal, interest_rate, repayment_period_months, status, disbursed_at, updated_by, previous_status, is_deleted, created_at, updated_at
FROM loans
WHERE id = $1 AND is_deleted = FALSE
`

type GetLoanByIDRow struct {
	ID                    pgtype.UUID        `json:"id"`
	MemberID              pgtype.UUID        `json:"memberId"`
	BranchID              int64              `json:"branchId"`
	Principal             pgtype.Numeric     `json:"principal"`
	InterestRate          pgtype.Numeric     `json:"interestRate"`
	RepaymentPeriodMonths int32              `json:"repaymentPeriodMonths"`
	Status                LoanStatus         `json:"status"`
	DisbursedAt           pgtype.Timestamptz `json:"disbursedAt"`
	UpdatedBy             pgtype.UUID        `json:"updatedBy"`
	PreviousStatus        NullLoanStatus     `json:"previousStatus"`
	IsDeleted             bool               `json:"isDeleted"`
	CreatedAt             pgtype.Timestamptz `json:"createdAt"`
	UpdatedAt             pgtype.Timestamptz `json:"updatedAt"`
}

func (q *Queries) GetLoanByID(ctx context.Context, id pgtype.UUID) (GetLoanByIDRow, error) {
	row := q.db.QueryRow(ctx, getLoanByID, id)
	var i GetLoanByIDRow
	err := row.Scan(
		&i.ID,
		&i.MemberID,
		&i.BranchID,
		&i.Principal,
		&i.InterestRate,
		&i.RepaymentPeriodMonths,
		&i.Status,
		&i.DisbursedAt,
		&i.UpdatedBy,
		&i.PreviousStatus,
		&i.IsDeleted,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listLoansByBranch = `-- name: ListLoansByBranch :many
SELECT id, member_id, branch_id, principal, interest_rate, repayment_period_months, status, disbursed_at, updated_by, previous_status, is_deleted, created_at, updated_at
FROM loans
WHERE branch_id = $1
  AND is_deleted = FALSE
  AND ($2::timestamptz IS NULL OR created_at < $2 OR (created_at = $2 AND id < $3))
  AND ($5::loan_status IS NULL OR status = $5)
ORDER BY created_at DESC, id DESC
LIMIT $4
`

type ListLoansByBranchParams struct {
	BranchID     int64              `json:"branchId"`
	Column2      pgtype.Timestamptz `json:"column2"`
	ID           pgtype.UUID        `json:"id"`
	Limit        int32              `json:"limit"`
	StatusFilter NullLoanStatus     `json:"statusFilter"`
}

type ListLoansByBranchRow struct {
	ID                    pgtype.UUID        `json:"id"`
	MemberID              pgtype.UUID        `json:"memberId"`
	BranchID              int64              `json:"branchId"`
	Principal             pgtype.Numeric     `json:"principal"`
	InterestRate          pgtype.Numeric     `json:"interestRate"`
	RepaymentPeriodMonths int32              `json:"repaymentPeriodMonths"`
	Status                LoanStatus         `json:"status"`
	DisbursedAt           pgtype.Timestamptz `json:"disbursedAt"`
	UpdatedBy             pgtype.UUID        `json:"updatedBy"`
	PreviousStatus        NullLoanStatus     `json:"previousStatus"`
	IsDeleted             bool               `json:"isDeleted"`
	CreatedAt             pgtype.Timestamptz `json:"createdAt"`
	UpdatedAt             pgtype.Timestamptz `json:"updatedAt"`
}

func (q *Queries) ListLoansByBranch(ctx context.Context, arg ListLoansByBranchParams) ([]ListLoansByBranchRow, error) {
	rows, err := q.db.Query(ctx, listLoansByBranch,
		arg.BranchID,
		arg.Column2,
		arg.ID,
		arg.Limit,
		arg.StatusFilter,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListLoansByBranchRow
	for rows.Next() {
		var i ListLoansByBranchRow
		if err := rows.Scan(
			&i.ID,
			&i.MemberID,
			&i.BranchID,
			&i.Principal,
			&i.InterestRate,
			&i.RepaymentPeriodMonths,
			&i.Status,
			&i.DisbursedAt,
			&i.UpdatedBy,
			&i.PreviousStatus,
			&i.IsDeleted,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listLoansByMember = `-- name: ListLoansByMember :many
SELECT id, member_id, branch_id, principal, interest_rate, repayment_period_months, status, disbursed_at, updated_by, previous_status, is_deleted, created_at, updated_at
FROM loans
WHERE member_id = $1
  AND is_deleted = FALSE
  AND ($2::timestamptz IS NULL OR created_at < $2 OR (created_at = $2 AND id < $3))
ORDER BY created_at DESC, id DESC
LIMIT $4
`

type ListLoansByMemberParams struct {
	MemberID pgtype.UUID        `json:"memberId"`
	Column2  pgtype.Timestamptz `json:"column2"`
	ID       pgtype.UUID        `json:"id"`
	Limit    int32              `json:"limit"`
}

type ListLoansByMemberRow struct {
	ID                    pgtype.UUID        `json:"id"`
	MemberID              pgtype.UUID        `json:"memberId"`
	BranchID              int64              `json:"branchId"`
	Principal             pgtype.Numeric     `json:"principal"`
	InterestRate          pgtype.Numeric     `json:"interestRate"`
	RepaymentPeriodMonths int32              `json:"repaymentPeriodMonths"`
	Status                LoanStatus         `json:"status"`
	DisbursedAt           pgtype.Timestamptz `json:"disbursedAt"`
	UpdatedBy             pgtype.UUID        `json:"updatedBy"`
	PreviousStatus        NullLoanStatus     `json:"previousStatus"`
	IsDeleted             bool               `json:"isDeleted"`
	CreatedAt             pgtype.Timestamptz `json:"createdAt"`
	UpdatedAt             pgtype.Timestamptz `json:"updatedAt"`
}

func (q *Queries) ListLoansByMember(ctx context.Context, arg ListLoansByMemberParams) ([]ListLoansByMemberRow, error) {
	rows, err := q.db.Query(ctx, listLoansByMember,
		arg.MemberID,
		arg.Column2,
		arg.ID,
		arg.Limit,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListLoansByMemberRow
	for rows.Next() {
		var i ListLoansByMemberRow
		if err := rows.Scan(
			&i.ID,
			&i.MemberID,
			&i.BranchID,
			&i.Principal,
			&i.InterestRate,
			&i.RepaymentPeriodMonths,
			&i.Status,
			&i.DisbursedAt,
			&i.UpdatedBy,
			&i.PreviousStatus,
			&i.IsDeleted,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listLoansForDelinquencyUpdate = `-- name: ListLoansForDelinquencyUpdate :many
SELECT id, member_id, branch_id, principal, interest_rate, repayment_period_months, status, disbursed_at, updated_by, previous_status, is_deleted, created_at, updated_at
FROM loans
WHERE status IN ('active', 'delinquent')
  AND is_deleted = FALSE
ORDER BY created_at ASC, id ASC
LIMIT $1
FOR UPDATE SKIP LOCKED
`

type ListLoansForDelinquencyUpdateRow struct {
	ID                    pgtype.UUID        `json:"id"`
	MemberID              pgtype.UUID        `json:"memberId"`
	BranchID              int64              `json:"branchId"`
	Principal             pgtype.Numeric     `json:"principal"`
	InterestRate          pgtype.Numeric     `json:"interestRate"`
	RepaymentPeriodMonths int32              `json:"repaymentPeriodMonths"`
	Status                LoanStatus         `json:"status"`
	DisbursedAt           pgtype.Timestamptz `json:"disbursedAt"`
	UpdatedBy             pgtype.UUID        `json:"updatedBy"`
	PreviousStatus        NullLoanStatus     `json:"previousStatus"`
	IsDeleted             bool               `json:"isDeleted"`
	CreatedAt             pgtype.Timestamptz `json:"createdAt"`
	UpdatedAt             pgtype.Timestamptz `json:"updatedAt"`
}

func (q *Queries) ListLoansForDelinquencyUpdate(ctx context.Context, limit int32) ([]ListLoansForDelinquencyUpdateRow, error) {
	rows, err := q.db.Query(ctx, listLoansForDelinquencyUpdate, limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListLoansForDelinquencyUpdateRow
	for rows.Next() {
		var i ListLoansForDelinquencyUpdateRow
		if err := rows.Scan(
			&i.ID,
			&i.MemberID,
			&i.BranchID,
			&i.Principal,
			&i.InterestRate,
			&i.RepaymentPeriodMonths,
			&i.Status,
			&i.DisbursedAt,
			&i.UpdatedBy,
			&i.PreviousStatus,
			&i.IsDeleted,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const lockLoanByID = `-- name: LockLoanByID :one
SELECT id, member_id, branch_id, principal, interest_rate, repayment_period_months, status, disbursed_at, updated_by, previous_status, is_deleted, created_at, updated_at
FROM loans
WHERE id = $1 AND is_deleted = FALSE
FOR UPDATE
`

type LockLoanByIDRow struct {
	ID                    pgtype.UUID        `json:"id"`
	MemberID              pgtype.UUID        `json:"memberId"`
	BranchID              int64              `json:"branchId"`
	Principal             pgtype.Numeric     `json:"principal"`
	InterestRate          pgtype.Numeric     `json:"interestRate"`
	RepaymentPeriodMonths int32              `json:"repaymentPeriodMonths"`
	Status                LoanStatus         `json:"status"`
	DisbursedAt           pgtype.Timestamptz `json:"disbursedAt"`
	UpdatedBy             pgtype.UUID        `json:"updatedBy"`
	PreviousStatus        NullLoanStatus     `json:"previousStatus"`
	IsDeleted             bool               `json:"isDeleted"`
	CreatedAt             pgtype.Timestamptz `json:"createdAt"`
	UpdatedAt             pgtype.Timestamptz `json:"updatedAt"`
}

func (q *Queries) LockLoanByID(ctx context.Context, id pgtype.UUID) (LockLoanByIDRow, error) {
	row := q.db.QueryRow(ctx, lockLoanByID, id)
	var i LockLoanByIDRow
	err := row.Scan(
		&i.ID,
		&i.MemberID,
		&i.BranchID,
		&i.Principal,
		&i.InterestRate,
		&i.RepaymentPeriodMonths,
		&i.Status,
		&i.DisbursedAt,
		&i.UpdatedBy,
		&i.PreviousStatus,
		&i.IsDeleted,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const markLoanDisbursed = `-- name: MarkLoanDisbursed :one
UPDATE loans
SET previous_status = status,
    status = 'disbursed',
    disbursed_at = NOW(),
    updated_by = $2,
    updated_at = NOW()
WHERE id = $1 AND status = 'approved' AND is_deleted = FALSE
RETURNING id, member_id, branch_id, principal, interest_rate, repayment_period_months, status, disbursed_at, updated_by, previous_status, is_deleted, created_at, updated_at
`

type MarkLoanDisbursedParams struct {
	ID        pgtype.UUID `json:"id"`
	UpdatedBy pgtype.UUID `json:"updatedBy"`
}

type MarkLoanDisbursedRow struct {
	ID                    pgtype.UUID        `json:"id"`
	MemberID              pgtype.UUID        `json:"memberId"`
	BranchID              int64              `json:"branchId"`
	Principal             pgtype.Numeric     `json:"principal"`
	InterestRate          pgtype.Numeric     `json:"interestRate"`
	RepaymentPeriodMonths int32              `json:"repaymentPeriodMonths"`
	Status                LoanStatus         `json:"status"`
	DisbursedAt           pgtype.Timestamptz `json:"disbursedAt"`
	UpdatedBy             pgtype.UUID        `json:"updatedBy"`
	PreviousStatus        NullLoanStatus     `json:"previousStatus"`
	IsDeleted             bool               `json:"isDeleted"`
	CreatedAt             pgtype.Timestamptz `json:"createdAt"`
	UpdatedAt             pgtype.Timestamptz `json:"updatedAt"`
}

func (q *Queries) MarkLoanDisbursed(ctx context.Context, arg MarkLoanDisbursedParams) (MarkLoanDisbursedRow, error) {
	row := q.db.QueryRow(ctx, markLoanDisbursed, arg.ID, arg.UpdatedBy)
	var i MarkLoanDisbursedRow
	err := row.Scan(
		&i.ID,
		&i.MemberID,
		&i.BranchID,
		&i.Principal,
		&i.InterestRate,
		&i.RepaymentPeriodMonths,
		&i.Status,
		&i.DisbursedAt,
		&i.UpdatedBy,
		&i.PreviousStatus,
		&i.IsDeleted,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const softDeleteLoan = `-- name: SoftDeleteLoan :one
UPDATE loans
SET is_deleted = TRUE,
    updated_by = $2,
    updated_at = NOW()
WHERE id = $1 AND is_deleted = FALSE
RETURNING id, member_id, branch_id, principal, interest_rate, repayment_period_months, status, disbursed_at, updated_by, previous_status, is_deleted, created_at, updated_at
`

type SoftDeleteLoanParams struct {
	ID        pgtype.UUID `json:"id"`
	UpdatedBy pgtype.UUID `json:"updatedBy"`
}

type SoftDeleteLoanRow struct {
	ID                    pgtype.UUID        `json:"id"`
	MemberID              pgtype.UUID        `json:"memberId"`
	BranchID              int64              `json:"branchId"`
	Principal             pgtype.Numeric     `json:"principal"`
	InterestRate          pgtype.Numeric     `json:"interestRate"`
	RepaymentPeriodMonths int32              `json:"repaymentPeriodMonths"`
	Status                LoanStatus         `json:"status"`
	DisbursedAt           pgtype.Timestamptz `json:"disbursedAt"`
	UpdatedBy             pgtype.UUID        `json:"updatedBy"`
	PreviousStatus        NullLoanStatus     `json:"previousStatus"`
	IsDeleted             bool               `json:"isDeleted"`
	CreatedAt             pgtype.Timestamptz `json:"createdAt"`
	UpdatedAt             pgtype.Timestamptz `json:"updatedAt"`
}

func (q *Queries) SoftDeleteLoan(ctx context.Context, arg SoftDeleteLoanParams) (SoftDeleteLoanRow, error) {
	row := q.db.QueryRow(ctx, softDeleteLoan, arg.ID, arg.UpdatedBy)
	var i SoftDeleteLoanRow
	err := row.Scan(
		&i.ID,
		&i.MemberID,
		&i.BranchID,
		&i.Principal,
		&i.InterestRate,
		&i.RepaymentPeriodMonths,
		&i.Status,
		&i.DisbursedAt,
		&i.UpdatedBy,
		&i.PreviousStatus,
		&i.IsDeleted,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const updateLoanStatus = `-- name: UpdateLoanStatus :one
UPDATE loans
SET previous_status = status,
    status = $2,
    updated_by = $3,
    updated_at = NOW()
WHERE id = $1 AND is_deleted = FALSE
RETURNING id, member_id, branch_id, principal, interest_rate, repayment_period_months, status, disbursed_at, updated_by, previous_status, is_deleted, created_at, updated_at
`

type UpdateLoanStatusParams struct {
	ID        pgtype.UUID `json:"id"`
	Status    LoanStatus  `json:"status"`
	UpdatedBy pgtype.UUID `json:"updatedBy"`
}

type UpdateLoanStatusRow struct {
	ID                    pgtype.UUID        `json:"id"`
	MemberID              pgtype.UUID        `json:"memberId"`
	BranchID              int64              `json:"branchId"`
	Principal             pgtype.Numeric     `json:"principal"`
	InterestRate          pgtype.Numeric     `json:"interestRate"`
	RepaymentPeriodMonths int32              `json:"repaymentPeriodMonths"`
	Status                LoanStatus         `json:"status"`
	DisbursedAt           pgtype.Timestamptz `json:"disbursedAt"`
	UpdatedBy             pgtype.UUID        `json:"updatedBy"`
	PreviousStatus        NullLoanStatus     `json:"previousStatus"`
	IsDeleted             bool               `json:"isDeleted"`
	CreatedAt             pgtype.Timestamptz `json:"createdAt"`
	UpdatedAt             pgtype.Timestamptz `json:"updatedAt"`
}

func (q *Queries) UpdateLoanStatus(ctx context.Context, arg UpdateLoanStatusParams) (UpdateLoanStatusRow, error) {
	row := q.db.QueryRow(ctx, updateLoanStatus, arg.ID, arg.Status, arg.UpdatedBy)
	var i UpdateLoanStatusRow
	err := row.Scan(
		&i.ID,
		&i.MemberID,
		&i.BranchID,
		&i.Principal,
		&i.InterestRate,
		&i.RepaymentPeriodMonths,
		&i.Status,
		&i.DisbursedAt,
		&i.UpdatedBy,
		&i.PreviousStatus,
		&i.IsDeleted,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
