// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: loans.sql

package loansqlc

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createLoan = `-- name: CreateLoan :one
INSERT INTO loans (member_id, branch_id, principal, interest_rate, collateral_value, collateral_coverage_ratio, updated_by)
VALUES ($1, $2, $3, $4, $5, $6, $7)
RETURNING id, member_id, branch_id, principal, interest_rate, collateral_value, collateral_coverage_ratio, status, disbursed_at, updated_by, previous_status, is_deleted, created_at, updated_at
`

type CreateLoanParams struct {
	MemberID                pgtype.UUID    `json:"memberId"`
	BranchID                int64          `json:"branchId"`
	Principal               pgtype.Numeric `json:"principal"`
	InterestRate            pgtype.Numeric `json:"interestRate"`
	CollateralValue         pgtype.Numeric `json:"collateralValue"`
	CollateralCoverageRatio pgtype.Numeric `json:"collateralCoverageRatio"`
	UpdatedBy               pgtype.UUID    `json:"updatedBy"`
}

func (q *Queries) CreateLoan(ctx context.Context, arg CreateLoanParams) (Loan, error) {
	row := q.db.QueryRow(ctx, createLoan,
		arg.MemberID,
		arg.BranchID,
		arg.Principal,
		arg.InterestRate,
		arg.CollateralValue,
		arg.CollateralCoverageRatio,
		arg.UpdatedBy,
	)
	var i Loan
	err := row.Scan(
		&i.ID,
		&i.MemberID,
		&i.BranchID,
		&i.Principal,
		&i.InterestRate,
		&i.CollateralValue,
		&i.CollateralCoverageRatio,
		&i.Status,
		&i.DisbursedAt,
		&i.UpdatedBy,
		&i.PreviousStatus,
		&i.IsDeleted,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getLoanByID = `-- name: GetLoanByID :one
SELECT id, member_id, branch_id, principal, interest_rate, collateral_value, collateral_coverage_ratio, status, disbursed_at, updated_by, previous_status, is_deleted, created_at, updated_at
FROM loans
WHERE id = $1 AND is_deleted = FALSE
`

func (q *Queries) GetLoanByID(ctx context.Context, id pgtype.UUID) (Loan, error) {
	row := q.db.QueryRow(ctx, getLoanByID, id)
	var i Loan
	err := row.Scan(
		&i.ID,
		&i.MemberID,
		&i.BranchID,
		&i.Principal,
		&i.InterestRate,
		&i.CollateralValue,
		&i.CollateralCoverageRatio,
		&i.Status,
		&i.DisbursedAt,
		&i.UpdatedBy,
		&i.PreviousStatus,
		&i.IsDeleted,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listLoansByBranch = `-- name: ListLoansByBranch :many
SELECT id, member_id, branch_id, principal, interest_rate, collateral_value, collateral_coverage_ratio, status, disbursed_at, updated_by, previous_status, is_deleted, created_at, updated_at
FROM loans
WHERE branch_id = $1
  AND is_deleted = FALSE
  AND ($2::timestamptz IS NULL OR created_at < $2 OR (created_at = $2 AND id < $3))
  AND ($5::loan_status IS NULL OR status = $5)
ORDER BY created_at DESC, id DESC
LIMIT $4
`

type ListLoansByBranchParams struct {
	BranchID     int64              `json:"branchId"`
	Column2      pgtype.Timestamptz `json:"column2"`
	ID           pgtype.UUID        `json:"id"`
	Limit        int32              `json:"limit"`
	StatusFilter NullLoanStatus     `json:"statusFilter"`
}

func (q *Queries) ListLoansByBranch(ctx context.Context, arg ListLoansByBranchParams) ([]Loan, error) {
	rows, err := q.db.Query(ctx, listLoansByBranch,
		arg.BranchID,
		arg.Column2,
		arg.ID,
		arg.Limit,
		arg.StatusFilter,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Loan
	for rows.Next() {
		var i Loan
		if err := rows.Scan(
			&i.ID,
			&i.MemberID,
			&i.BranchID,
			&i.Principal,
			&i.InterestRate,
			&i.CollateralValue,
			&i.CollateralCoverageRatio,
			&i.Status,
			&i.DisbursedAt,
			&i.UpdatedBy,
			&i.PreviousStatus,
			&i.IsDeleted,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listLoansByMember = `-- name: ListLoansByMember :many
SELECT id, member_id, branch_id, principal, interest_rate, collateral_value, collateral_coverage_ratio, status, disbursed_at, updated_by, previous_status, is_deleted, created_at, updated_at
FROM loans
WHERE member_id = $1
  AND is_deleted = FALSE
  AND ($2::timestamptz IS NULL OR created_at < $2 OR (created_at = $2 AND id < $3))
ORDER BY created_at DESC, id DESC
LIMIT $4
`

type ListLoansByMemberParams struct {
	MemberID pgtype.UUID        `json:"memberId"`
	Column2  pgtype.Timestamptz `json:"column2"`
	ID       pgtype.UUID        `json:"id"`
	Limit    int32              `json:"limit"`
}

func (q *Queries) ListLoansByMember(ctx context.Context, arg ListLoansByMemberParams) ([]Loan, error) {
	rows, err := q.db.Query(ctx, listLoansByMember,
		arg.MemberID,
		arg.Column2,
		arg.ID,
		arg.Limit,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Loan
	for rows.Next() {
		var i Loan
		if err := rows.Scan(
			&i.ID,
			&i.MemberID,
			&i.BranchID,
			&i.Principal,
			&i.InterestRate,
			&i.CollateralValue,
			&i.CollateralCoverageRatio,
			&i.Status,
			&i.DisbursedAt,
			&i.UpdatedBy,
			&i.PreviousStatus,
			&i.IsDeleted,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listLoansForDelinquencyUpdate = `-- name: ListLoansForDelinquencyUpdate :many
SELECT id, member_id, branch_id, principal, interest_rate, collateral_value, collateral_coverage_ratio, status, disbursed_at, updated_by, previous_status, is_deleted, created_at, updated_at
FROM loans
WHERE status IN ('active', 'delinquent')
  AND is_deleted = FALSE
ORDER BY created_at ASC, id ASC
LIMIT $1
FOR UPDATE SKIP LOCKED
`

func (q *Queries) ListLoansForDelinquencyUpdate(ctx context.Context, limit int32) ([]Loan, error) {
	rows, err := q.db.Query(ctx, listLoansForDelinquencyUpdate, limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Loan
	for rows.Next() {
		var i Loan
		if err := rows.Scan(
			&i.ID,
			&i.MemberID,
			&i.BranchID,
			&i.Principal,
			&i.InterestRate,
			&i.CollateralValue,
			&i.CollateralCoverageRatio,
			&i.Status,
			&i.DisbursedAt,
			&i.UpdatedBy,
			&i.PreviousStatus,
			&i.IsDeleted,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const lockLoanByID = `-- name: LockLoanByID :one
SELECT id, member_id, branch_id, principal, interest_rate, collateral_value, collateral_coverage_ratio, status, disbursed_at, updated_by, previous_status, is_deleted, created_at, updated_at
FROM loans
WHERE id = $1 AND is_deleted = FALSE
FOR UPDATE
`

func (q *Queries) LockLoanByID(ctx context.Context, id pgtype.UUID) (Loan, error) {
	row := q.db.QueryRow(ctx, lockLoanByID, id)
	var i Loan
	err := row.Scan(
		&i.ID,
		&i.MemberID,
		&i.BranchID,
		&i.Principal,
		&i.InterestRate,
		&i.CollateralValue,
		&i.CollateralCoverageRatio,
		&i.Status,
		&i.DisbursedAt,
		&i.UpdatedBy,
		&i.PreviousStatus,
		&i.IsDeleted,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const markLoanDisbursed = `-- name: MarkLoanDisbursed :one
UPDATE loans
SET previous_status = status,
    status = 'disbursed',
    disbursed_at = NOW(),
    updated_by = $2,
    updated_at = NOW()
WHERE id = $1 AND status = 'approved' AND is_deleted = FALSE
RETURNING id, member_id, branch_id, principal, interest_rate, collateral_value, collateral_coverage_ratio, status, disbursed_at, updated_by, previous_status, is_deleted, created_at, updated_at
`

type MarkLoanDisbursedParams struct {
	ID        pgtype.UUID `json:"id"`
	UpdatedBy pgtype.UUID `json:"updatedBy"`
}

func (q *Queries) MarkLoanDisbursed(ctx context.Context, arg MarkLoanDisbursedParams) (Loan, error) {
	row := q.db.QueryRow(ctx, markLoanDisbursed, arg.ID, arg.UpdatedBy)
	var i Loan
	err := row.Scan(
		&i.ID,
		&i.MemberID,
		&i.BranchID,
		&i.Principal,
		&i.InterestRate,
		&i.CollateralValue,
		&i.CollateralCoverageRatio,
		&i.Status,
		&i.DisbursedAt,
		&i.UpdatedBy,
		&i.PreviousStatus,
		&i.IsDeleted,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const softDeleteLoan = `-- name: SoftDeleteLoan :one
UPDATE loans
SET is_deleted = TRUE,
    updated_by = $2,
    updated_at = NOW()
WHERE id = $1 AND is_deleted = FALSE
RETURNING id, member_id, branch_id, principal, interest_rate, collateral_value, collateral_coverage_ratio, status, disbursed_at, updated_by, previous_status, is_deleted, created_at, updated_at
`

type SoftDeleteLoanParams struct {
	ID        pgtype.UUID `json:"id"`
	UpdatedBy pgtype.UUID `json:"updatedBy"`
}

func (q *Queries) SoftDeleteLoan(ctx context.Context, arg SoftDeleteLoanParams) (Loan, error) {
	row := q.db.QueryRow(ctx, softDeleteLoan, arg.ID, arg.UpdatedBy)
	var i Loan
	err := row.Scan(
		&i.ID,
		&i.MemberID,
		&i.BranchID,
		&i.Principal,
		&i.InterestRate,
		&i.CollateralValue,
		&i.CollateralCoverageRatio,
		&i.Status,
		&i.DisbursedAt,
		&i.UpdatedBy,
		&i.PreviousStatus,
		&i.IsDeleted,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const updateLoanCollateral = `-- name: UpdateLoanCollateral :one
UPDATE loans
SET collateral_value = $2,
    collateral_coverage_ratio = $3,
    updated_by = $4,
    updated_at = NOW()
WHERE id = $1 AND is_deleted = FALSE
RETURNING id, member_id, branch_id, principal, interest_rate, collateral_value, collateral_coverage_ratio, status, disbursed_at, updated_by, previous_status, is_deleted, created_at, updated_at
`

type UpdateLoanCollateralParams struct {
	ID                      pgtype.UUID    `json:"id"`
	CollateralValue         pgtype.Numeric `json:"collateralValue"`
	CollateralCoverageRatio pgtype.Numeric `json:"collateralCoverageRatio"`
	UpdatedBy               pgtype.UUID    `json:"updatedBy"`
}

func (q *Queries) UpdateLoanCollateral(ctx context.Context, arg UpdateLoanCollateralParams) (Loan, error) {
	row := q.db.QueryRow(ctx, updateLoanCollateral,
		arg.ID,
		arg.CollateralValue,
		arg.CollateralCoverageRatio,
		arg.UpdatedBy,
	)
	var i Loan
	err := row.Scan(
		&i.ID,
		&i.MemberID,
		&i.BranchID,
		&i.Principal,
		&i.InterestRate,
		&i.CollateralValue,
		&i.CollateralCoverageRatio,
		&i.Status,
		&i.DisbursedAt,
		&i.UpdatedBy,
		&i.PreviousStatus,
		&i.IsDeleted,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const updateLoanStatus = `-- name: UpdateLoanStatus :one
UPDATE loans
SET previous_status = status,
    status = $2,
    updated_by = $3,
    updated_at = NOW()
WHERE id = $1 AND is_deleted = FALSE
RETURNING id, member_id, branch_id, principal, interest_rate, collateral_value, collateral_coverage_ratio, status, disbursed_at, updated_by, previous_status, is_deleted, created_at, updated_at
`

type UpdateLoanStatusParams struct {
	ID        pgtype.UUID `json:"id"`
	Status    LoanStatus  `json:"status"`
	UpdatedBy pgtype.UUID `json:"updatedBy"`
}

func (q *Queries) UpdateLoanStatus(ctx context.Context, arg UpdateLoanStatusParams) (Loan, error) {
	row := q.db.QueryRow(ctx, updateLoanStatus, arg.ID, arg.Status, arg.UpdatedBy)
	var i Loan
	err := row.Scan(
		&i.ID,
		&i.MemberID,
		&i.BranchID,
		&i.Principal,
		&i.InterestRate,
		&i.CollateralValue,
		&i.CollateralCoverageRatio,
		&i.Status,
		&i.DisbursedAt,
		&i.UpdatedBy,
		&i.PreviousStatus,
		&i.IsDeleted,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
