// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package loansqlc

import (
	"database/sql/driver"
	"fmt"

	"github.com/jackc/pgx/v5/pgtype"
)

type CreditBalanceSource string

const (
	CreditBalanceSourceOverpayment CreditBalanceSource = "overpayment"
	CreditBalanceSourceRefund      CreditBalanceSource = "refund"
	CreditBalanceSourceAdjustment  CreditBalanceSource = "adjustment"
)

func (e *CreditBalanceSource) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = CreditBalanceSource(s)
	case string:
		*e = CreditBalanceSource(s)
	default:
		return fmt.Errorf("unsupported scan type for CreditBalanceSource: %T", src)
	}
	return nil
}

type NullCreditBalanceSource struct {
	CreditBalanceSource CreditBalanceSource `json:"creditBalanceSource"`
	Valid               bool                `json:"valid"` // Valid is true if CreditBalanceSource is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullCreditBalanceSource) Scan(value interface{}) error {
	if value == nil {
		ns.CreditBalanceSource, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.CreditBalanceSource.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullCreditBalanceSource) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.CreditBalanceSource), nil
}

type CreditBalanceStatus string

const (
	CreditBalanceStatusAvailable CreditBalanceStatus = "available"
	CreditBalanceStatusFrozen    CreditBalanceStatus = "frozen"
	CreditBalanceStatusWithdrawn CreditBalanceStatus = "withdrawn"
)

func (e *CreditBalanceStatus) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = CreditBalanceStatus(s)
	case string:
		*e = CreditBalanceStatus(s)
	default:
		return fmt.Errorf("unsupported scan type for CreditBalanceStatus: %T", src)
	}
	return nil
}

type NullCreditBalanceStatus struct {
	CreditBalanceStatus CreditBalanceStatus `json:"creditBalanceStatus"`
	Valid               bool                `json:"valid"` // Valid is true if CreditBalanceStatus is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullCreditBalanceStatus) Scan(value interface{}) error {
	if value == nil {
		ns.CreditBalanceStatus, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.CreditBalanceStatus.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullCreditBalanceStatus) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.CreditBalanceStatus), nil
}

type LoanStatus string

const (
	LoanStatusPending       LoanStatus = "pending"
	LoanStatusApproved      LoanStatus = "approved"
	LoanStatusRejected      LoanStatus = "rejected"
	LoanStatusDisbursed     LoanStatus = "disbursed"
	LoanStatusRestructuring LoanStatus = "restructuring"
	LoanStatusActive        LoanStatus = "active"
	LoanStatusDelinquent    LoanStatus = "delinquent"
	LoanStatusClosed        LoanStatus = "closed"
	LoanStatusWrittenOff    LoanStatus = "written_off"
	LoanStatusManualReview  LoanStatus = "manual_review"
)

func (e *LoanStatus) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = LoanStatus(s)
	case string:
		*e = LoanStatus(s)
	default:
		return fmt.Errorf("unsupported scan type for LoanStatus: %T", src)
	}
	return nil
}

type NullLoanStatus struct {
	LoanStatus LoanStatus `json:"loanStatus"`
	Valid      bool       `json:"valid"` // Valid is true if LoanStatus is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullLoanStatus) Scan(value interface{}) error {
	if value == nil {
		ns.LoanStatus, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.LoanStatus.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullLoanStatus) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.LoanStatus), nil
}

type LoanTransactionType string

const (
	LoanTransactionTypeDisbursement     LoanTransactionType = "disbursement"
	LoanTransactionTypeRepayment        LoanTransactionType = "repayment"
	LoanTransactionTypePenalty          LoanTransactionType = "penalty"
	LoanTransactionTypeReversal         LoanTransactionType = "reversal"
	LoanTransactionTypeCreditWithdrawal LoanTransactionType = "credit_withdrawal"
)

func (e *LoanTransactionType) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = LoanTransactionType(s)
	case string:
		*e = LoanTransactionType(s)
	default:
		return fmt.Errorf("unsupported scan type for LoanTransactionType: %T", src)
	}
	return nil
}

type NullLoanTransactionType struct {
	LoanTransactionType LoanTransactionType `json:"loanTransactionType"`
	Valid               bool                `json:"valid"` // Valid is true if LoanTransactionType is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullLoanTransactionType) Scan(value interface{}) error {
	if value == nil {
		ns.LoanTransactionType, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.LoanTransactionType.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullLoanTransactionType) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.LoanTransactionType), nil
}

type RepaymentScheduleStatus string

const (
	RepaymentScheduleStatusUpcoming   RepaymentScheduleStatus = "upcoming"
	RepaymentScheduleStatusDue        RepaymentScheduleStatus = "due"
	RepaymentScheduleStatusPaid       RepaymentScheduleStatus = "paid"
	RepaymentScheduleStatusMissed     RepaymentScheduleStatus = "missed"
	RepaymentScheduleStatusPartial    RepaymentScheduleStatus = "partial"
	RepaymentScheduleStatusSuperseded RepaymentScheduleStatus = "superseded"
)

func (e *RepaymentScheduleStatus) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = RepaymentScheduleStatus(s)
	case string:
		*e = RepaymentScheduleStatus(s)
	default:
		return fmt.Errorf("unsupported scan type for RepaymentScheduleStatus: %T", src)
	}
	return nil
}

type NullRepaymentScheduleStatus struct {
	RepaymentScheduleStatus RepaymentScheduleStatus `json:"repaymentScheduleStatus"`
	Valid                   bool                    `json:"valid"` // Valid is true if RepaymentScheduleStatus is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullRepaymentScheduleStatus) Scan(value interface{}) error {
	if value == nil {
		ns.RepaymentScheduleStatus, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.RepaymentScheduleStatus.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullRepaymentScheduleStatus) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.RepaymentScheduleStatus), nil
}

type CreditBalance struct {
	ID             pgtype.UUID         `json:"id"`
	MemberID       pgtype.UUID         `json:"memberId"`
	LoanID         pgtype.UUID         `json:"loanId"`
	Amount         pgtype.Numeric      `json:"amount"`
	Source         CreditBalanceSource `json:"source"`
	Status         CreditBalanceStatus `json:"status"`
	CreatedAt      pgtype.Timestamptz  `json:"createdAt"`
	LastActivityAt pgtype.Timestamptz  `json:"lastActivityAt"`
}

type Loan struct {
	ID                      pgtype.UUID        `json:"id"`
	MemberID                pgtype.UUID        `json:"memberId"`
	BranchID                int64              `json:"branchId"`
	Principal               pgtype.Numeric     `json:"principal"`
	InterestRate            pgtype.Numeric     `json:"interestRate"`
	CollateralValue         pgtype.Numeric     `json:"collateralValue"`
	CollateralCoverageRatio pgtype.Numeric     `json:"collateralCoverageRatio"`
	Status                  LoanStatus         `json:"status"`
	DisbursedAt             pgtype.Timestamptz `json:"disbursedAt"`
	UpdatedBy               pgtype.UUID        `json:"updatedBy"`
	PreviousStatus          NullLoanStatus     `json:"previousStatus"`
	IsDeleted               bool               `json:"isDeleted"`
	CreatedAt               pgtype.Timestamptz `json:"createdAt"`
	UpdatedAt               pgtype.Timestamptz `json:"updatedAt"`
}

type LoanAuditTrail struct {
	ID                pgtype.UUID        `json:"id"`
	LoanID            pgtype.UUID        `json:"loanId"`
	FieldChanged      string             `json:"fieldChanged"`
	PreviousValue     pgtype.Text        `json:"previousValue"`
	NewValue          string             `json:"newValue"`
	ChangedBy         pgtype.UUID        `json:"changedBy"`
	ChangeReason      string             `json:"changeReason"`
	ApprovalReference pgtype.Text        `json:"approvalReference"`
	CreatedAt         pgtype.Timestamptz `json:"createdAt"`
}

type LoanTransaction struct {
	ID                          pgtype.UUID         `json:"id"`
	LoanID                      pgtype.UUID         `json:"loanId"`
	Type                        LoanTransactionType `json:"type"`
	Amount                      pgtype.Numeric      `json:"amount"`
	ReferenceID                 pgtype.UUID         `json:"referenceId"`
	PaymentGatewayTransactionID pgtype.Text         `json:"paymentGatewayTransactionId"`
	AllocationBreakdown         []byte              `json:"allocationBreakdown"`
	CreatedAt                   pgtype.Timestamptz  `json:"createdAt"`
	CreatedBy                   pgtype.UUID         `json:"createdBy"`
}

type RepaymentSchedule struct {
	ID            pgtype.UUID             `json:"id"`
	LoanID        pgtype.UUID             `json:"loanId"`
	InstallmentNo int32                   `json:"installmentNo"`
	DueDate       pgtype.Date             `json:"dueDate"`
	AmountDue     pgtype.Numeric          `json:"amountDue"`
	Status        RepaymentScheduleStatus `json:"status"`
	CreatedAt     pgtype.Timestamptz      `json:"createdAt"`
	UpdatedAt     pgtype.Timestamptz      `json:"updatedAt"`
}
