// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package loansqlc

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

type Querier interface {
	CountApprovedGuarantors(ctx context.Context, loanID pgtype.UUID) (int64, error)
	CreateCreditBalance(ctx context.Context, arg CreateCreditBalanceParams) (CreditBalance, error)
	CreateLoan(ctx context.Context, arg CreateLoanParams) (CreateLoanRow, error)
	CreateLoanGuarantor(ctx context.Context, arg CreateLoanGuarantorParams) (LoanGuarantor, error)
	CreateRepaymentSchedule(ctx context.Context, arg CreateRepaymentScheduleParams) (RepaymentSchedule, error)
	GetCreditBalanceByID(ctx context.Context, id pgtype.UUID) (CreditBalance, error)
	GetLoanByID(ctx context.Context, id pgtype.UUID) (GetLoanByIDRow, error)
	GetLoanDisbursement(ctx context.Context, loanID pgtype.UUID) (LoanTransaction, error)
	GetLoanGuarantor(ctx context.Context, arg GetLoanGuarantorParams) (LoanGuarantor, error)
	GetLoanTransactionByGatewayID(ctx context.Context, arg GetLoanTransactionByGatewayIDParams) (LoanTransaction, error)
	GetLoanTransactionByReference(ctx context.Context, arg GetLoanTransactionByReferenceParams) (LoanTransaction, error)
	GetTotalGuaranteedAmount(ctx context.Context, loanID pgtype.UUID) (interface{}, error)
	InsertLoanAuditTrail(ctx context.Context, arg InsertLoanAuditTrailParams) (LoanAuditTrail, error)
	InsertLoanTransaction(ctx context.Context, arg InsertLoanTransactionParams) (LoanTransaction, error)
	ListCreditBalancesByMember(ctx context.Context, arg ListCreditBalancesByMemberParams) ([]CreditBalance, error)
	ListDueRepaymentSchedules(ctx context.Context, dueDate pgtype.Date) ([]RepaymentSchedule, error)
	ListGuarantorLoans(ctx context.Context, guarantorID pgtype.UUID) ([]ListGuarantorLoansRow, error)
	ListLoanAuditTrail(ctx context.Context, arg ListLoanAuditTrailParams) ([]LoanAuditTrail, error)
	ListLoanGuarantors(ctx context.Context, loanID pgtype.UUID) ([]LoanGuarantor, error)
	ListLoanTransactions(ctx context.Context, arg ListLoanTransactionsParams) ([]LoanTransaction, error)
	ListLoansByBranch(ctx context.Context, arg ListLoansByBranchParams) ([]ListLoansByBranchRow, error)
	ListLoansByMember(ctx context.Context, arg ListLoansByMemberParams) ([]ListLoansByMemberRow, error)
	ListLoansForDelinquencyUpdate(ctx context.Context, limit int32) ([]ListLoansForDelinquencyUpdateRow, error)
	ListRepaymentSchedulesByLoan(ctx context.Context, loanID pgtype.UUID) ([]RepaymentSchedule, error)
	LockCreditBalanceByID(ctx context.Context, id pgtype.UUID) (CreditBalance, error)
	LockGuarantor(ctx context.Context, arg LockGuarantorParams) (LoanGuarantor, error)
	LockLoanByID(ctx context.Context, id pgtype.UUID) (LockLoanByIDRow, error)
	LockRepaymentSchedulesByLoan(ctx context.Context, loanID pgtype.UUID) ([]RepaymentSchedule, error)
	MarkLoanDisbursed(ctx context.Context, arg MarkLoanDisbursedParams) (MarkLoanDisbursedRow, error)
	SoftDeleteLoan(ctx context.Context, arg SoftDeleteLoanParams) (SoftDeleteLoanRow, error)
	SumLoanTransactionsByType(ctx context.Context, arg SumLoanTransactionsByTypeParams) (pgtype.Numeric, error)
	SupersedeRepaymentSchedules(ctx context.Context, loanID pgtype.UUID) error
	UpdateCreditBalanceStatus(ctx context.Context, arg UpdateCreditBalanceStatusParams) (CreditBalance, error)
	UpdateGuarantorStatus(ctx context.Context, arg UpdateGuarantorStatusParams) (LoanGuarantor, error)
	UpdateLoanStatus(ctx context.Context, arg UpdateLoanStatusParams) (UpdateLoanStatusRow, error)
	UpdateRepaymentScheduleStatus(ctx context.Context, arg UpdateRepaymentScheduleStatusParams) (RepaymentSchedule, error)
}

var _ Querier = (*Queries)(nil)
