// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package loansqlc

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

type Querier interface {
	CreateCreditBalance(ctx context.Context, arg CreateCreditBalanceParams) (CreditBalance, error)
	CreateLoan(ctx context.Context, arg CreateLoanParams) (Loan, error)
	CreateRepaymentSchedule(ctx context.Context, arg CreateRepaymentScheduleParams) (RepaymentSchedule, error)
	GetCreditBalanceByID(ctx context.Context, id pgtype.UUID) (CreditBalance, error)
	GetLoanByID(ctx context.Context, id pgtype.UUID) (Loan, error)
	GetLoanDisbursement(ctx context.Context, loanID pgtype.UUID) (LoanTransaction, error)
	GetLoanTransactionByGatewayID(ctx context.Context, arg GetLoanTransactionByGatewayIDParams) (LoanTransaction, error)
	GetLoanTransactionByReference(ctx context.Context, arg GetLoanTransactionByReferenceParams) (LoanTransaction, error)
	InsertLoanAuditTrail(ctx context.Context, arg InsertLoanAuditTrailParams) (LoanAuditTrail, error)
	InsertLoanTransaction(ctx context.Context, arg InsertLoanTransactionParams) (LoanTransaction, error)
	ListCreditBalancesByMember(ctx context.Context, arg ListCreditBalancesByMemberParams) ([]CreditBalance, error)
	ListDueRepaymentSchedules(ctx context.Context, dueDate pgtype.Date) ([]RepaymentSchedule, error)
	ListLoanAuditTrail(ctx context.Context, arg ListLoanAuditTrailParams) ([]LoanAuditTrail, error)
	ListLoanTransactions(ctx context.Context, arg ListLoanTransactionsParams) ([]LoanTransaction, error)
	ListLoansByBranch(ctx context.Context, arg ListLoansByBranchParams) ([]Loan, error)
	ListLoansByMember(ctx context.Context, arg ListLoansByMemberParams) ([]Loan, error)
	ListLoansForDelinquencyUpdate(ctx context.Context, limit int32) ([]Loan, error)
	ListRepaymentSchedulesByLoan(ctx context.Context, loanID pgtype.UUID) ([]RepaymentSchedule, error)
	LockCreditBalanceByID(ctx context.Context, id pgtype.UUID) (CreditBalance, error)
	LockLoanByID(ctx context.Context, id pgtype.UUID) (Loan, error)
	LockRepaymentSchedulesByLoan(ctx context.Context, loanID pgtype.UUID) ([]RepaymentSchedule, error)
	MarkLoanDisbursed(ctx context.Context, arg MarkLoanDisbursedParams) (Loan, error)
	SoftDeleteLoan(ctx context.Context, arg SoftDeleteLoanParams) (Loan, error)
	SumLoanTransactionsByType(ctx context.Context, arg SumLoanTransactionsByTypeParams) (pgtype.Numeric, error)
	SupersedeRepaymentSchedules(ctx context.Context, loanID pgtype.UUID) error
	UpdateCreditBalanceStatus(ctx context.Context, arg UpdateCreditBalanceStatusParams) (CreditBalance, error)
	UpdateLoanCollateral(ctx context.Context, arg UpdateLoanCollateralParams) (Loan, error)
	UpdateLoanStatus(ctx context.Context, arg UpdateLoanStatusParams) (Loan, error)
	UpdateRepaymentScheduleStatus(ctx context.Context, arg UpdateRepaymentScheduleStatusParams) (RepaymentSchedule, error)
}

var _ Querier = (*Queries)(nil)
