// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: repayment_schedules.sql

package loansqlc

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createRepaymentSchedule = `-- name: CreateRepaymentSchedule :one
INSERT INTO repayment_schedules (loan_id, installment_no, due_date, amount_due, status)
VALUES ($1, $2, $3, $4, $5)
ON CONFLICT (loan_id, installment_no, status) DO NOTHING
RETURNING id, loan_id, installment_no, due_date, amount_due, status, created_at, updated_at
`

type CreateRepaymentScheduleParams struct {
	LoanID        pgtype.UUID             `json:"loanId"`
	InstallmentNo int32                   `json:"installmentNo"`
	DueDate       pgtype.Date             `json:"dueDate"`
	AmountDue     pgtype.Numeric          `json:"amountDue"`
	Status        RepaymentScheduleStatus `json:"status"`
}

func (q *Queries) CreateRepaymentSchedule(ctx context.Context, arg CreateRepaymentScheduleParams) (RepaymentSchedule, error) {
	row := q.db.QueryRow(ctx, createRepaymentSchedule,
		arg.LoanID,
		arg.InstallmentNo,
		arg.DueDate,
		arg.AmountDue,
		arg.Status,
	)
	var i RepaymentSchedule
	err := row.Scan(
		&i.ID,
		&i.LoanID,
		&i.InstallmentNo,
		&i.DueDate,
		&i.AmountDue,
		&i.Status,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listDueRepaymentSchedules = `-- name: ListDueRepaymentSchedules :many
SELECT id, loan_id, installment_no, due_date, amount_due, status, created_at, updated_at
FROM repayment_schedules
WHERE due_date <= $1 AND status IN ('due', 'missed')
ORDER BY due_date ASC, loan_id ASC
`

func (q *Queries) ListDueRepaymentSchedules(ctx context.Context, dueDate pgtype.Date) ([]RepaymentSchedule, error) {
	rows, err := q.db.Query(ctx, listDueRepaymentSchedules, dueDate)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []RepaymentSchedule
	for rows.Next() {
		var i RepaymentSchedule
		if err := rows.Scan(
			&i.ID,
			&i.LoanID,
			&i.InstallmentNo,
			&i.DueDate,
			&i.AmountDue,
			&i.Status,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listRepaymentSchedulesByLoan = `-- name: ListRepaymentSchedulesByLoan :many
SELECT id, loan_id, installment_no, due_date, amount_due, status, created_at, updated_at
FROM repayment_schedules
WHERE loan_id = $1
ORDER BY installment_no ASC
`

func (q *Queries) ListRepaymentSchedulesByLoan(ctx context.Context, loanID pgtype.UUID) ([]RepaymentSchedule, error) {
	rows, err := q.db.Query(ctx, listRepaymentSchedulesByLoan, loanID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []RepaymentSchedule
	for rows.Next() {
		var i RepaymentSchedule
		if err := rows.Scan(
			&i.ID,
			&i.LoanID,
			&i.InstallmentNo,
			&i.DueDate,
			&i.AmountDue,
			&i.Status,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const lockRepaymentSchedulesByLoan = `-- name: LockRepaymentSchedulesByLoan :many
SELECT id, loan_id, installment_no, due_date, amount_due, status, created_at, updated_at
FROM repayment_schedules
WHERE loan_id = $1
ORDER BY installment_no ASC
FOR UPDATE
`

func (q *Queries) LockRepaymentSchedulesByLoan(ctx context.Context, loanID pgtype.UUID) ([]RepaymentSchedule, error) {
	rows, err := q.db.Query(ctx, lockRepaymentSchedulesByLoan, loanID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []RepaymentSchedule
	for rows.Next() {
		var i RepaymentSchedule
		if err := rows.Scan(
			&i.ID,
			&i.LoanID,
			&i.InstallmentNo,
			&i.DueDate,
			&i.AmountDue,
			&i.Status,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const supersedeRepaymentSchedules = `-- name: SupersedeRepaymentSchedules :exec
UPDATE repayment_schedules
SET status = 'superseded',
    updated_at = NOW()
WHERE loan_id = $1 AND status <> 'superseded'
`

func (q *Queries) SupersedeRepaymentSchedules(ctx context.Context, loanID pgtype.UUID) error {
	_, err := q.db.Exec(ctx, supersedeRepaymentSchedules, loanID)
	return err
}

const updateRepaymentScheduleStatus = `-- name: UpdateRepaymentScheduleStatus :one
UPDATE repayment_schedules
SET status = $2,
    updated_at = NOW()
WHERE id = $1
RETURNING id, loan_id, installment_no, due_date, amount_due, status, created_at, updated_at
`

type UpdateRepaymentScheduleStatusParams struct {
	ID     pgtype.UUID             `json:"id"`
	Status RepaymentScheduleStatus `json:"status"`
}

func (q *Queries) UpdateRepaymentScheduleStatus(ctx context.Context, arg UpdateRepaymentScheduleStatusParams) (RepaymentSchedule, error) {
	row := q.db.QueryRow(ctx, updateRepaymentScheduleStatus, arg.ID, arg.Status)
	var i RepaymentSchedule
	err := row.Scan(
		&i.ID,
		&i.LoanID,
		&i.InstallmentNo,
		&i.DueDate,
		&i.AmountDue,
		&i.Status,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
