// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: transactions.sql

package loansqlc

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const getLoanDisbursement = `-- name: GetLoanDisbursement :one
SELECT id, loan_id, type, amount, reference_id, payment_gateway_transaction_id, allocation_breakdown, created_at, created_by
FROM loan_transactions
WHERE loan_id = $1 AND type = 'disbursement'
`

func (q *Queries) GetLoanDisbursement(ctx context.Context, loanID pgtype.UUID) (LoanTransaction, error) {
	row := q.db.QueryRow(ctx, getLoanDisbursement, loanID)
	var i LoanTransaction
	err := row.Scan(
		&i.ID,
		&i.LoanID,
		&i.Type,
		&i.Amount,
		&i.ReferenceID,
		&i.PaymentGatewayTransactionID,
		&i.AllocationBreakdown,
		&i.CreatedAt,
		&i.CreatedBy,
	)
	return i, err
}

const getLoanTransactionByGatewayID = `-- name: GetLoanTransactionByGatewayID :one
SELECT id, loan_id, type, amount, reference_id, payment_gateway_transaction_id, allocation_breakdown, created_at, created_by
FROM loan_transactions
WHERE loan_id = $1 AND payment_gateway_transaction_id = $2
`

type GetLoanTransactionByGatewayIDParams struct {
	LoanID                      pgtype.UUID `json:"loanId"`
	PaymentGatewayTransactionID pgtype.Text `json:"paymentGatewayTransactionId"`
}

func (q *Queries) GetLoanTransactionByGatewayID(ctx context.Context, arg GetLoanTransactionByGatewayIDParams) (LoanTransaction, error) {
	row := q.db.QueryRow(ctx, getLoanTransactionByGatewayID, arg.LoanID, arg.PaymentGatewayTransactionID)
	var i LoanTransaction
	err := row.Scan(
		&i.ID,
		&i.LoanID,
		&i.Type,
		&i.Amount,
		&i.ReferenceID,
		&i.PaymentGatewayTransactionID,
		&i.AllocationBreakdown,
		&i.CreatedAt,
		&i.CreatedBy,
	)
	return i, err
}

const getLoanTransactionByReference = `-- name: GetLoanTransactionByReference :one
SELECT id, loan_id, type, amount, reference_id, payment_gateway_transaction_id, allocation_breakdown, created_at, created_by
FROM loan_transactions
WHERE loan_id = $1 AND reference_id = $2 AND type = $3
`

type GetLoanTransactionByReferenceParams struct {
	LoanID      pgtype.UUID         `json:"loanId"`
	ReferenceID pgtype.UUID         `json:"referenceId"`
	Type        LoanTransactionType `json:"type"`
}

func (q *Queries) GetLoanTransactionByReference(ctx context.Context, arg GetLoanTransactionByReferenceParams) (LoanTransaction, error) {
	row := q.db.QueryRow(ctx, getLoanTransactionByReference, arg.LoanID, arg.ReferenceID, arg.Type)
	var i LoanTransaction
	err := row.Scan(
		&i.ID,
		&i.LoanID,
		&i.Type,
		&i.Amount,
		&i.ReferenceID,
		&i.PaymentGatewayTransactionID,
		&i.AllocationBreakdown,
		&i.CreatedAt,
		&i.CreatedBy,
	)
	return i, err
}

const insertLoanTransaction = `-- name: InsertLoanTransaction :one
INSERT INTO loan_transactions (loan_id, type, amount, reference_id, payment_gateway_transaction_id, allocation_breakdown, created_by)
VALUES ($1, $2, $3, $4, $5, $6, $7)
ON CONFLICT DO NOTHING
RETURNING id, loan_id, type, amount, reference_id, payment_gateway_transaction_id, allocation_breakdown, created_at, created_by
`

type InsertLoanTransactionParams struct {
	LoanID                      pgtype.UUID         `json:"loanId"`
	Type                        LoanTransactionType `json:"type"`
	Amount                      pgtype.Numeric      `json:"amount"`
	ReferenceID                 pgtype.UUID         `json:"referenceId"`
	PaymentGatewayTransactionID pgtype.Text         `json:"paymentGatewayTransactionId"`
	AllocationBreakdown         []byte              `json:"allocationBreakdown"`
	CreatedBy                   pgtype.UUID         `json:"createdBy"`
}

func (q *Queries) InsertLoanTransaction(ctx context.Context, arg InsertLoanTransactionParams) (LoanTransaction, error) {
	row := q.db.QueryRow(ctx, insertLoanTransaction,
		arg.LoanID,
		arg.Type,
		arg.Amount,
		arg.ReferenceID,
		arg.PaymentGatewayTransactionID,
		arg.AllocationBreakdown,
		arg.CreatedBy,
	)
	var i LoanTransaction
	err := row.Scan(
		&i.ID,
		&i.LoanID,
		&i.Type,
		&i.Amount,
		&i.ReferenceID,
		&i.PaymentGatewayTransactionID,
		&i.AllocationBreakdown,
		&i.CreatedAt,
		&i.CreatedBy,
	)
	return i, err
}

const listLoanTransactions = `-- name: ListLoanTransactions :many
SELECT id, loan_id, type, amount, reference_id, payment_gateway_transaction_id, allocation_breakdown, created_at, created_by
FROM loan_transactions
WHERE loan_id = $1
  AND ($2::timestamptz IS NULL OR created_at < $2 OR (created_at = $2 AND id < $3))
ORDER BY created_at DESC, id DESC
LIMIT $4
`

type ListLoanTransactionsParams struct {
	LoanID  pgtype.UUID        `json:"loanId"`
	Column2 pgtype.Timestamptz `json:"column2"`
	ID      pgtype.UUID        `json:"id"`
	Limit   int32              `json:"limit"`
}

func (q *Queries) ListLoanTransactions(ctx context.Context, arg ListLoanTransactionsParams) ([]LoanTransaction, error) {
	rows, err := q.db.Query(ctx, listLoanTransactions,
		arg.LoanID,
		arg.Column2,
		arg.ID,
		arg.Limit,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []LoanTransaction
	for rows.Next() {
		var i LoanTransaction
		if err := rows.Scan(
			&i.ID,
			&i.LoanID,
			&i.Type,
			&i.Amount,
			&i.ReferenceID,
			&i.PaymentGatewayTransactionID,
			&i.AllocationBreakdown,
			&i.CreatedAt,
			&i.CreatedBy,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const sumLoanTransactionsByType = `-- name: SumLoanTransactionsByType :one
SELECT COALESCE(SUM(amount), 0)::numeric AS total
FROM loan_transactions
WHERE loan_id = $1 AND type = $2
`

type SumLoanTransactionsByTypeParams struct {
	LoanID pgtype.UUID         `json:"loanId"`
	Type   LoanTransactionType `json:"type"`
}

func (q *Queries) SumLoanTransactionsByType(ctx context.Context, arg SumLoanTransactionsByTypeParams) (pgtype.Numeric, error) {
	row := q.db.QueryRow(ctx, sumLoanTransactionsByType, arg.LoanID, arg.Type)
	var total pgtype.Numeric
	err := row.Scan(&total)
	return total, err
}
