// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: allocations.sql

package contributionsqlc

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const getContributionAllocationByID = `-- name: GetContributionAllocationByID :one
SELECT id, receipt_id, type, target_id, amount, status, authoritative_reference_id, external_reference, failure_reason, created_at, updated_at
FROM contribution_allocations
WHERE id = $1
`

func (q *Queries) GetContributionAllocationByID(ctx context.Context, id pgtype.UUID) (ContributionAllocation, error) {
	row := q.db.QueryRow(ctx, getContributionAllocationByID, id)
	var i ContributionAllocation
	err := row.Scan(
		&i.ID,
		&i.ReceiptID,
		&i.Type,
		&i.TargetID,
		&i.Amount,
		&i.Status,
		&i.AuthoritativeReferenceID,
		&i.ExternalReference,
		&i.FailureReason,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const insertContributionAllocation = `-- name: InsertContributionAllocation :one
INSERT INTO contribution_allocations (
    receipt_id,
    type,
    target_id,
    amount,
    status
) VALUES (
    $1, $2, $3, $4, 'pending'
)
ON CONFLICT DO NOTHING
RETURNING id, receipt_id, type, target_id, amount, status, authoritative_reference_id, external_reference, failure_reason, created_at, updated_at
`

type InsertContributionAllocationParams struct {
	ReceiptID pgtype.UUID                `json:"receiptId"`
	Type      ContributionAllocationType `json:"type"`
	TargetID  pgtype.UUID                `json:"targetId"`
	Amount    pgtype.Numeric             `json:"amount"`
}

func (q *Queries) InsertContributionAllocation(ctx context.Context, arg InsertContributionAllocationParams) (ContributionAllocation, error) {
	row := q.db.QueryRow(ctx, insertContributionAllocation,
		arg.ReceiptID,
		arg.Type,
		arg.TargetID,
		arg.Amount,
	)
	var i ContributionAllocation
	err := row.Scan(
		&i.ID,
		&i.ReceiptID,
		&i.Type,
		&i.TargetID,
		&i.Amount,
		&i.Status,
		&i.AuthoritativeReferenceID,
		&i.ExternalReference,
		&i.FailureReason,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listContributionAllocationsByReceipt = `-- name: ListContributionAllocationsByReceipt :many
SELECT id, receipt_id, type, target_id, amount, status, authoritative_reference_id, external_reference, failure_reason, created_at, updated_at
FROM contribution_allocations
WHERE receipt_id = $1
ORDER BY created_at ASC, id ASC
`

func (q *Queries) ListContributionAllocationsByReceipt(ctx context.Context, receiptID pgtype.UUID) ([]ContributionAllocation, error) {
	rows, err := q.db.Query(ctx, listContributionAllocationsByReceipt, receiptID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ContributionAllocation
	for rows.Next() {
		var i ContributionAllocation
		if err := rows.Scan(
			&i.ID,
			&i.ReceiptID,
			&i.Type,
			&i.TargetID,
			&i.Amount,
			&i.Status,
			&i.AuthoritativeReferenceID,
			&i.ExternalReference,
			&i.FailureReason,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const lockContributionAllocationsByReceipt = `-- name: LockContributionAllocationsByReceipt :many
SELECT id, receipt_id, type, target_id, amount, status, authoritative_reference_id, external_reference, failure_reason, created_at, updated_at
FROM contribution_allocations
WHERE receipt_id = $1
ORDER BY created_at ASC, id ASC
FOR UPDATE
`

func (q *Queries) LockContributionAllocationsByReceipt(ctx context.Context, receiptID pgtype.UUID) ([]ContributionAllocation, error) {
	rows, err := q.db.Query(ctx, lockContributionAllocationsByReceipt, receiptID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ContributionAllocation
	for rows.Next() {
		var i ContributionAllocation
		if err := rows.Scan(
			&i.ID,
			&i.ReceiptID,
			&i.Type,
			&i.TargetID,
			&i.Amount,
			&i.Status,
			&i.AuthoritativeReferenceID,
			&i.ExternalReference,
			&i.FailureReason,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateContributionAllocationCompleted = `-- name: UpdateContributionAllocationCompleted :one
UPDATE contribution_allocations
SET status = 'completed',
    authoritative_reference_id = $2,
    external_reference = $3,
    failure_reason = NULL,
    updated_at = NOW()
WHERE id = $1
RETURNING id, receipt_id, type, target_id, amount, status, authoritative_reference_id, external_reference, failure_reason, created_at, updated_at
`

type UpdateContributionAllocationCompletedParams struct {
	ID                       pgtype.UUID `json:"id"`
	AuthoritativeReferenceID pgtype.UUID `json:"authoritativeReferenceId"`
	ExternalReference        pgtype.Text `json:"externalReference"`
}

func (q *Queries) UpdateContributionAllocationCompleted(ctx context.Context, arg UpdateContributionAllocationCompletedParams) (ContributionAllocation, error) {
	row := q.db.QueryRow(ctx, updateContributionAllocationCompleted, arg.ID, arg.AuthoritativeReferenceID, arg.ExternalReference)
	var i ContributionAllocation
	err := row.Scan(
		&i.ID,
		&i.ReceiptID,
		&i.Type,
		&i.TargetID,
		&i.Amount,
		&i.Status,
		&i.AuthoritativeReferenceID,
		&i.ExternalReference,
		&i.FailureReason,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const updateContributionAllocationFailed = `-- name: UpdateContributionAllocationFailed :one
UPDATE contribution_allocations
SET status = 'failed',
    failure_reason = $2,
    updated_at = NOW()
WHERE id = $1
RETURNING id, receipt_id, type, target_id, amount, status, authoritative_reference_id, external_reference, failure_reason, created_at, updated_at
`

type UpdateContributionAllocationFailedParams struct {
	ID            pgtype.UUID `json:"id"`
	FailureReason pgtype.Text `json:"failureReason"`
}

func (q *Queries) UpdateContributionAllocationFailed(ctx context.Context, arg UpdateContributionAllocationFailedParams) (ContributionAllocation, error) {
	row := q.db.QueryRow(ctx, updateContributionAllocationFailed, arg.ID, arg.FailureReason)
	var i ContributionAllocation
	err := row.Scan(
		&i.ID,
		&i.ReceiptID,
		&i.Type,
		&i.TargetID,
		&i.Amount,
		&i.Status,
		&i.AuthoritativeReferenceID,
		&i.ExternalReference,
		&i.FailureReason,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
