// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: cash.sql

package contributionsqlc

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const acceptCashHandover = `-- name: AcceptCashHandover :one
UPDATE cashier_sessions
SET status = 'handed_over',
    handed_over_at = NOW(),
    handed_over_to = $2,
    updated_at = NOW()
WHERE id = $1 AND status = 'closed'
RETURNING id, branch_id, cashier_id, status, expected_amount, counted_amount, variance, variance_reason, opened_at, closed_at, closed_by, handed_over_at, handed_over_to, deposited_at, created_at, updated_at
`

type AcceptCashHandoverParams struct {
	ID           pgtype.UUID `json:"id"`
	HandedOverTo pgtype.UUID `json:"handedOverTo"`
}

func (q *Queries) AcceptCashHandover(ctx context.Context, arg AcceptCashHandoverParams) (CashierSession, error) {
	row := q.db.QueryRow(ctx, acceptCashHandover, arg.ID, arg.HandedOverTo)
	var i CashierSession
	err := row.Scan(
		&i.ID,
		&i.BranchID,
		&i.CashierID,
		&i.Status,
		&i.ExpectedAmount,
		&i.CountedAmount,
		&i.Variance,
		&i.VarianceReason,
		&i.OpenedAt,
		&i.ClosedAt,
		&i.ClosedBy,
		&i.HandedOverAt,
		&i.HandedOverTo,
		&i.DepositedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const closeCashierSession = `-- name: CloseCashierSession :one
UPDATE cashier_sessions
SET status = 'closed',
    expected_amount = $2,
    counted_amount = $3,
    variance = $3::NUMERIC(19,4) - $2::NUMERIC(19,4),
    variance_reason = $4,
    closed_at = NOW(),
    closed_by = $5,
    updated_at = NOW()
WHERE id = $1 AND status = 'open'
RETURNING id, branch_id, cashier_id, status, expected_amount, counted_amount, variance, variance_reason, opened_at, closed_at, closed_by, handed_over_at, handed_over_to, deposited_at, created_at, updated_at
`

type CloseCashierSessionParams struct {
	ID             pgtype.UUID    `json:"id"`
	ExpectedAmount pgtype.Numeric `json:"expectedAmount"`
	CountedAmount  pgtype.Numeric `json:"countedAmount"`
	VarianceReason pgtype.Text    `json:"varianceReason"`
	ClosedBy       pgtype.UUID    `json:"closedBy"`
}

func (q *Queries) CloseCashierSession(ctx context.Context, arg CloseCashierSessionParams) (CashierSession, error) {
	row := q.db.QueryRow(ctx, closeCashierSession,
		arg.ID,
		arg.ExpectedAmount,
		arg.CountedAmount,
		arg.VarianceReason,
		arg.ClosedBy,
	)
	var i CashierSession
	err := row.Scan(
		&i.ID,
		&i.BranchID,
		&i.CashierID,
		&i.Status,
		&i.ExpectedAmount,
		&i.CountedAmount,
		&i.Variance,
		&i.VarianceReason,
		&i.OpenedAt,
		&i.ClosedAt,
		&i.ClosedBy,
		&i.HandedOverAt,
		&i.HandedOverTo,
		&i.DepositedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getCashDepositByBankReference = `-- name: GetCashDepositByBankReference :one
SELECT id, branch_id, amount, bank_reference, status, recorded_by, recorded_at, verified_by, verified_at, created_at, updated_at
FROM cash_deposits
WHERE bank_reference = $1
`

func (q *Queries) GetCashDepositByBankReference(ctx context.Context, bankReference string) (CashDeposit, error) {
	row := q.db.QueryRow(ctx, getCashDepositByBankReference, bankReference)
	var i CashDeposit
	err := row.Scan(
		&i.ID,
		&i.BranchID,
		&i.Amount,
		&i.BankReference,
		&i.Status,
		&i.RecordedBy,
		&i.RecordedAt,
		&i.VerifiedBy,
		&i.VerifiedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getCashDepositByID = `-- name: GetCashDepositByID :one
SELECT id, branch_id, amount, bank_reference, status, recorded_by, recorded_at, verified_by, verified_at, created_at, updated_at
FROM cash_deposits
WHERE id = $1
`

func (q *Queries) GetCashDepositByID(ctx context.Context, id pgtype.UUID) (CashDeposit, error) {
	row := q.db.QueryRow(ctx, getCashDepositByID, id)
	var i CashDeposit
	err := row.Scan(
		&i.ID,
		&i.BranchID,
		&i.Amount,
		&i.BankReference,
		&i.Status,
		&i.RecordedBy,
		&i.RecordedAt,
		&i.VerifiedBy,
		&i.VerifiedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getOpenCashierSession = `-- name: GetOpenCashierSession :one
SELECT id, branch_id, cashier_id, status, expected_amount, counted_amount, variance, variance_reason, opened_at, closed_at, closed_by, handed_over_at, handed_over_to, deposited_at, created_at, updated_at
FROM cashier_sessions
WHERE cashier_id = $1 AND status = 'open'
`

func (q *Queries) GetOpenCashierSession(ctx context.Context, cashierID pgtype.UUID) (CashierSession, error) {
	row := q.db.QueryRow(ctx, getOpenCashierSession, cashierID)
	var i CashierSession
	err := row.Scan(
		&i.ID,
		&i.BranchID,
		&i.CashierID,
		&i.Status,
		&i.ExpectedAmount,
		&i.CountedAmount,
		&i.Variance,
		&i.VarianceReason,
		&i.OpenedAt,
		&i.ClosedAt,
		&i.ClosedBy,
		&i.HandedOverAt,
		&i.HandedOverTo,
		&i.DepositedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const insertCashDeposit = `-- name: InsertCashDeposit :one
INSERT INTO cash_deposits (branch_id, amount, bank_reference, recorded_by)
VALUES ($1, $2, $3, $4)
ON CONFLICT DO NOTHING
RETURNING id, branch_id, amount, bank_reference, status, recorded_by, recorded_at, verified_by, verified_at, created_at, updated_at
`

type InsertCashDepositParams struct {
	BranchID      int64          `json:"branchId"`
	Amount        pgtype.Numeric `json:"amount"`
	BankReference string         `json:"bankReference"`
	RecordedBy    pgtype.UUID    `json:"recordedBy"`
}

func (q *Queries) InsertCashDeposit(ctx context.Context, arg InsertCashDepositParams) (CashDeposit, error) {
	row := q.db.QueryRow(ctx, insertCashDeposit,
		arg.BranchID,
		arg.Amount,
		arg.BankReference,
		arg.RecordedBy,
	)
	var i CashDeposit
	err := row.Scan(
		&i.ID,
		&i.BranchID,
		&i.Amount,
		&i.BankReference,
		&i.Status,
		&i.RecordedBy,
		&i.RecordedAt,
		&i.VerifiedBy,
		&i.VerifiedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const insertCashDepositSession = `-- name: InsertCashDepositSession :one
INSERT INTO cash_deposit_sessions (deposit_id, session_id)
VALUES ($1, $2)
ON CONFLICT DO NOTHING
RETURNING deposit_id, session_id, created_at
`

type InsertCashDepositSessionParams struct {
	DepositID pgtype.UUID `json:"depositId"`
	SessionID pgtype.UUID `json:"sessionId"`
}

func (q *Queries) InsertCashDepositSession(ctx context.Context, arg InsertCashDepositSessionParams) (CashDepositSession, error) {
	row := q.db.QueryRow(ctx, insertCashDepositSession, arg.DepositID, arg.SessionID)
	var i CashDepositSession
	err := row.Scan(&i.DepositID, &i.SessionID, &i.CreatedAt)
	return i, err
}

const insertCashierSession = `-- name: InsertCashierSession :one
INSERT INTO cashier_sessions (branch_id, cashier_id)
VALUES ($1, $2)
ON CONFLICT DO NOTHING
RETURNING id, branch_id, cashier_id, status, expected_amount, counted_amount, variance, variance_reason, opened_at, closed_at, closed_by, handed_over_at, handed_over_to, deposited_at, created_at, updated_at
`

type InsertCashierSessionParams struct {
	BranchID  int64       `json:"branchId"`
	CashierID pgtype.UUID `json:"cashierId"`
}

func (q *Queries) InsertCashierSession(ctx context.Context, arg InsertCashierSessionParams) (CashierSession, error) {
	row := q.db.QueryRow(ctx, insertCashierSession, arg.BranchID, arg.CashierID)
	var i CashierSession
	err := row.Scan(
		&i.ID,
		&i.BranchID,
		&i.CashierID,
		&i.Status,
		&i.ExpectedAmount,
		&i.CountedAmount,
		&i.Variance,
		&i.VarianceReason,
		&i.OpenedAt,
		&i.ClosedAt,
		&i.ClosedBy,
		&i.HandedOverAt,
		&i.HandedOverTo,
		&i.DepositedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listCashDepositSessions = `-- name: ListCashDepositSessions :many
SELECT session_id
FROM cash_deposit_sessions
WHERE deposit_id = $1
ORDER BY session_id
`

func (q *Queries) ListCashDepositSessions(ctx context.Context, depositID pgtype.UUID) ([]pgtype.UUID, error) {
	rows, err := q.db.Query(ctx, listCashDepositSessions, depositID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []pgtype.UUID
	for rows.Next() {
		var session_id pgtype.UUID
		if err := rows.Scan(&session_id); err != nil {
			return nil, err
		}
		items = append(items, session_id)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const lockCashierSession = `-- name: LockCashierSession :one
SELECT id, branch_id, cashier_id, status, expected_amount, counted_amount, variance, variance_reason, opened_at, closed_at, closed_by, handed_over_at, handed_over_to, deposited_at, created_at, updated_at
FROM cashier_sessions
WHERE id = $1
FOR UPDATE
`

func (q *Queries) LockCashierSession(ctx context.Context, id pgtype.UUID) (CashierSession, error) {
	row := q.db.QueryRow(ctx, lockCashierSession, id)
	var i CashierSession
	err := row.Scan(
		&i.ID,
		&i.BranchID,
		&i.CashierID,
		&i.Status,
		&i.ExpectedAmount,
		&i.CountedAmount,
		&i.Variance,
		&i.VarianceReason,
		&i.OpenedAt,
		&i.ClosedAt,
		&i.ClosedBy,
		&i.HandedOverAt,
		&i.HandedOverTo,
		&i.DepositedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const lockCashierSessions = `-- name: LockCashierSessions :many
SELECT id, branch_id, cashier_id, status, expected_amount, counted_amount, variance, variance_reason, opened_at, closed_at, closed_by, handed_over_at, handed_over_to, deposited_at, created_at, updated_at
FROM cashier_sessions
WHERE id = ANY($1::UUID[])
ORDER BY id
FOR UPDATE
`

func (q *Queries) LockCashierSessions(ctx context.Context, dollar_1 []pgtype.UUID) ([]CashierSession, error) {
	rows, err := q.db.Query(ctx, lockCashierSessions, dollar_1)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []CashierSession
	for rows.Next() {
		var i CashierSession
		if err := rows.Scan(
			&i.ID,
			&i.BranchID,
			&i.CashierID,
			&i.Status,
			&i.ExpectedAmount,
			&i.CountedAmount,
			&i.Variance,
			&i.VarianceReason,
			&i.OpenedAt,
			&i.ClosedAt,
			&i.ClosedBy,
			&i.HandedOverAt,
			&i.HandedOverTo,
			&i.DepositedAt,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const markCashierSessionDeposited = `-- name: MarkCashierSessionDeposited :one
UPDATE cashier_sessions
SET status = 'deposited',
    deposited_at = NOW(),
    updated_at = NOW()
WHERE id = $1 AND status = 'handed_over'
RETURNING id, branch_id, cashier_id, status, expected_amount, counted_amount, variance, variance_reason, opened_at, closed_at, closed_by, handed_over_at, handed_over_to, deposited_at, created_at, updated_at
`

func (q *Queries) MarkCashierSessionDeposited(ctx context.Context, id pgtype.UUID) (CashierSession, error) {
	row := q.db.QueryRow(ctx, markCashierSessionDeposited, id)
	var i CashierSession
	err := row.Scan(
		&i.ID,
		&i.BranchID,
		&i.CashierID,
		&i.Status,
		&i.ExpectedAmount,
		&i.CountedAmount,
		&i.Variance,
		&i.VarianceReason,
		&i.OpenedAt,
		&i.ClosedAt,
		&i.ClosedBy,
		&i.HandedOverAt,
		&i.HandedOverTo,
		&i.DepositedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const sumCashReceiptsBySession = `-- name: SumCashReceiptsBySession :one
SELECT COALESCE(SUM(received_amount), 0)::NUMERIC(19,4)
FROM contribution_receipts
WHERE cashier_session_id = $1
  AND source_channel = 'cash'
  AND is_deleted = FALSE
`

func (q *Queries) SumCashReceiptsBySession(ctx context.Context, cashierSessionID pgtype.UUID) (pgtype.Numeric, error) {
	row := q.db.QueryRow(ctx, sumCashReceiptsBySession, cashierSessionID)
	var column_1 pgtype.Numeric
	err := row.Scan(&column_1)
	return column_1, err
}

const verifyCashDeposit = `-- name: VerifyCashDeposit :one
UPDATE cash_deposits
SET status = 'verified',
    verified_by = $2,
    verified_at = NOW(),
    updated_at = NOW()
WHERE id = $1 AND status = 'recorded'
RETURNING id, branch_id, amount, bank_reference, status, recorded_by, recorded_at, verified_by, verified_at, created_at, updated_at
`

type VerifyCashDepositParams struct {
	ID         pgtype.UUID `json:"id"`
	VerifiedBy pgtype.UUID `json:"verifiedBy"`
}

func (q *Queries) VerifyCashDeposit(ctx context.Context, arg VerifyCashDepositParams) (CashDeposit, error) {
	row := q.db.QueryRow(ctx, verifyCashDeposit, arg.ID, arg.VerifiedBy)
	var i CashDeposit
	err := row.Scan(
		&i.ID,
		&i.BranchID,
		&i.Amount,
		&i.BankReference,
		&i.Status,
		&i.RecordedBy,
		&i.RecordedAt,
		&i.VerifiedBy,
		&i.VerifiedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
