// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: charges.sql

package contributionsqlc

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createContributionCharge = `-- name: CreateContributionCharge :one
INSERT INTO contribution_charges (idempotency_key, member_id, branch_id, category, amount, reason, created_by)
SELECT $1, m.id, m.branch_id, $2, $3, $4, $5
FROM members m
WHERE m.id = $6 AND m.branch_id = $7 AND NOT m.is_deleted
ON CONFLICT DO NOTHING
RETURNING id, idempotency_key, member_id, branch_id, category, amount, reason, created_by, created_at
`

type CreateContributionChargeParams struct {
	IdempotencyKey string         `json:"idempotencyKey"`
	Category       string         `json:"category"`
	Amount         pgtype.Numeric `json:"amount"`
	Reason         string         `json:"reason"`
	CreatedBy      pgtype.UUID    `json:"createdBy"`
	MemberID       pgtype.UUID    `json:"memberId"`
	BranchID       int64          `json:"branchId"`
}

func (q *Queries) CreateContributionCharge(ctx context.Context, arg CreateContributionChargeParams) (ContributionCharge, error) {
	row := q.db.QueryRow(ctx, createContributionCharge,
		arg.IdempotencyKey,
		arg.Category,
		arg.Amount,
		arg.Reason,
		arg.CreatedBy,
		arg.MemberID,
		arg.BranchID,
	)
	var i ContributionCharge
	err := row.Scan(
		&i.ID,
		&i.IdempotencyKey,
		&i.MemberID,
		&i.BranchID,
		&i.Category,
		&i.Amount,
		&i.Reason,
		&i.CreatedBy,
		&i.CreatedAt,
	)
	return i, err
}

const getContributionChargeByKey = `-- name: GetContributionChargeByKey :one
SELECT id, idempotency_key, member_id, branch_id, category, amount, reason, created_by, created_at FROM contribution_charges WHERE idempotency_key = $1
`

func (q *Queries) GetContributionChargeByKey(ctx context.Context, idempotencyKey string) (ContributionCharge, error) {
	row := q.db.QueryRow(ctx, getContributionChargeByKey, idempotencyKey)
	var i ContributionCharge
	err := row.Scan(
		&i.ID,
		&i.IdempotencyKey,
		&i.MemberID,
		&i.BranchID,
		&i.Category,
		&i.Amount,
		&i.Reason,
		&i.CreatedBy,
		&i.CreatedAt,
	)
	return i, err
}

const listContributionCharges = `-- name: ListContributionCharges :many
SELECT c.id, c.idempotency_key, c.member_id, c.branch_id, c.category, c.amount, c.reason, c.created_by, c.created_at, COALESCE(p.paid, 0)::numeric AS paid
FROM contribution_charges c
LEFT JOIN LATERAL (
    SELECT SUM(a.amount) AS paid FROM contribution_allocations a
    WHERE a.target_id = c.id AND a.type IN ('other_charge', 'penalty') AND a.status = 'completed'
) p ON true
WHERE c.member_id = $1 AND c.branch_id = $2
  AND ($3::timestamptz IS NULL
       OR (c.created_at, c.id) < ($3::timestamptz, $4::uuid))
ORDER BY c.created_at DESC, c.id DESC
LIMIT $5
`

type ListContributionChargesParams struct {
	MemberID        pgtype.UUID        `json:"memberId"`
	BranchID        int64              `json:"branchId"`
	CursorCreatedAt pgtype.Timestamptz `json:"cursorCreatedAt"`
	CursorID        pgtype.UUID        `json:"cursorId"`
	FetchLimit      int32              `json:"fetchLimit"`
}

type ListContributionChargesRow struct {
	ID             pgtype.UUID        `json:"id"`
	IdempotencyKey string             `json:"idempotencyKey"`
	MemberID       pgtype.UUID        `json:"memberId"`
	BranchID       int64              `json:"branchId"`
	Category       string             `json:"category"`
	Amount         pgtype.Numeric     `json:"amount"`
	Reason         string             `json:"reason"`
	CreatedBy      pgtype.UUID        `json:"createdBy"`
	CreatedAt      pgtype.Timestamptz `json:"createdAt"`
	Paid           pgtype.Numeric     `json:"paid"`
}

func (q *Queries) ListContributionCharges(ctx context.Context, arg ListContributionChargesParams) ([]ListContributionChargesRow, error) {
	rows, err := q.db.Query(ctx, listContributionCharges,
		arg.MemberID,
		arg.BranchID,
		arg.CursorCreatedAt,
		arg.CursorID,
		arg.FetchLimit,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListContributionChargesRow
	for rows.Next() {
		var i ListContributionChargesRow
		if err := rows.Scan(
			&i.ID,
			&i.IdempotencyKey,
			&i.MemberID,
			&i.BranchID,
			&i.Category,
			&i.Amount,
			&i.Reason,
			&i.CreatedBy,
			&i.CreatedAt,
			&i.Paid,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const lockContributionCharges = `-- name: LockContributionCharges :many
SELECT id, idempotency_key, member_id, branch_id, category, amount, reason, created_by, created_at FROM contribution_charges WHERE id = ANY($1::uuid[])
ORDER BY id FOR UPDATE
`

func (q *Queries) LockContributionCharges(ctx context.Context, ids []pgtype.UUID) ([]ContributionCharge, error) {
	rows, err := q.db.Query(ctx, lockContributionCharges, ids)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ContributionCharge
	for rows.Next() {
		var i ContributionCharge
		if err := rows.Scan(
			&i.ID,
			&i.IdempotencyKey,
			&i.MemberID,
			&i.BranchID,
			&i.Category,
			&i.Amount,
			&i.Reason,
			&i.CreatedBy,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const sumContributionChargePayments = `-- name: SumContributionChargePayments :one
SELECT COALESCE(SUM(amount), 0)::numeric AS paid
FROM contribution_allocations
WHERE target_id = $1 AND type IN ('other_charge', 'penalty') AND status = 'completed'
  AND ($2::uuid IS NULL OR receipt_id <> $2)
`

type SumContributionChargePaymentsParams struct {
	ChargeID       pgtype.UUID `json:"chargeId"`
	ExcludeReceipt pgtype.UUID `json:"excludeReceipt"`
}

func (q *Queries) SumContributionChargePayments(ctx context.Context, arg SumContributionChargePaymentsParams) (pgtype.Numeric, error) {
	row := q.db.QueryRow(ctx, sumContributionChargePayments, arg.ChargeID, arg.ExcludeReceipt)
	var paid pgtype.Numeric
	err := row.Scan(&paid)
	return paid, err
}
