// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: fees.sql

package contributionsqlc

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const assessMonthlyFees = `-- name: AssessMonthlyFees :exec
INSERT INTO contribution_monthly_fees (member_id, period, type)
SELECT m.id, $1::date, fee.type
FROM members m
CROSS JOIN (VALUES ('com'::contribution_allocation_type), ('lgom'::contribution_allocation_type)) fee(type)
WHERE m.id = $2 AND NOT m.is_deleted
  AND m.created_at < $1::date + INTERVAL '1 month'
  AND COALESCE(
      (SELECT h.to_status FROM member_status_history h
       WHERE h.member_id = m.id AND h.created_at <= ($1::timestamp AT TIME ZONE 'Africa/Nairobi')
       ORDER BY h.created_at DESC, h.id DESC LIMIT 1),
      (SELECT h.from_status FROM member_status_history h
       WHERE h.member_id = m.id AND h.created_at > ($1::timestamp AT TIME ZONE 'Africa/Nairobi')
       ORDER BY h.created_at, h.id LIMIT 1), m.status) = 'active'
ON CONFLICT DO NOTHING
`

type AssessMonthlyFeesParams struct {
	Period   pgtype.Date `json:"period"`
	MemberID pgtype.UUID `json:"memberId"`
}

func (q *Queries) AssessMonthlyFees(ctx context.Context, arg AssessMonthlyFeesParams) error {
	_, err := q.db.Exec(ctx, assessMonthlyFees, arg.Period, arg.MemberID)
	return err
}

const lockMonthlyFees = `-- name: LockMonthlyFees :many
SELECT member_id, period, type, amount, exemption_reason, approved_by, created_at FROM contribution_monthly_fees
WHERE member_id = $1 AND period = $2
ORDER BY type
FOR UPDATE
`

type LockMonthlyFeesParams struct {
	MemberID pgtype.UUID `json:"memberId"`
	Period   pgtype.Date `json:"period"`
}

func (q *Queries) LockMonthlyFees(ctx context.Context, arg LockMonthlyFeesParams) ([]ContributionMonthlyFee, error) {
	rows, err := q.db.Query(ctx, lockMonthlyFees, arg.MemberID, arg.Period)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ContributionMonthlyFee
	for rows.Next() {
		var i ContributionMonthlyFee
		if err := rows.Scan(
			&i.MemberID,
			&i.Period,
			&i.Type,
			&i.Amount,
			&i.ExemptionReason,
			&i.ApprovedBy,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const sumMonthlyFeePayments = `-- name: SumMonthlyFeePayments :one
SELECT COALESCE(SUM(a.amount), 0)::numeric AS paid
FROM contribution_allocations a
JOIN contribution_receipts r ON r.id = a.receipt_id
WHERE r.member_id = $1
  AND r.contribution_period >= $2::date
  AND r.contribution_period < $2::date + INTERVAL '1 month'
  AND a.type = $3 AND a.status = 'completed'
  AND ($4::uuid IS NULL OR r.id <> $4)
`

type SumMonthlyFeePaymentsParams struct {
	MemberID       pgtype.UUID                `json:"memberId"`
	Period         pgtype.Date                `json:"period"`
	Type           ContributionAllocationType `json:"type"`
	ExcludeReceipt pgtype.UUID                `json:"excludeReceipt"`
}

func (q *Queries) SumMonthlyFeePayments(ctx context.Context, arg SumMonthlyFeePaymentsParams) (pgtype.Numeric, error) {
	row := q.db.QueryRow(ctx, sumMonthlyFeePayments,
		arg.MemberID,
		arg.Period,
		arg.Type,
		arg.ExcludeReceipt,
	)
	var paid pgtype.Numeric
	err := row.Scan(&paid)
	return paid, err
}
