// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package contributionsqlc

import (
	"database/sql/driver"
	"fmt"

	"github.com/jackc/pgx/v5/pgtype"
)

type ContributionAllocationStatus string

const (
	ContributionAllocationStatusPending   ContributionAllocationStatus = "pending"
	ContributionAllocationStatusCompleted ContributionAllocationStatus = "completed"
	ContributionAllocationStatusFailed    ContributionAllocationStatus = "failed"
)

func (e *ContributionAllocationStatus) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = ContributionAllocationStatus(s)
	case string:
		*e = ContributionAllocationStatus(s)
	default:
		return fmt.Errorf("unsupported scan type for ContributionAllocationStatus: %T", src)
	}
	return nil
}

type NullContributionAllocationStatus struct {
	ContributionAllocationStatus ContributionAllocationStatus `json:"contributionAllocationStatus"`
	Valid                        bool                         `json:"valid"` // Valid is true if ContributionAllocationStatus is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullContributionAllocationStatus) Scan(value interface{}) error {
	if value == nil {
		ns.ContributionAllocationStatus, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.ContributionAllocationStatus.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullContributionAllocationStatus) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.ContributionAllocationStatus), nil
}

type ContributionAllocationType string

const (
	ContributionAllocationTypeCom               ContributionAllocationType = "com"
	ContributionAllocationTypeLgom              ContributionAllocationType = "lgom"
	ContributionAllocationTypeSharePurchase     ContributionAllocationType = "share_purchase"
	ContributionAllocationTypeLoanPrincipal     ContributionAllocationType = "loan_principal"
	ContributionAllocationTypeLoanInterest      ContributionAllocationType = "loan_interest"
	ContributionAllocationTypePenalty           ContributionAllocationType = "penalty"
	ContributionAllocationTypeOtherCharge       ContributionAllocationType = "other_charge"
	ContributionAllocationTypeOverpaymentCredit ContributionAllocationType = "overpayment_credit"
)

func (e *ContributionAllocationType) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = ContributionAllocationType(s)
	case string:
		*e = ContributionAllocationType(s)
	default:
		return fmt.Errorf("unsupported scan type for ContributionAllocationType: %T", src)
	}
	return nil
}

type NullContributionAllocationType struct {
	ContributionAllocationType ContributionAllocationType `json:"contributionAllocationType"`
	Valid                      bool                       `json:"valid"` // Valid is true if ContributionAllocationType is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullContributionAllocationType) Scan(value interface{}) error {
	if value == nil {
		ns.ContributionAllocationType, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.ContributionAllocationType.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullContributionAllocationType) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.ContributionAllocationType), nil
}

type ContributionReceiptStatus string

const (
	ContributionReceiptStatusPending      ContributionReceiptStatus = "pending"
	ContributionReceiptStatusProcessing   ContributionReceiptStatus = "processing"
	ContributionReceiptStatusCompleted    ContributionReceiptStatus = "completed"
	ContributionReceiptStatusFailed       ContributionReceiptStatus = "failed"
	ContributionReceiptStatusManualReview ContributionReceiptStatus = "manual_review"
)

func (e *ContributionReceiptStatus) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = ContributionReceiptStatus(s)
	case string:
		*e = ContributionReceiptStatus(s)
	default:
		return fmt.Errorf("unsupported scan type for ContributionReceiptStatus: %T", src)
	}
	return nil
}

type NullContributionReceiptStatus struct {
	ContributionReceiptStatus ContributionReceiptStatus `json:"contributionReceiptStatus"`
	Valid                     bool                      `json:"valid"` // Valid is true if ContributionReceiptStatus is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullContributionReceiptStatus) Scan(value interface{}) error {
	if value == nil {
		ns.ContributionReceiptStatus, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.ContributionReceiptStatus.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullContributionReceiptStatus) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.ContributionReceiptStatus), nil
}

type ContributionSourceChannel string

const (
	ContributionSourceChannelDarajaStk     ContributionSourceChannel = "daraja_stk"
	ContributionSourceChannelDarajaPaybill ContributionSourceChannel = "daraja_paybill"
	ContributionSourceChannelCash          ContributionSourceChannel = "cash"
	ContributionSourceChannelManual        ContributionSourceChannel = "manual"
)

func (e *ContributionSourceChannel) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = ContributionSourceChannel(s)
	case string:
		*e = ContributionSourceChannel(s)
	default:
		return fmt.Errorf("unsupported scan type for ContributionSourceChannel: %T", src)
	}
	return nil
}

type NullContributionSourceChannel struct {
	ContributionSourceChannel ContributionSourceChannel `json:"contributionSourceChannel"`
	Valid                     bool                      `json:"valid"` // Valid is true if ContributionSourceChannel is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullContributionSourceChannel) Scan(value interface{}) error {
	if value == nil {
		ns.ContributionSourceChannel, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.ContributionSourceChannel.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullContributionSourceChannel) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.ContributionSourceChannel), nil
}

type ContributionAllocation struct {
	ID                       pgtype.UUID                  `json:"id"`
	ReceiptID                pgtype.UUID                  `json:"receiptId"`
	Type                     ContributionAllocationType   `json:"type"`
	TargetID                 pgtype.UUID                  `json:"targetId"`
	Amount                   pgtype.Numeric               `json:"amount"`
	Status                   ContributionAllocationStatus `json:"status"`
	AuthoritativeReferenceID pgtype.UUID                  `json:"authoritativeReferenceId"`
	ExternalReference        pgtype.Text                  `json:"externalReference"`
	FailureReason            pgtype.Text                  `json:"failureReason"`
	CreatedAt                pgtype.Timestamptz           `json:"createdAt"`
	UpdatedAt                pgtype.Timestamptz           `json:"updatedAt"`
}

type ContributionReceipt struct {
	ID                    pgtype.UUID               `json:"id"`
	SourceChannel         ContributionSourceChannel `json:"sourceChannel"`
	ExternalTransactionID pgtype.Text               `json:"externalTransactionId"`
	CheckoutRequestID     pgtype.Text               `json:"checkoutRequestId"`
	MemberID              pgtype.UUID               `json:"memberId"`
	BranchID              int64                     `json:"branchId"`
	ContributionPeriod    pgtype.Date               `json:"contributionPeriod"`
	ReceivedAmount        pgtype.Numeric            `json:"receivedAmount"`
	AllocationPlan        []byte                    `json:"allocationPlan"`
	Status                ContributionReceiptStatus `json:"status"`
	FailureReason         pgtype.Text               `json:"failureReason"`
	ReceivedBy            pgtype.UUID               `json:"receivedBy"`
	ReceivedAt            pgtype.Timestamptz        `json:"receivedAt"`
	IsDeleted             bool                      `json:"isDeleted"`
	CreatedAt             pgtype.Timestamptz        `json:"createdAt"`
	UpdatedAt             pgtype.Timestamptz        `json:"updatedAt"`
}
