// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: payment_requests.sql

package contributionsqlc

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const getContributionPaymentRequestByCheckoutID = `-- name: GetContributionPaymentRequestByCheckoutID :one
SELECT id, checkout_request_id, member_id, branch_id, contribution_period, expected_amount, allocation_plan, status, receipt_id, failure_reason, requested_by, created_at, updated_at
FROM contribution_payment_requests
WHERE checkout_request_id = $1
`

func (q *Queries) GetContributionPaymentRequestByCheckoutID(ctx context.Context, checkoutRequestID string) (ContributionPaymentRequest, error) {
	row := q.db.QueryRow(ctx, getContributionPaymentRequestByCheckoutID, checkoutRequestID)
	var i ContributionPaymentRequest
	err := row.Scan(
		&i.ID,
		&i.CheckoutRequestID,
		&i.MemberID,
		&i.BranchID,
		&i.ContributionPeriod,
		&i.ExpectedAmount,
		&i.AllocationPlan,
		&i.Status,
		&i.ReceiptID,
		&i.FailureReason,
		&i.RequestedBy,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const insertContributionPaymentRequest = `-- name: InsertContributionPaymentRequest :one
INSERT INTO contribution_payment_requests (
    checkout_request_id,
    member_id,
    branch_id,
    contribution_period,
    expected_amount,
    allocation_plan,
    requested_by
) VALUES (
    $1, $2, $3, $4, $5, $6, $7
)
ON CONFLICT DO NOTHING
RETURNING id, checkout_request_id, member_id, branch_id, contribution_period, expected_amount, allocation_plan, status, receipt_id, failure_reason, requested_by, created_at, updated_at
`

type InsertContributionPaymentRequestParams struct {
	CheckoutRequestID  string         `json:"checkoutRequestId"`
	MemberID           pgtype.UUID    `json:"memberId"`
	BranchID           int64          `json:"branchId"`
	ContributionPeriod pgtype.Date    `json:"contributionPeriod"`
	ExpectedAmount     pgtype.Numeric `json:"expectedAmount"`
	AllocationPlan     []byte         `json:"allocationPlan"`
	RequestedBy        pgtype.UUID    `json:"requestedBy"`
}

func (q *Queries) InsertContributionPaymentRequest(ctx context.Context, arg InsertContributionPaymentRequestParams) (ContributionPaymentRequest, error) {
	row := q.db.QueryRow(ctx, insertContributionPaymentRequest,
		arg.CheckoutRequestID,
		arg.MemberID,
		arg.BranchID,
		arg.ContributionPeriod,
		arg.ExpectedAmount,
		arg.AllocationPlan,
		arg.RequestedBy,
	)
	var i ContributionPaymentRequest
	err := row.Scan(
		&i.ID,
		&i.CheckoutRequestID,
		&i.MemberID,
		&i.BranchID,
		&i.ContributionPeriod,
		&i.ExpectedAmount,
		&i.AllocationPlan,
		&i.Status,
		&i.ReceiptID,
		&i.FailureReason,
		&i.RequestedBy,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const lockContributionPaymentRequestByCheckoutID = `-- name: LockContributionPaymentRequestByCheckoutID :one
SELECT id, checkout_request_id, member_id, branch_id, contribution_period, expected_amount, allocation_plan, status, receipt_id, failure_reason, requested_by, created_at, updated_at
FROM contribution_payment_requests
WHERE checkout_request_id = $1
FOR UPDATE
`

func (q *Queries) LockContributionPaymentRequestByCheckoutID(ctx context.Context, checkoutRequestID string) (ContributionPaymentRequest, error) {
	row := q.db.QueryRow(ctx, lockContributionPaymentRequestByCheckoutID, checkoutRequestID)
	var i ContributionPaymentRequest
	err := row.Scan(
		&i.ID,
		&i.CheckoutRequestID,
		&i.MemberID,
		&i.BranchID,
		&i.ContributionPeriod,
		&i.ExpectedAmount,
		&i.AllocationPlan,
		&i.Status,
		&i.ReceiptID,
		&i.FailureReason,
		&i.RequestedBy,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const updateContributionPaymentRequestCompleted = `-- name: UpdateContributionPaymentRequestCompleted :one
UPDATE contribution_payment_requests
SET status = 'completed',
    receipt_id = $2,
    failure_reason = NULL,
    updated_at = NOW()
WHERE id = $1
RETURNING id, checkout_request_id, member_id, branch_id, contribution_period, expected_amount, allocation_plan, status, receipt_id, failure_reason, requested_by, created_at, updated_at
`

type UpdateContributionPaymentRequestCompletedParams struct {
	ID        pgtype.UUID `json:"id"`
	ReceiptID pgtype.UUID `json:"receiptId"`
}

func (q *Queries) UpdateContributionPaymentRequestCompleted(ctx context.Context, arg UpdateContributionPaymentRequestCompletedParams) (ContributionPaymentRequest, error) {
	row := q.db.QueryRow(ctx, updateContributionPaymentRequestCompleted, arg.ID, arg.ReceiptID)
	var i ContributionPaymentRequest
	err := row.Scan(
		&i.ID,
		&i.CheckoutRequestID,
		&i.MemberID,
		&i.BranchID,
		&i.ContributionPeriod,
		&i.ExpectedAmount,
		&i.AllocationPlan,
		&i.Status,
		&i.ReceiptID,
		&i.FailureReason,
		&i.RequestedBy,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const updateContributionPaymentRequestFailed = `-- name: UpdateContributionPaymentRequestFailed :one
UPDATE contribution_payment_requests
SET status = 'failed',
    failure_reason = $2,
    updated_at = NOW()
WHERE id = $1
RETURNING id, checkout_request_id, member_id, branch_id, contribution_period, expected_amount, allocation_plan, status, receipt_id, failure_reason, requested_by, created_at, updated_at
`

type UpdateContributionPaymentRequestFailedParams struct {
	ID            pgtype.UUID `json:"id"`
	FailureReason pgtype.Text `json:"failureReason"`
}

func (q *Queries) UpdateContributionPaymentRequestFailed(ctx context.Context, arg UpdateContributionPaymentRequestFailedParams) (ContributionPaymentRequest, error) {
	row := q.db.QueryRow(ctx, updateContributionPaymentRequestFailed, arg.ID, arg.FailureReason)
	var i ContributionPaymentRequest
	err := row.Scan(
		&i.ID,
		&i.CheckoutRequestID,
		&i.MemberID,
		&i.BranchID,
		&i.ContributionPeriod,
		&i.ExpectedAmount,
		&i.AllocationPlan,
		&i.Status,
		&i.ReceiptID,
		&i.FailureReason,
		&i.RequestedBy,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
