// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package contributionsqlc

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

type Querier interface {
	GetContributionAllocationByID(ctx context.Context, id pgtype.UUID) (ContributionAllocation, error)
	GetContributionReceiptByCheckoutRequestID(ctx context.Context, checkoutRequestID pgtype.Text) (ContributionReceipt, error)
	GetContributionReceiptByExternalTransactionID(ctx context.Context, externalTransactionID pgtype.Text) (ContributionReceipt, error)
	GetContributionReceiptByID(ctx context.Context, id pgtype.UUID) (ContributionReceipt, error)
	InsertContributionAllocation(ctx context.Context, arg InsertContributionAllocationParams) (ContributionAllocation, error)
	InsertContributionReceipt(ctx context.Context, arg InsertContributionReceiptParams) (ContributionReceipt, error)
	ListContributionAllocationsByReceipt(ctx context.Context, receiptID pgtype.UUID) ([]ContributionAllocation, error)
	ListContributionReceiptsByMember(ctx context.Context, arg ListContributionReceiptsByMemberParams) ([]ContributionReceipt, error)
	LockContributionAllocationsByReceipt(ctx context.Context, receiptID pgtype.UUID) ([]ContributionAllocation, error)
	LockContributionReceiptByID(ctx context.Context, id pgtype.UUID) (ContributionReceipt, error)
	UpdateContributionAllocationCompleted(ctx context.Context, arg UpdateContributionAllocationCompletedParams) (ContributionAllocation, error)
	UpdateContributionAllocationFailed(ctx context.Context, arg UpdateContributionAllocationFailedParams) (ContributionAllocation, error)
	UpdateContributionReceiptStatus(ctx context.Context, arg UpdateContributionReceiptStatusParams) (ContributionReceipt, error)
}

var _ Querier = (*Queries)(nil)
