// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package contributionsqlc

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

type Querier interface {
	AcceptCashHandover(ctx context.Context, arg AcceptCashHandoverParams) (CashierSession, error)
	CloseCashierSession(ctx context.Context, arg CloseCashierSessionParams) (CashierSession, error)
	GetCashDepositByBankReference(ctx context.Context, bankReference string) (CashDeposit, error)
	GetCashDepositByID(ctx context.Context, id pgtype.UUID) (CashDeposit, error)
	GetContributionAllocationByID(ctx context.Context, id pgtype.UUID) (ContributionAllocation, error)
	GetContributionPaymentRequestByCheckoutID(ctx context.Context, checkoutRequestID pgtype.Text) (ContributionPaymentRequest, error)
	GetContributionPaymentRequestByIdempotencyKey(ctx context.Context, idempotencyKey string) (ContributionPaymentRequest, error)
	GetContributionReceiptByCheckoutRequestID(ctx context.Context, checkoutRequestID pgtype.Text) (ContributionReceipt, error)
	GetContributionReceiptByExternalTransactionID(ctx context.Context, externalTransactionID pgtype.Text) (ContributionReceipt, error)
	GetContributionReceiptByID(ctx context.Context, id pgtype.UUID) (ContributionReceipt, error)
	GetContributionReceiptByIdempotencyKey(ctx context.Context, idempotencyKey pgtype.Text) (ContributionReceipt, error)
	GetOpenCashierSession(ctx context.Context, cashierID pgtype.UUID) (CashierSession, error)
	InsertCashDeposit(ctx context.Context, arg InsertCashDepositParams) (CashDeposit, error)
	InsertCashDepositSession(ctx context.Context, arg InsertCashDepositSessionParams) (CashDepositSession, error)
	InsertCashierSession(ctx context.Context, arg InsertCashierSessionParams) (CashierSession, error)
	InsertContributionAllocation(ctx context.Context, arg InsertContributionAllocationParams) (ContributionAllocation, error)
	InsertContributionPaymentRequest(ctx context.Context, arg InsertContributionPaymentRequestParams) (ContributionPaymentRequest, error)
	InsertContributionReceipt(ctx context.Context, arg InsertContributionReceiptParams) (ContributionReceipt, error)
	ListCashDepositSessions(ctx context.Context, depositID pgtype.UUID) ([]pgtype.UUID, error)
	ListContributionAllocationsByReceipt(ctx context.Context, receiptID pgtype.UUID) ([]ContributionAllocation, error)
	ListContributionReceiptsByMember(ctx context.Context, arg ListContributionReceiptsByMemberParams) ([]ContributionReceipt, error)
	LockCashierSession(ctx context.Context, id pgtype.UUID) (CashierSession, error)
	LockCashierSessions(ctx context.Context, dollar_1 []pgtype.UUID) ([]CashierSession, error)
	LockContributionAllocationsByReceipt(ctx context.Context, receiptID pgtype.UUID) ([]ContributionAllocation, error)
	LockContributionPaymentRequestByCheckoutID(ctx context.Context, checkoutRequestID pgtype.Text) (ContributionPaymentRequest, error)
	LockContributionReceiptByID(ctx context.Context, id pgtype.UUID) (ContributionReceipt, error)
	MarkCashierSessionDeposited(ctx context.Context, id pgtype.UUID) (CashierSession, error)
	SumCashReceiptsBySession(ctx context.Context, cashierSessionID pgtype.UUID) (pgtype.Numeric, error)
	UpdateContributionAllocationCompleted(ctx context.Context, arg UpdateContributionAllocationCompletedParams) (ContributionAllocation, error)
	UpdateContributionAllocationFailed(ctx context.Context, arg UpdateContributionAllocationFailedParams) (ContributionAllocation, error)
	UpdateContributionPaymentRequestCheckoutID(ctx context.Context, arg UpdateContributionPaymentRequestCheckoutIDParams) (ContributionPaymentRequest, error)
	UpdateContributionPaymentRequestCompleted(ctx context.Context, arg UpdateContributionPaymentRequestCompletedParams) (ContributionPaymentRequest, error)
	UpdateContributionPaymentRequestFailed(ctx context.Context, arg UpdateContributionPaymentRequestFailedParams) (ContributionPaymentRequest, error)
	UpdateContributionReceiptStatus(ctx context.Context, arg UpdateContributionReceiptStatusParams) (ContributionReceipt, error)
	VerifyCashDeposit(ctx context.Context, arg VerifyCashDepositParams) (CashDeposit, error)
}

var _ Querier = (*Queries)(nil)
