// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: receipts.sql

package contributionsqlc

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const getContributionReceiptByCheckoutRequestID = `-- name: GetContributionReceiptByCheckoutRequestID :one
SELECT id, source_channel, external_transaction_id, checkout_request_id, member_id, branch_id, contribution_period, received_amount, allocation_plan, status, failure_reason, received_by, received_at, is_deleted, created_at, updated_at
FROM contribution_receipts
WHERE checkout_request_id = $1 AND is_deleted = FALSE
`

func (q *Queries) GetContributionReceiptByCheckoutRequestID(ctx context.Context, checkoutRequestID pgtype.Text) (ContributionReceipt, error) {
	row := q.db.QueryRow(ctx, getContributionReceiptByCheckoutRequestID, checkoutRequestID)
	var i ContributionReceipt
	err := row.Scan(
		&i.ID,
		&i.SourceChannel,
		&i.ExternalTransactionID,
		&i.CheckoutRequestID,
		&i.MemberID,
		&i.BranchID,
		&i.ContributionPeriod,
		&i.ReceivedAmount,
		&i.AllocationPlan,
		&i.Status,
		&i.FailureReason,
		&i.ReceivedBy,
		&i.ReceivedAt,
		&i.IsDeleted,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getContributionReceiptByExternalTransactionID = `-- name: GetContributionReceiptByExternalTransactionID :one
SELECT id, source_channel, external_transaction_id, checkout_request_id, member_id, branch_id, contribution_period, received_amount, allocation_plan, status, failure_reason, received_by, received_at, is_deleted, created_at, updated_at
FROM contribution_receipts
WHERE external_transaction_id = $1 AND is_deleted = FALSE
`

func (q *Queries) GetContributionReceiptByExternalTransactionID(ctx context.Context, externalTransactionID pgtype.Text) (ContributionReceipt, error) {
	row := q.db.QueryRow(ctx, getContributionReceiptByExternalTransactionID, externalTransactionID)
	var i ContributionReceipt
	err := row.Scan(
		&i.ID,
		&i.SourceChannel,
		&i.ExternalTransactionID,
		&i.CheckoutRequestID,
		&i.MemberID,
		&i.BranchID,
		&i.ContributionPeriod,
		&i.ReceivedAmount,
		&i.AllocationPlan,
		&i.Status,
		&i.FailureReason,
		&i.ReceivedBy,
		&i.ReceivedAt,
		&i.IsDeleted,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getContributionReceiptByID = `-- name: GetContributionReceiptByID :one
SELECT id, source_channel, external_transaction_id, checkout_request_id, member_id, branch_id, contribution_period, received_amount, allocation_plan, status, failure_reason, received_by, received_at, is_deleted, created_at, updated_at
FROM contribution_receipts
WHERE id = $1 AND is_deleted = FALSE
`

func (q *Queries) GetContributionReceiptByID(ctx context.Context, id pgtype.UUID) (ContributionReceipt, error) {
	row := q.db.QueryRow(ctx, getContributionReceiptByID, id)
	var i ContributionReceipt
	err := row.Scan(
		&i.ID,
		&i.SourceChannel,
		&i.ExternalTransactionID,
		&i.CheckoutRequestID,
		&i.MemberID,
		&i.BranchID,
		&i.ContributionPeriod,
		&i.ReceivedAmount,
		&i.AllocationPlan,
		&i.Status,
		&i.FailureReason,
		&i.ReceivedBy,
		&i.ReceivedAt,
		&i.IsDeleted,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const insertContributionReceipt = `-- name: InsertContributionReceipt :one
INSERT INTO contribution_receipts (
    source_channel,
    external_transaction_id,
    checkout_request_id,
    member_id,
    branch_id,
    contribution_period,
    received_amount,
    allocation_plan,
    status,
    received_by,
    received_at
) VALUES (
    $1, $2, $3, $4, $5, $6, $7, $8, 'pending', $9, $10
)
ON CONFLICT DO NOTHING
RETURNING id, source_channel, external_transaction_id, checkout_request_id, member_id, branch_id, contribution_period, received_amount, allocation_plan, status, failure_reason, received_by, received_at, is_deleted, created_at, updated_at
`

type InsertContributionReceiptParams struct {
	SourceChannel         ContributionSourceChannel `json:"sourceChannel"`
	ExternalTransactionID pgtype.Text               `json:"externalTransactionId"`
	CheckoutRequestID     pgtype.Text               `json:"checkoutRequestId"`
	MemberID              pgtype.UUID               `json:"memberId"`
	BranchID              int64                     `json:"branchId"`
	ContributionPeriod    pgtype.Date               `json:"contributionPeriod"`
	ReceivedAmount        pgtype.Numeric            `json:"receivedAmount"`
	AllocationPlan        []byte                    `json:"allocationPlan"`
	ReceivedBy            pgtype.UUID               `json:"receivedBy"`
	ReceivedAt            pgtype.Timestamptz        `json:"receivedAt"`
}

func (q *Queries) InsertContributionReceipt(ctx context.Context, arg InsertContributionReceiptParams) (ContributionReceipt, error) {
	row := q.db.QueryRow(ctx, insertContributionReceipt,
		arg.SourceChannel,
		arg.ExternalTransactionID,
		arg.CheckoutRequestID,
		arg.MemberID,
		arg.BranchID,
		arg.ContributionPeriod,
		arg.ReceivedAmount,
		arg.AllocationPlan,
		arg.ReceivedBy,
		arg.ReceivedAt,
	)
	var i ContributionReceipt
	err := row.Scan(
		&i.ID,
		&i.SourceChannel,
		&i.ExternalTransactionID,
		&i.CheckoutRequestID,
		&i.MemberID,
		&i.BranchID,
		&i.ContributionPeriod,
		&i.ReceivedAmount,
		&i.AllocationPlan,
		&i.Status,
		&i.FailureReason,
		&i.ReceivedBy,
		&i.ReceivedAt,
		&i.IsDeleted,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listContributionReceiptsByMember = `-- name: ListContributionReceiptsByMember :many
SELECT id, source_channel, external_transaction_id, checkout_request_id, member_id, branch_id, contribution_period, received_amount, allocation_plan, status, failure_reason, received_by, received_at, is_deleted, created_at, updated_at
FROM contribution_receipts
WHERE member_id = $1
  AND is_deleted = FALSE
  AND (
    $2::timestamptz IS NULL
    OR created_at < $2
    OR (created_at = $2 AND id < $3)
  )
ORDER BY created_at DESC, id DESC
LIMIT $4
`

type ListContributionReceiptsByMemberParams struct {
	MemberID        pgtype.UUID        `json:"memberId"`
	CursorCreatedAt pgtype.Timestamptz `json:"cursorCreatedAt"`
	CursorID        pgtype.UUID        `json:"cursorId"`
	Limit           int32              `json:"limit"`
}

func (q *Queries) ListContributionReceiptsByMember(ctx context.Context, arg ListContributionReceiptsByMemberParams) ([]ContributionReceipt, error) {
	rows, err := q.db.Query(ctx, listContributionReceiptsByMember,
		arg.MemberID,
		arg.CursorCreatedAt,
		arg.CursorID,
		arg.Limit,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ContributionReceipt
	for rows.Next() {
		var i ContributionReceipt
		if err := rows.Scan(
			&i.ID,
			&i.SourceChannel,
			&i.ExternalTransactionID,
			&i.CheckoutRequestID,
			&i.MemberID,
			&i.BranchID,
			&i.ContributionPeriod,
			&i.ReceivedAmount,
			&i.AllocationPlan,
			&i.Status,
			&i.FailureReason,
			&i.ReceivedBy,
			&i.ReceivedAt,
			&i.IsDeleted,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const lockContributionReceiptByID = `-- name: LockContributionReceiptByID :one
SELECT id, source_channel, external_transaction_id, checkout_request_id, member_id, branch_id, contribution_period, received_amount, allocation_plan, status, failure_reason, received_by, received_at, is_deleted, created_at, updated_at
FROM contribution_receipts
WHERE id = $1 AND is_deleted = FALSE
FOR UPDATE
`

func (q *Queries) LockContributionReceiptByID(ctx context.Context, id pgtype.UUID) (ContributionReceipt, error) {
	row := q.db.QueryRow(ctx, lockContributionReceiptByID, id)
	var i ContributionReceipt
	err := row.Scan(
		&i.ID,
		&i.SourceChannel,
		&i.ExternalTransactionID,
		&i.CheckoutRequestID,
		&i.MemberID,
		&i.BranchID,
		&i.ContributionPeriod,
		&i.ReceivedAmount,
		&i.AllocationPlan,
		&i.Status,
		&i.FailureReason,
		&i.ReceivedBy,
		&i.ReceivedAt,
		&i.IsDeleted,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const updateContributionReceiptStatus = `-- name: UpdateContributionReceiptStatus :one
UPDATE contribution_receipts
SET status = $2,
    failure_reason = $3,
    updated_at = NOW()
WHERE id = $1 AND is_deleted = FALSE
RETURNING id, source_channel, external_transaction_id, checkout_request_id, member_id, branch_id, contribution_period, received_amount, allocation_plan, status, failure_reason, received_by, received_at, is_deleted, created_at, updated_at
`

type UpdateContributionReceiptStatusParams struct {
	ID            pgtype.UUID               `json:"id"`
	Status        ContributionReceiptStatus `json:"status"`
	FailureReason pgtype.Text               `json:"failureReason"`
}

func (q *Queries) UpdateContributionReceiptStatus(ctx context.Context, arg UpdateContributionReceiptStatusParams) (ContributionReceipt, error) {
	row := q.db.QueryRow(ctx, updateContributionReceiptStatus, arg.ID, arg.Status, arg.FailureReason)
	var i ContributionReceipt
	err := row.Scan(
		&i.ID,
		&i.SourceChannel,
		&i.ExternalTransactionID,
		&i.CheckoutRequestID,
		&i.MemberID,
		&i.BranchID,
		&i.ContributionPeriod,
		&i.ReceivedAmount,
		&i.AllocationPlan,
		&i.Status,
		&i.FailureReason,
		&i.ReceivedBy,
		&i.ReceivedAt,
		&i.IsDeleted,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
