package grpc

import (
	"context"
	"fmt"
	"math/big"

	"github.com/jackc/pgx/v5/pgtype"
	"github.com/yaninyzwitty/caritas-backend/gen/caritas/member/v1"
	"github.com/yaninyzwitty/caritas-backend/internal/member"
	"github.com/yaninyzwitty/caritas-backend/internal/repository/sqlc"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
)

type Server struct {
	memberv1.UnimplementedMemberServiceServer
	memberService *member.Service
}

// Must implement MemberServiceServer interface generated by protobuf to satisfy gRPC server requirements.
// This is the only way to wire the gRPC handlers to the domain service.
func NewServer(memberService *member.Service) *Server {
	return &Server{memberService: memberService}
}

func (s *Server) RegisterMember(ctx context.Context, req *memberv1.RegisterMemberRequest) (*memberv1.RegisterMemberResponse, error) {
	var dateOfBirth pgtype.Date
	if req.GetProfile().GetPersonal().GetDateOfBirth() != nil {
		dateOfBirth = pgtype.Date{Time: req.GetProfile().GetPersonal().GetDateOfBirth().AsTime(), Valid: true}
	} else {
		dateOfBirth.Valid = false
	}

	monthlyIncome := big.NewInt(req.GetProfile().GetEmployment().GetMonthlyIncome().GetUnits())
	profile := sqlc.CreateMemberProfileParams{
		FullName:              req.GetProfile().GetPersonal().GetFullName(),
		Phone:                 req.GetProfile().GetPersonal().GetPhone(),
		Email:                 req.GetProfile().GetPersonal().GetEmail(),
		Address:               pgtype.Text{String: req.GetProfile().GetPersonal().GetAddress(), Valid: req.GetProfile().GetPersonal().GetAddress() != ""},
		DateOfBirth:           dateOfBirth,
		Occupation:            pgtype.Text{String: req.GetProfile().GetEmployment().GetOccupation(), Valid: req.GetProfile().GetEmployment().GetOccupation() != ""},
		Employer:              pgtype.Text{String: req.GetProfile().GetEmployment().GetEmployer(), Valid: req.GetProfile().GetEmployment().GetEmployer() != ""},
		MonthlyIncome:         pgtype.Numeric{Int: monthlyIncome, Exp: -9, Valid: true},
		IDDocumentType:        pgtype.Text{String: req.GetProfile().GetIdDocument().GetType(), Valid: req.GetProfile().GetIdDocument().GetType() != ""},
		IDDocumentNumber:      pgtype.Text{String: req.GetProfile().GetIdDocument().GetNumber(), Valid: req.GetProfile().GetIdDocument().GetNumber() != ""},
		NextOfKinName:         pgtype.Text{String: req.GetProfile().GetNextOfKin().GetName(), Valid: req.GetProfile().GetNextOfKin().GetName() != ""},
		NextOfKinPhone:        pgtype.Text{String: req.GetProfile().GetNextOfKin().GetPhone(), Valid: req.GetProfile().GetNextOfKin().GetPhone() != ""},
		NextOfKinRelationship: pgtype.Text{String: req.GetProfile().GetNextOfKin().GetRelationship().String(), Valid: true},
	}

	member, err := s.memberService.RegisterMember(ctx, req.BranchId, req.NationalId, profile)
	if err != nil {
		return nil, fmt.Errorf("register member: %w", err)
	}

	return &memberv1.RegisterMemberResponse{
		Member: convertToProtoMember(member),
	}, nil
}

func (s *Server) GetMember(ctx context.Context, req *memberv1.GetMemberRequest) (*memberv1.GetMemberResponse, error) {
	var member sqlc.GetMemberByIDRow
	var err error

	switch identifier := req.Identifier.(type) {
	case *memberv1.GetMemberRequest_MemberId:
		member, err = s.memberService.GetMember(ctx, identifier.MemberId)
	case *memberv1.GetMemberRequest_NationalId:
		member, err = s.memberService.GetMemberByNationalID(ctx, req.BranchId, identifier.NationalId)
	default:
		return nil, fmt.Errorf("invalid identifier")
	}

	if err != nil {
		return nil, fmt.Errorf("get member: %w", err)
	}

	return &memberv1.GetMemberResponse{
		Member: convertToProtoMember(member),
	}, nil
}

func (s *Server) ListMembers(ctx context.Context, req *memberv1.ListMembersRequest) (*memberv1.ListMembersResponse, error) {
	limit := req.PageSize
	if limit <= 0 {
		limit = 50
	}

	var pageToken *string
	if req.PageToken != "" {
		pageToken = &req.PageToken
	}

	var statusFilter *string
	if req.StatusFilter != memberv1.MemberStatus_MEMBER_STATUS_UNSPECIFIED {
		status := statusProtoToString(req.StatusFilter)
		statusFilter = &status
	}

	members, err := s.memberService.ListMembers(ctx, req.BranchId, pageToken, limit, statusFilter)
	if err != nil {
		return nil, fmt.Errorf("list members: %w", err)
	}

	var protoMembers []*memberv1.Member
	var nextToken string

	if len(members) > 0 {
		protoMembers = make([]*memberv1.Member, len(members))
		for i, m := range members {
			protoMembers[i] = convertListMemberToProtoMember(m)
		}
		lastMember := members[len(members)-1]
		nextToken = fmt.Sprintf("%d,%d", lastMember.CreatedAt.Time.Unix(), lastMember.ID)
	}

	return &memberv1.ListMembersResponse{
		Members:       protoMembers,
		NextPageToken: nextToken,
	}, nil
}

func (s *Server) UpdateMemberProfile(ctx context.Context, req *memberv1.UpdateMemberProfileRequest) (*memberv1.UpdateMemberProfileResponse, error) {
	var dateOfBirth pgtype.Date
	if req.GetProfile().GetPersonal().GetDateOfBirth() != nil {
		dateOfBirth = pgtype.Date{Time: req.GetProfile().GetPersonal().GetDateOfBirth().AsTime(), Valid: true}
	} else {
		dateOfBirth.Valid = false
	}

	monthlyIncome := big.NewInt(req.GetProfile().GetEmployment().GetMonthlyIncome().GetUnits())
	profile := sqlc.UpdateMemberProfileParams{
		FullName:              req.GetProfile().GetPersonal().GetFullName(),
		Phone:                 req.GetProfile().GetPersonal().GetPhone(),
		Email:                 req.GetProfile().GetPersonal().GetEmail(),
		Address:               pgtype.Text{String: req.GetProfile().GetPersonal().GetAddress(), Valid: req.GetProfile().GetPersonal().GetAddress() != ""},
		DateOfBirth:           dateOfBirth,
		Occupation:            pgtype.Text{String: req.GetProfile().GetEmployment().GetOccupation(), Valid: req.GetProfile().GetEmployment().GetOccupation() != ""},
		Employer:              pgtype.Text{String: req.GetProfile().GetEmployment().GetEmployer(), Valid: req.GetProfile().GetEmployment().GetEmployer() != ""},
		MonthlyIncome:         pgtype.Numeric{Int: monthlyIncome, Exp: -9, Valid: true},
		IDDocumentType:        pgtype.Text{String: req.GetProfile().GetIdDocument().GetType(), Valid: req.GetProfile().GetIdDocument().GetType() != ""},
		IDDocumentNumber:      pgtype.Text{String: req.GetProfile().GetIdDocument().GetNumber(), Valid: req.GetProfile().GetIdDocument().GetNumber() != ""},
		NextOfKinName:         pgtype.Text{String: req.GetProfile().GetNextOfKin().GetName(), Valid: req.GetProfile().GetNextOfKin().GetName() != ""},
		NextOfKinPhone:        pgtype.Text{String: req.GetProfile().GetNextOfKin().GetPhone(), Valid: req.GetProfile().GetNextOfKin().GetPhone() != ""},
		NextOfKinRelationship: pgtype.Text{String: req.GetProfile().GetNextOfKin().GetRelationship().String(), Valid: true},
	}

	if err := s.memberService.UpdateMemberProfile(ctx, req.MemberId, profile); err != nil {
		return nil, fmt.Errorf("update member profile: %w", err)
	}

	member, err := s.memberService.GetMember(ctx, req.MemberId)
	if err != nil {
		return nil, fmt.Errorf("get updated member: %w", err)
	}

	return &memberv1.UpdateMemberProfileResponse{
		Member: convertToProtoMember(member),
	}, nil
}

func (s *Server) UpdateMemberStatus(ctx context.Context, req *memberv1.UpdateMemberStatusRequest) (*memberv1.UpdateMemberStatusResponse, error) {
	status := statusProtoToString(req.NewStatus)
	member, err := s.memberService.UpdateMemberStatus(ctx, req.MemberId, status, req.Reason)
	if err != nil {
		return nil, fmt.Errorf("update member status: %w", err)
	}

	return &memberv1.UpdateMemberStatusResponse{
		Member: convertToProtoMember(member),
	}, nil
}

func (s *Server) CloseMember(ctx context.Context, req *memberv1.CloseMemberRequest) (*memberv1.CloseMemberResponse, error) {
	_, err := s.memberService.CloseMember(ctx, req.MemberId, req.Reason)
	if err != nil {
		return nil, fmt.Errorf("close member: %w", err)
	}

	return &memberv1.CloseMemberResponse{
		Success: true,
	}, nil
}

func (s *Server) GetMemberStatusHistory(ctx context.Context, req *memberv1.GetMemberStatusHistoryRequest) (*memberv1.GetMemberStatusHistoryResponse, error) {
	history, err := s.memberService.GetMemberStatusHistory(ctx, req.MemberId)
	if err != nil {
		return nil, fmt.Errorf("get member status history: %w", err)
	}

	var transitions []*memberv1.StatusTransition
	for _, h := range history {
		transitions = append(transitions, &memberv1.StatusTransition{
			FromStatus: h.FromStatus.String,
			ToStatus:   h.ToStatus,
			Reason:     h.Reason.String,
			OccurredAt: timestampToProto(h.CreatedAt),
		})
	}

	return &memberv1.GetMemberStatusHistoryResponse{
		Transitions: transitions,
	}, nil
}

func convertToProtoMember(m sqlc.GetMemberByIDRow) *memberv1.Member {
	var units int64
	if m.MonthlyIncome.Int != nil {
		units = m.MonthlyIncome.Int.Int64()
	}

	return &memberv1.Member{
		Id:           m.ID,
		BranchId:     m.BranchID,
		MemberNumber: m.MemberNumber,
		NationalId:   m.NationalID,
		Status:       statusStringToProto(m.Status),
		Profile: &memberv1.MemberProfile{
			Personal: &memberv1.PersonalInfo{
				FullName:    m.FullName.String,
				Phone:       m.Phone.String,
				Email:       m.Email.String,
				DateOfBirth: dateToProto(m.DateOfBirth),
				Address:     m.Address.String,
			},
			Employment: &memberv1.Employment{
				Occupation: m.Occupation.String,
				Employer:   m.Employer.String,
				MonthlyIncome: &memberv1.Money{
					CurrencyCode: "KES",
					Units:        units,
					Nanos:        0,
				},
			},
			IdDocument: &memberv1.Identification{
				Type:   m.IDDocumentType.String,
				Number: m.IDDocumentNumber.String,
			},
			NextOfKin: &memberv1.NextOfKin{
				Name:         m.NextOfKinName.String,
				Phone:        m.NextOfKinPhone.String,
				Relationship: relationshipStringToProto(m.NextOfKinRelationship.String),
			},
		},
		RegisteredAt: timestampToProto(m.CreatedAt),
		LastUpdated:  timestampToProto(m.UpdatedAt),
	}
}

func dateToProto(d pgtype.Date) *timestamppb.Timestamp {
	if !d.Valid {
		return nil
	}
	return timestamppb.New(d.Time)
}

func timestampToProto(t pgtype.Timestamptz) *timestamppb.Timestamp {
	if !t.Valid {
		return nil
	}
	return timestamppb.New(t.Time)
}

func convertListMemberToProtoMember(m sqlc.ListMembersByBranchCursorRow) *memberv1.Member {
	var units int64
	if m.MonthlyIncome.Int != nil {
		units = m.MonthlyIncome.Int.Int64()
	}

	return &memberv1.Member{
		Id:           m.ID,
		BranchId:     m.BranchID,
		MemberNumber: m.MemberNumber,
		NationalId:   m.NationalID,
		Status:       statusStringToProto(m.Status),
		Profile: &memberv1.MemberProfile{
			Personal: &memberv1.PersonalInfo{
				FullName:    m.FullName.String,
				Phone:       m.Phone.String,
				Email:       m.Email.String,
				DateOfBirth: dateToProto(m.DateOfBirth),
				Address:     m.Address.String,
			},
			Employment: &memberv1.Employment{
				Occupation: m.Occupation.String,
				Employer:   m.Employer.String,
				MonthlyIncome: &memberv1.Money{
					CurrencyCode: "KES",
					Units:        units,
					Nanos:        0,
				},
			},
			IdDocument: &memberv1.Identification{
				Type:   m.IDDocumentType.String,
				Number: m.IDDocumentNumber.String,
			},
			NextOfKin: &memberv1.NextOfKin{
				Name:         m.NextOfKinName.String,
				Phone:        m.NextOfKinPhone.String,
				Relationship: relationshipStringToProto(m.NextOfKinRelationship.String),
			},
		},
		RegisteredAt: timestampToProto(m.CreatedAt),
		LastUpdated:  timestampToProto(m.UpdatedAt),
	}
}

func statusStringToProto(status string) memberv1.MemberStatus {
	switch status {
	case "pending":
		return memberv1.MemberStatus_MEMBER_STATUS_PENDING
	case "active":
		return memberv1.MemberStatus_MEMBER_STATUS_ACTIVE
	case "suspended":
		return memberv1.MemberStatus_MEMBER_STATUS_SUSPENDED
	case "closed":
		return memberv1.MemberStatus_MEMBER_STATUS_CLOSED
	case "rejected":
		return memberv1.MemberStatus_MEMBER_STATUS_REJECTED
	default:
		return memberv1.MemberStatus_MEMBER_STATUS_UNSPECIFIED
	}
}

func statusProtoToString(status memberv1.MemberStatus) string {
	switch status {
	case memberv1.MemberStatus_MEMBER_STATUS_PENDING:
		return "pending"
	case memberv1.MemberStatus_MEMBER_STATUS_ACTIVE:
		return "active"
	case memberv1.MemberStatus_MEMBER_STATUS_SUSPENDED:
		return "suspended"
	case memberv1.MemberStatus_MEMBER_STATUS_CLOSED:
		return "closed"
	case memberv1.MemberStatus_MEMBER_STATUS_REJECTED:
		return "rejected"
	default:
		return "pending"
	}
}

func relationshipStringToProto(rel string) memberv1.RelationshipType {
	switch rel {
	case "spouse":
		return memberv1.RelationshipType_RELATIONSHIP_TYPE_SPOUSE
	case "child":
		return memberv1.RelationshipType_RELATIONSHIP_TYPE_CHILD
	case "parent":
		return memberv1.RelationshipType_RELATIONSHIP_TYPE_PARENT
	case "sibling":
		return memberv1.RelationshipType_RELATIONSHIP_TYPE_SIBLING
	case "friend":
		return memberv1.RelationshipType_RELATIONSHIP_TYPE_FRIEND
	case "other":
		return memberv1.RelationshipType_RELATIONSHIP_TYPE_OTHER
	default:
		return memberv1.RelationshipType_RELATIONSHIP_TYPE_UNSPECIFIED
	}
}