// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package authsqlc

import (
	"github.com/jackc/pgx/v5/pgtype"
)

type StaffUser struct {
	ID           pgtype.UUID        `json:"id"`
	BranchID     int64              `json:"branchId"`
	Email        string             `json:"email"`
	PasswordHash pgtype.Text        `json:"passwordHash"`
	Role         string             `json:"role"`
	IsActive     bool               `json:"isActive"`
	CreatedAt    pgtype.Timestamptz `json:"createdAt"`
	UpdatedAt    pgtype.Timestamptz `json:"updatedAt"`
	Name         string             `json:"name"`
	AuthUserID   pgtype.Text        `json:"authUserId"`
}
