// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: staff.sql

package authsqlc

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const countStaffUsers = `-- name: CountStaffUsers :one
SELECT count(*) FROM staff_users
`

func (q *Queries) CountStaffUsers(ctx context.Context) (int64, error) {
	row := q.db.QueryRow(ctx, countStaffUsers)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const createStaffUser = `-- name: CreateStaffUser :one
INSERT INTO staff_users (name, branch_id, email, password_hash, role)
VALUES ($1, $2, lower($3), $4, $5)
ON CONFLICT (email) DO NOTHING
RETURNING id, branch_id, email, password_hash, role, is_active, created_at, updated_at, name
`

type CreateStaffUserParams struct {
	Name         string `json:"name"`
	BranchID     int64  `json:"branchId"`
	Email        string `json:"email"`
	PasswordHash string `json:"passwordHash"`
	Role         string `json:"role"`
}

func (q *Queries) CreateStaffUser(ctx context.Context, arg CreateStaffUserParams) (StaffUser, error) {
	row := q.db.QueryRow(ctx, createStaffUser,
		arg.Name,
		arg.BranchID,
		arg.Email,
		arg.PasswordHash,
		arg.Role,
	)
	var i StaffUser
	err := row.Scan(
		&i.ID,
		&i.BranchID,
		&i.Email,
		&i.PasswordHash,
		&i.Role,
		&i.IsActive,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.Name,
	)
	return i, err
}

const deactivateStaffUser = `-- name: DeactivateStaffUser :one
UPDATE staff_users
SET is_active = FALSE,
    updated_at = NOW()
WHERE id = $1
  AND is_active = TRUE
RETURNING id, branch_id, email, password_hash, role, is_active, created_at, updated_at, name
`

func (q *Queries) DeactivateStaffUser(ctx context.Context, id pgtype.UUID) (StaffUser, error) {
	row := q.db.QueryRow(ctx, deactivateStaffUser, id)
	var i StaffUser
	err := row.Scan(
		&i.ID,
		&i.BranchID,
		&i.Email,
		&i.PasswordHash,
		&i.Role,
		&i.IsActive,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.Name,
	)
	return i, err
}

const getActiveStaffByEmail = `-- name: GetActiveStaffByEmail :one
SELECT id, branch_id, email, password_hash, role, is_active, created_at, updated_at, name
FROM staff_users
WHERE lower(email) = lower($1) AND is_active = TRUE
`

func (q *Queries) GetActiveStaffByEmail(ctx context.Context, email string) (StaffUser, error) {
	row := q.db.QueryRow(ctx, getActiveStaffByEmail, email)
	var i StaffUser
	err := row.Scan(
		&i.ID,
		&i.BranchID,
		&i.Email,
		&i.PasswordHash,
		&i.Role,
		&i.IsActive,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.Name,
	)
	return i, err
}

const getActiveStaffByID = `-- name: GetActiveStaffByID :one
SELECT id, branch_id, email, password_hash, role, is_active, created_at, updated_at, name
FROM staff_users
WHERE id = $1 AND is_active = TRUE
`

func (q *Queries) GetActiveStaffByID(ctx context.Context, id pgtype.UUID) (StaffUser, error) {
	row := q.db.QueryRow(ctx, getActiveStaffByID, id)
	var i StaffUser
	err := row.Scan(
		&i.ID,
		&i.BranchID,
		&i.Email,
		&i.PasswordHash,
		&i.Role,
		&i.IsActive,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.Name,
	)
	return i, err
}
