syntax = "proto3";

package auth.v1;

import "google/api/annotations.proto";
import "google/protobuf/timestamp.proto";

service AuthService {
  rpc CreateStaffUser(CreateStaffUserRequest) returns (CreateStaffUserResponse) {
    option (google.api.http) = {
      post: "/api/v1/auth/create-staff-user"
      body: "*"
    };
  }
  rpc DeactivateStaffUser(DeactivateStaffUserRequest) returns (DeactivateStaffUserResponse) {
    option (google.api.http) = {
      post: "/api/v1/auth/deactivate-staff-user"
      body: "*"
    };
  }
}

message StaffUser {
  string id = 1;
  int64 branch_id = 2;
  string email = 3;
  string role = 4;
  bool is_active = 5;
  google.protobuf.Timestamp created_at = 6;
  google.protobuf.Timestamp updated_at = 7;
  string name = 8;
  string auth_user_id = 9;
}

message CreateStaffUserRequest {
  int64 branch_id = 1;
  string email = 2;
  reserved 3;
  reserved "password";
  string role = 4;
  string name = 5;
  string auth_user_id = 6;
}

message CreateStaffUserResponse {
  StaffUser staff_user = 1;
}

message DeactivateStaffUserRequest {
  string staff_user_id = 1;
}

message DeactivateStaffUserResponse {
  StaffUser staff_user = 1;
}
